// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 144.9138641357422,
  "anchorY": 182.19300842285156,
  "bounds": {
    "left": 65,
    "top": 60,
    "right": 214,
    "bottom": 201
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/carapace-castle/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/carapace-castle/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/carapace-castle/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 65,
            "w": 152,
            "h": 138
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 64,
            "w": 152,
            "h": 139
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 64,
            "w": 152,
            "h": 139
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 63,
            "w": 153,
            "h": 140
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 61,
            "w": 152,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 60,
            "w": 152,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 59,
            "w": 152,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 59,
            "w": 151,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 58,
            "w": 151,
            "h": 144
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 59,
            "w": 151,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 59,
            "w": 151,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 60,
            "w": 152,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 61,
            "w": 152,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 63,
            "w": 152,
            "h": 140
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 64,
            "w": 152,
            "h": 139
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 64,
            "w": 152,
            "h": 139
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 69,
            "y": 64,
            "w": 147,
            "h": 139
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 68,
            "y": 62,
            "w": 146,
            "h": 141
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 60,
            "w": 147,
            "h": 143
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 63,
            "w": 151,
            "h": 140
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 61,
            "y": 66,
            "w": 154,
            "h": 137
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 64,
            "w": 156,
            "h": 139
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 60,
            "w": 156,
            "h": 143
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 68,
            "y": 62,
            "w": 151,
            "h": 141
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 65,
            "w": 151,
            "h": 138
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 83,
            "y": 66,
            "w": 139,
            "h": 137
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 86,
            "y": 57,
            "w": 142,
            "h": 146
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 20,
            "y": 57,
            "w": 172,
            "h": 147
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 38,
            "y": 69,
            "w": 144,
            "h": 135
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 55,
            "y": 68,
            "w": 138,
            "h": 136
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 60,
            "y": 67,
            "w": 150,
            "h": 136
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 65,
            "w": 152,
            "h": 138
          }
        }
      ]
    }
  }
};
