// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 144.9138641357422,
  "anchorY": 182.19300842285156,
  "bounds": {
    "left": 65,
    "top": 65,
    "right": 214,
    "bottom": 201
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/carapace-green/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/carapace-green/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/carapace-green/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 70,
            "w": 153,
            "h": 133
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 70,
            "w": 153,
            "h": 133
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 69,
            "w": 153,
            "h": 134
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 68,
            "w": 153,
            "h": 135
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 67,
            "w": 152,
            "h": 136
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 65,
            "w": 152,
            "h": 137
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 64,
            "w": 152,
            "h": 138
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 64,
            "w": 151,
            "h": 138
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 63,
            "w": 151,
            "h": 139
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 64,
            "w": 151,
            "h": 138
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 64,
            "w": 151,
            "h": 138
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 65,
            "w": 152,
            "h": 137
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 67,
            "w": 152,
            "h": 136
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 68,
            "w": 152,
            "h": 135
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 69,
            "w": 153,
            "h": 134
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 70,
            "w": 153,
            "h": 133
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 69,
            "y": 69,
            "w": 147,
            "h": 134
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 68,
            "y": 68,
            "w": 147,
            "h": 135
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 68,
            "w": 149,
            "h": 135
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 71,
            "w": 153,
            "h": 132
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 61,
            "y": 72,
            "w": 156,
            "h": 131
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 69,
            "w": 157,
            "h": 134
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 65,
            "w": 155,
            "h": 138
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 68,
            "y": 67,
            "w": 150,
            "h": 136
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 72,
            "w": 154,
            "h": 131
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 83,
            "y": 71,
            "w": 139,
            "h": 132
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 86,
            "y": 57,
            "w": 139,
            "h": 146
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 20,
            "y": 57,
            "w": 172,
            "h": 147
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 38,
            "y": 75,
            "w": 153,
            "h": 129
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 55,
            "y": 76,
            "w": 150,
            "h": 128
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 60,
            "y": 74,
            "w": 152,
            "h": 129
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 70,
            "w": 153,
            "h": 133
          }
        }
      ]
    }
  }
};
