// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 142.93299865722656,
  "anchorY": 217.8660125732422,
  "bounds": {
    "left": 77,
    "top": 81,
    "right": 209,
    "bottom": 235
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/flower-tulip/idle-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/flower-tulip/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/flower-tulip/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1000,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256
        }
      ]
    }
  }
};
