// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 140.07803344726562,
  "anchorY": 212.69281005859375,
  "bounds": {
    "left": 84,
    "top": 88,
    "right": 199,
    "bottom": 230
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/fungus-rock/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/fungus-rock/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/fungus-rock/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 783.3333611488342,
      "frameDurationMs": 78.33333611488342,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256
        }
      ]
    }
  }
};
