// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 163.67445373535156,
  "anchorY": 202.70169067382812,
  "bounds": {
    "left": 95,
    "top": 70,
    "right": 234,
    "bottom": 217
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/horse-unicorn/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/horse-unicorn/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/horse-unicorn/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 97,
            "y": 69,
            "w": 139,
            "h": 150
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 68,
            "w": 137,
            "h": 151
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 68,
            "w": 137,
            "h": 151
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 69,
            "w": 136,
            "h": 150
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 70,
            "w": 134,
            "h": 149
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 97,
            "y": 71,
            "w": 133,
            "h": 148
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 96,
            "y": 73,
            "w": 132,
            "h": 146
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 95,
            "y": 76,
            "w": 131,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 94,
            "y": 77,
            "w": 131,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 93,
            "y": 78,
            "w": 132,
            "h": 141
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 93,
            "y": 79,
            "w": 133,
            "h": 140
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 93,
            "y": 78,
            "w": 135,
            "h": 141
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 93,
            "y": 77,
            "w": 137,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 94,
            "y": 75,
            "w": 138,
            "h": 144
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 95,
            "y": 73,
            "w": 139,
            "h": 146
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 96,
            "y": 71,
            "w": 139,
            "h": 148
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 65,
            "w": 139,
            "h": 154
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 73,
            "w": 136,
            "h": 146
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 78,
            "w": 138,
            "h": 141
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 79,
            "w": 138,
            "h": 140
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 75,
            "w": 142,
            "h": 144
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 67,
            "w": 145,
            "h": 152
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 61,
            "w": 139,
            "h": 158
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 61,
            "w": 137,
            "h": 158
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 800.000011920929,
      "frameDurationMs": 80.0000011920929,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 68,
            "w": 128,
            "h": 151
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 110,
            "y": 51,
            "w": 118,
            "h": 168
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 114,
            "y": 41,
            "w": 118,
            "h": 178
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 114,
            "y": 38,
            "w": 118,
            "h": 181
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 47,
            "w": 124,
            "h": 172
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 27,
            "y": 96,
            "w": 170,
            "h": 124
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 70,
            "w": 143,
            "h": 150
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 76,
            "y": 65,
            "w": 130,
            "h": 155
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 67,
            "w": 131,
            "h": 152
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 68,
            "w": 131,
            "h": 151
          }
        }
      ]
    }
  }
};
