// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 177.45059204101562,
  "anchorY": 197.86880493164062,
  "bounds": {
    "left": 99,
    "top": 111,
    "right": 224,
    "bottom": 209
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/orcsword-veteran/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/orcsword-veteran/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/orcsword-veteran/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 101,
            "y": 109,
            "w": 125,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 101,
            "y": 109,
            "w": 125,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 102,
            "y": 109,
            "w": 124,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 102,
            "y": 110,
            "w": 124,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 101,
            "y": 110,
            "w": 125,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 100,
            "y": 111,
            "w": 125,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 111,
            "w": 126,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 112,
            "w": 126,
            "h": 99
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 112,
            "w": 127,
            "h": 99
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 97,
            "y": 112,
            "w": 128,
            "h": 99
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 97,
            "y": 112,
            "w": 128,
            "h": 99
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 97,
            "y": 112,
            "w": 128,
            "h": 99
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 111,
            "w": 127,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 110,
            "w": 127,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 110,
            "w": 127,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 100,
            "y": 109,
            "w": 126,
            "h": 102
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 1000,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 103,
            "y": 110,
            "w": 124,
            "h": 101
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 104,
            "y": 108,
            "w": 120,
            "h": 103
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 103,
            "w": 116,
            "h": 108
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 101,
            "w": 117,
            "h": 110
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 104,
            "y": 103,
            "w": 116,
            "h": 108
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 102,
            "y": 108,
            "w": 119,
            "h": 103
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 100,
            "y": 112,
            "w": 126,
            "h": 99
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 110,
            "w": 132,
            "h": 101
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 98,
            "y": 104,
            "w": 136,
            "h": 107
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 101,
            "w": 137,
            "h": 110
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 100,
            "y": 102,
            "w": 134,
            "h": 109
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 102,
            "y": 106,
            "w": 129,
            "h": 105
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 1000,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 100,
            "y": 109,
            "w": 126,
            "h": 102
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 116,
            "y": 105,
            "w": 106,
            "h": 106
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 141,
            "y": 71,
            "w": 86,
            "h": 140
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 139,
            "y": 68,
            "w": 89,
            "h": 143
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 124,
            "y": 45,
            "w": 98,
            "h": 166
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 44,
            "y": 76,
            "w": 166,
            "h": 147
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 82,
            "y": 113,
            "w": 133,
            "h": 98
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 87,
            "y": 110,
            "w": 132,
            "h": 101
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 89,
            "y": 109,
            "w": 133,
            "h": 102
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 94,
            "y": 109,
            "w": 130,
            "h": 102
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 99,
            "y": 109,
            "w": 127,
            "h": 102
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 100,
            "y": 109,
            "w": 126,
            "h": 102
          }
        }
      ]
    }
  }
};
