// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 191.325927734375,
  "anchorY": 196.6731414794922,
  "bounds": {
    "left": 107,
    "top": 110,
    "right": 235,
    "bottom": 208
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/reaper-blood/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/reaper-blood/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/reaper-blood/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 106,
            "y": 109,
            "w": 130,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 107,
            "y": 109,
            "w": 129,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 110,
            "w": 129,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 110,
            "w": 129,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 109,
            "y": 110,
            "w": 128,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 109,
            "y": 111,
            "w": 128,
            "h": 99
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 109,
            "y": 110,
            "w": 128,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 110,
            "w": 129,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 110,
            "w": 129,
            "h": 100
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 107,
            "y": 109,
            "w": 129,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 106,
            "y": 109,
            "w": 130,
            "h": 101
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 833.3333134651184,
      "frameDurationMs": 83.33333134651184,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 107,
            "y": 106,
            "w": 128,
            "h": 104
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 106,
            "y": 100,
            "w": 129,
            "h": 110
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 93,
            "w": 128,
            "h": 117
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 115,
            "y": 94,
            "w": 122,
            "h": 116
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 120,
            "y": 100,
            "w": 117,
            "h": 110
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 113,
            "w": 132,
            "h": 97
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 104,
            "y": 109,
            "w": 133,
            "h": 101
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 104,
            "y": 108,
            "w": 133,
            "h": 102
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 107,
            "w": 131,
            "h": 103
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 106,
            "y": 106,
            "w": 129,
            "h": 104
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 899.9999761581421,
      "frameDurationMs": 81.81817965074019,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 104,
            "y": 102,
            "w": 131,
            "h": 109
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 144,
            "y": 97,
            "w": 90,
            "h": 114
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 147,
            "y": 60,
            "w": 80,
            "h": 148
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 103,
            "y": 47,
            "w": 123,
            "h": 161
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 35,
            "y": 65,
            "w": 193,
            "h": 154
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 125,
            "w": 151,
            "h": 94
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 118,
            "w": 150,
            "h": 99
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 76,
            "y": 117,
            "w": 147,
            "h": 93
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 91,
            "y": 111,
            "w": 139,
            "h": 99
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 108,
            "w": 131,
            "h": 102
          }
        }
      ]
    }
  }
};
