// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 143.09815979003906,
  "anchorY": 192.30584716796875,
  "bounds": {
    "left": 49,
    "top": 77,
    "right": 218,
    "bottom": 217
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/rhino-huge/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/rhino-huge/walk-0.webp",
      "width": 1560,
      "height": 260
    },
    {
      "src": "assets/wildstat/enemies/rhino-huge/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 75,
            "w": 153,
            "h": 144
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 75,
            "w": 153,
            "h": 144
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 76,
            "w": 153,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 76,
            "w": 154,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 77,
            "w": 154,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 78,
            "w": 154,
            "h": 141
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 78,
            "w": 155,
            "h": 141
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 63,
            "y": 79,
            "w": 157,
            "h": 140
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 55,
            "y": 79,
            "w": 165,
            "h": 140
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 51,
            "y": 79,
            "w": 169,
            "h": 140
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 78,
            "w": 171,
            "h": 141
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 47,
            "y": 78,
            "w": 172,
            "h": 141
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 77,
            "w": 171,
            "h": 142
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 76,
            "w": 155,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 76,
            "w": 154,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 75,
            "w": 153,
            "h": 144
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 500,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 58,
            "y": 71,
            "w": 164,
            "h": 148
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 66,
            "y": 68,
            "w": 154,
            "h": 151
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 70,
            "y": 58,
            "w": 152,
            "h": 161
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 67,
            "y": 55,
            "w": 151,
            "h": 164
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 56,
            "y": 59,
            "w": 160,
            "h": 160
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 52,
            "y": 68,
            "w": 168,
            "h": 151
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 916.6666865348817,
      "frameDurationMs": 83.3333351395347,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 75,
            "w": 153,
            "h": 144
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 67,
            "y": 77,
            "w": 151,
            "h": 142
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 67,
            "y": 77,
            "w": 148,
            "h": 142
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 35,
            "y": 60,
            "w": 173,
            "h": 159
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 45,
            "y": 59,
            "w": 164,
            "h": 160
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 60,
            "w": 163,
            "h": 159
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 51,
            "y": 65,
            "w": 162,
            "h": 154
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 57,
            "y": 68,
            "w": 158,
            "h": 151
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 72,
            "w": 155,
            "h": 147
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 64,
            "y": 75,
            "w": 154,
            "h": 144
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 65,
            "y": 75,
            "w": 153,
            "h": 144
          }
        }
      ]
    }
  }
};
