// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 176.6001434326172,
  "anchorY": 196.69456481933594,
  "bounds": {
    "left": 123,
    "top": 124,
    "right": 230,
    "bottom": 211
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/toad-horn/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/toad-horn/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/toad-horn/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 107,
            "h": 91
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 107,
            "h": 91
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 108,
            "h": 91
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 123,
            "w": 109,
            "h": 90
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 124,
            "w": 109,
            "h": 89
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 125,
            "w": 111,
            "h": 88
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 126,
            "w": 111,
            "h": 87
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 126,
            "w": 111,
            "h": 87
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 126,
            "w": 111,
            "h": 87
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 126,
            "w": 111,
            "h": 87
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 126,
            "w": 111,
            "h": 87
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 125,
            "w": 111,
            "h": 88
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 124,
            "w": 109,
            "h": 89
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 123,
            "w": 109,
            "h": 90
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 108,
            "h": 91
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 107,
            "h": 91
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 750,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 107,
            "h": 91
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 119,
            "w": 109,
            "h": 106
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 120,
            "y": 64,
            "w": 106,
            "h": 148
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 41,
            "w": 111,
            "h": 171
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 129,
            "y": 36,
            "w": 98,
            "h": 176
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 126,
            "y": 56,
            "w": 101,
            "h": 156
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 98,
            "w": 109,
            "h": 115
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 121,
            "y": 134,
            "w": 111,
            "h": 79
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 129,
            "w": 109,
            "h": 84
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 750,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 107,
            "h": 91
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 116,
            "w": 107,
            "h": 97
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 118,
            "w": 107,
            "h": 95
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 131,
            "w": 177,
            "h": 82
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 19,
            "y": 134,
            "w": 203,
            "h": 79
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 114,
            "y": 131,
            "w": 112,
            "h": 82
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 118,
            "y": 123,
            "w": 112,
            "h": 90
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 122,
            "y": 122,
            "w": 108,
            "h": 91
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 123,
            "y": 122,
            "w": 107,
            "h": 91
          }
        }
      ]
    }
  }
};
