// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 153.06451416015625,
  "anchorY": 211.43251037597656,
  "bounds": {
    "left": 83,
    "top": 85,
    "right": 232,
    "bottom": 225
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/wingdemon-bomb/idle-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/wingdemon-bomb/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/wingdemon-bomb/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 81,
            "y": 83,
            "w": 153,
            "h": 143
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 90,
            "y": 87,
            "w": 133,
            "h": 139
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 110,
            "y": 89,
            "w": 86,
            "h": 137
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 91,
            "y": 96,
            "w": 132,
            "h": 131
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 81,
            "y": 98,
            "w": 153,
            "h": 129
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 93,
            "y": 94,
            "w": 133,
            "h": 133
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 110,
            "y": 92,
            "w": 86,
            "h": 134
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 93,
            "y": 85,
            "w": 132,
            "h": 141
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 82,
            "y": 78,
            "w": 150,
            "h": 148
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 101,
            "y": 66,
            "w": 131,
            "h": 160
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 113,
            "y": 59,
            "w": 86,
            "h": 167
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 60,
            "w": 128,
            "h": 166
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 84,
            "y": 69,
            "w": 146,
            "h": 157
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 82,
            "w": 128,
            "h": 144
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 107,
            "y": 92,
            "w": 92,
            "h": 135
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 102,
            "y": 91,
            "w": 130,
            "h": 136
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 1000,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 81,
            "y": 83,
            "w": 153,
            "h": 143
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 124,
            "y": 53,
            "w": 80,
            "h": 171
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 78,
            "w": 139,
            "h": 146
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 21,
            "y": 102,
            "w": 131,
            "h": 122
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 34,
            "y": 58,
            "w": 133,
            "h": 166
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 50,
            "y": 37,
            "w": 138,
            "h": 186
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 42,
            "w": 121,
            "h": 182
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 105,
            "y": 61,
            "w": 75,
            "h": 164
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 80,
            "y": 82,
            "w": 153,
            "h": 144
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 107,
            "y": 92,
            "w": 117,
            "h": 134
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 108,
            "y": 88,
            "w": 101,
            "h": 138
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 81,
            "y": 85,
            "w": 153,
            "h": 141
          }
        }
      ]
    }
  }
};
