// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 145.39309692382812,
  "anchorY": 181.99000549316406,
  "bounds": {
    "left": 73,
    "top": 57,
    "right": 228,
    "bottom": 203
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/winter-ice/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/winter-ice/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/winter-ice/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 55,
            "w": 157,
            "h": 150
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 55,
            "w": 158,
            "h": 150
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 56,
            "w": 159,
            "h": 149
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 56,
            "w": 159,
            "h": 149
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 57,
            "w": 159,
            "h": 148
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 58,
            "w": 157,
            "h": 147
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 59,
            "w": 155,
            "h": 146
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 60,
            "w": 154,
            "h": 145
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 60,
            "w": 152,
            "h": 145
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 60,
            "w": 151,
            "h": 145
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 59,
            "w": 149,
            "h": 146
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 58,
            "w": 148,
            "h": 147
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 76,
            "y": 57,
            "w": 148,
            "h": 148
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 76,
            "y": 56,
            "w": 149,
            "h": 149
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 56,
            "w": 151,
            "h": 149
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 55,
            "w": 155,
            "h": 150
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 1000,
      "frameDurationMs": 83.33333333333333,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 78,
            "y": 45,
            "w": 139,
            "h": 160
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 77,
            "y": 48,
            "w": 142,
            "h": 157
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 54,
            "w": 148,
            "h": 151
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 59,
            "w": 152,
            "h": 146
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 56,
            "w": 154,
            "h": 149
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 48,
            "w": 154,
            "h": 157
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 45,
            "w": 154,
            "h": 160
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 48,
            "w": 154,
            "h": 157
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 54,
            "w": 154,
            "h": 151
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 59,
            "w": 152,
            "h": 146
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 56,
            "w": 148,
            "h": 149
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 77,
            "y": 48,
            "w": 142,
            "h": 157
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 78,
            "y": 55,
            "w": 144,
            "h": 150
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 51,
            "w": 144,
            "h": 154
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 91,
            "y": 47,
            "w": 138,
            "h": 158
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 50,
            "w": 157,
            "h": 155
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 25,
            "y": 48,
            "w": 203,
            "h": 157
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 38,
            "y": 49,
            "w": 191,
            "h": 156
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 62,
            "y": 53,
            "w": 164,
            "h": 152
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 78,
            "y": 55,
            "w": 144,
            "h": 150
          }
        }
      ]
    }
  }
};
