// Generated by scripts/import-enemy-sprite.mjs from a local Unity capture.
export default {
  "frameWidth": 256,
  "frameHeight": 256,
  "anchorX": 133.47186279296875,
  "anchorY": 216.7100067138672,
  "bounds": {
    "left": 73,
    "top": 68,
    "right": 197,
    "bottom": 233
  },
  "pages": [
    {
      "src": "assets/wildstat/enemies/worm-poison/idle-0.webp",
      "width": 1820,
      "height": 780
    },
    {
      "src": "assets/wildstat/enemies/worm-poison/walk-0.webp",
      "width": 1820,
      "height": 520
    },
    {
      "src": "assets/wildstat/enemies/worm-poison/attack-0.webp",
      "width": 1820,
      "height": 520
    }
  ],
  "animations": {
    "idle": {
      "loop": true,
      "durationMs": 1333.3333730697632,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 0,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 66,
            "w": 124,
            "h": 169
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 67,
            "w": 124,
            "h": 168
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 68,
            "w": 125,
            "h": 167
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 69,
            "w": 125,
            "h": 166
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 70,
            "w": 126,
            "h": 165
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 71,
            "w": 127,
            "h": 164
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 73,
            "w": 127,
            "h": 162
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 73,
            "w": 128,
            "h": 162
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 74,
            "w": 128,
            "h": 161
          }
        },
        {
          "page": 0,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 73,
            "w": 128,
            "h": 162
          }
        },
        {
          "page": 0,
          "x": 782,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 73,
            "w": 127,
            "h": 162
          }
        },
        {
          "page": 0,
          "x": 1042,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 72,
            "y": 71,
            "w": 127,
            "h": 164
          }
        },
        {
          "page": 0,
          "x": 1302,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 70,
            "w": 126,
            "h": 165
          }
        },
        {
          "page": 0,
          "x": 1562,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 69,
            "w": 125,
            "h": 166
          }
        },
        {
          "page": 0,
          "x": 2,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 68,
            "w": 125,
            "h": 167
          }
        },
        {
          "page": 0,
          "x": 262,
          "y": 522,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 67,
            "w": 124,
            "h": 168
          }
        }
      ]
    },
    "walk": {
      "loop": true,
      "durationMs": 666.6666865348816,
      "frameDurationMs": 83.3333358168602,
      "frames": [
        {
          "page": 1,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 66,
            "w": 124,
            "h": 169
          }
        },
        {
          "page": 1,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 68,
            "w": 126,
            "h": 167
          }
        },
        {
          "page": 1,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 72,
            "w": 130,
            "h": 163
          }
        },
        {
          "page": 1,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 76,
            "w": 136,
            "h": 159
          }
        },
        {
          "page": 1,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 78,
            "w": 138,
            "h": 157
          }
        },
        {
          "page": 1,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 71,
            "y": 76,
            "w": 136,
            "h": 159
          }
        },
        {
          "page": 1,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 73,
            "y": 72,
            "w": 131,
            "h": 163
          }
        },
        {
          "page": 1,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 74,
            "y": 68,
            "w": 127,
            "h": 167
          }
        }
      ]
    },
    "attack": {
      "loop": false,
      "durationMs": 833.3333134651184,
      "frameDurationMs": 83.33333134651184,
      "frames": [
        {
          "page": 2,
          "x": 2,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 66,
            "w": 124,
            "h": 169
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 70,
            "y": 81,
            "w": 134,
            "h": 154
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 46,
            "y": 25,
            "w": 149,
            "h": 210
          }
        },
        {
          "page": 2,
          "x": 782,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 47,
            "y": 24,
            "w": 146,
            "h": 211
          }
        },
        {
          "page": 2,
          "x": 1042,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 19,
            "w": 145,
            "h": 216
          }
        },
        {
          "page": 2,
          "x": 1302,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 21,
            "w": 146,
            "h": 214
          }
        },
        {
          "page": 2,
          "x": 1562,
          "y": 2,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 48,
            "y": 22,
            "w": 147,
            "h": 213
          }
        },
        {
          "page": 2,
          "x": 2,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 62,
            "w": 122,
            "h": 173
          }
        },
        {
          "page": 2,
          "x": 262,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 65,
            "w": 123,
            "h": 170
          }
        },
        {
          "page": 2,
          "x": 522,
          "y": 262,
          "w": 256,
          "h": 256,
          "contentBounds": {
            "x": 75,
            "y": 66,
            "w": 124,
            "h": 169
          }
        }
      ]
    }
  }
};
