// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sender: __t.identity(),
  senderName: __t.string().name("sender_name"),
  message: __t.string(),
  sentAt: __t.timestamp().name("sent_at"),
  replayId: __t.u64().name("replay_id"),
  senderIsGuest: __t.bool().name("sender_is_guest"),
  powerLevel: __t.f32().name("power_level"),
  senderGender: __t.u8().name("sender_gender"),
  moderated: __t.bool(),
});
