// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  clientId: __t.string(),
  clientSecret: __t.string(),
  campaignId: __t.string(),
  silverTierId: __t.string(),
  goldTierId: __t.string(),
  redirectUri: __t.string(),
  diamondTierId: __t.string(),
};
