// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  viewer: __t.identity(),
  displayName: __t.string().name("display_name"),
  firstSeenAt: __t.timestamp().name("first_seen_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  accountType: __t.string().name("account_type"),
  lastProtocolVersion: __t.u32().name("last_protocol_version"),
  label: __t.string(),
});
