// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  identity: __t.identity(),
  displayName: __t.string(),
  maxHp: __t.f32(),
  damage: __t.f32(),
  attackRate: __t.f32(),
  projectileSpeed: __t.f32(),
  projectileCount: __t.u32(),
  attackRange: __t.f32(),
  armor: __t.f32(),
  regen: __t.f32(),
  speed: __t.f32(),
};
