// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  reference: __t.string().primaryKey(),
  owner: __t.string(),
  packId: __t.string().name("pack_id"),
  purchasedAtMs: __t.f64().name("purchased_at_ms"),
  status: __t.string(),
  reservationId: __t.string().name("reservation_id"),
  reason: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
