// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  encounter: __t.u64(),
  enemyHp: __t.u32().name("enemy_hp"),
  damage: __t.u32(),
  kills: __t.u64(),
  lastAttack: __t.u64().name("last_attack"),
  nextAttackAt: __t.u64().name("next_attack_at"),
  respawnAt: __t.u64().name("respawn_at"),
});
