// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  challenger: __t.identity(),
  opponent: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.timestamp().name("started_at"),
  endsAtMicros: __t.u64().name("ends_at_micros"),
  lastResolvedAt: __t.timestamp().name("last_resolved_at"),
  challengerOriginX: __t.f64().name("challenger_origin_x"),
  challengerOriginY: __t.f64().name("challenger_origin_y"),
  opponentOriginX: __t.f64().name("opponent_origin_x"),
  opponentOriginY: __t.f64().name("opponent_origin_y"),
  challengerHp: __t.f32().name("challenger_hp"),
  challengerMaxHp: __t.f32().name("challenger_max_hp"),
  challengerDamage: __t.f32().name("challenger_damage"),
  challengerArmor: __t.f32().name("challenger_armor"),
  challengerAttackRate: __t.f32().name("challenger_attack_rate"),
  opponentHp: __t.f32().name("opponent_hp"),
  opponentMaxHp: __t.f32().name("opponent_max_hp"),
  opponentDamage: __t.f32().name("opponent_damage"),
  opponentArmor: __t.f32().name("opponent_armor"),
  opponentAttackRate: __t.f32().name("opponent_attack_rate"),
});
