// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  challengerName: __t.string().name("challenger_name"),
  opponentName: __t.string().name("opponent_name"),
  winnerName: __t.string().name("winner_name"),
  durationSeconds: __t.f32().name("duration_seconds"),
  challengerMaxHp: __t.f32().name("challenger_max_hp"),
  challengerDamage: __t.f32().name("challenger_damage"),
  challengerArmor: __t.f32().name("challenger_armor"),
  challengerAttackRate: __t.f32().name("challenger_attack_rate"),
  challengerRegen: __t.f32().name("challenger_regen"),
  challengerFinalHp: __t.f32().name("challenger_final_hp"),
  challengerAttacks: __t.u32().name("challenger_attacks"),
  challengerDamageDealt: __t.f32().name("challenger_damage_dealt"),
  challengerRegened: __t.f32().name("challenger_regened"),
  challengerBlocked: __t.f32().name("challenger_blocked"),
  opponentMaxHp: __t.f32().name("opponent_max_hp"),
  opponentDamage: __t.f32().name("opponent_damage"),
  opponentArmor: __t.f32().name("opponent_armor"),
  opponentAttackRate: __t.f32().name("opponent_attack_rate"),
  opponentRegen: __t.f32().name("opponent_regen"),
  opponentFinalHp: __t.f32().name("opponent_final_hp"),
  opponentAttacks: __t.u32().name("opponent_attacks"),
  opponentDamageDealt: __t.f32().name("opponent_damage_dealt"),
  opponentRegened: __t.f32().name("opponent_regened"),
  opponentBlocked: __t.f32().name("opponent_blocked"),
  createdAt: __t.timestamp().name("created_at"),
  challengerIdentity: __t.string().name("challenger_identity"),
  opponentIdentity: __t.string().name("opponent_identity"),
  challengerHeadItem: __t.string().name("challenger_head_item"),
  challengerChestItem: __t.string().name("challenger_chest_item"),
  challengerFeetItem: __t.string().name("challenger_feet_item"),
  challengerRightHandItem: __t.string().name("challenger_right_hand_item"),
  challengerLeftHandItem: __t.string().name("challenger_left_hand_item"),
  opponentHeadItem: __t.string().name("opponent_head_item"),
  opponentChestItem: __t.string().name("opponent_chest_item"),
  opponentFeetItem: __t.string().name("opponent_feet_item"),
  opponentRightHandItem: __t.string().name("opponent_right_hand_item"),
  opponentLeftHandItem: __t.string().name("opponent_left_hand_item"),
});
