// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  duelId: __t.u64().primaryKey().name("duel_id"),
  challengerRiposte: __t.f32().name("challenger_riposte"),
  opponentRiposte: __t.f32().name("opponent_riposte"),
  riposteSeed: __t.u64().name("riposte_seed"),
});
