// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptDuelReducer from "./accept_duel_reducer";
import AcceptTermsReducer from "./accept_terms_reducer";
import AcknowledgeBalanceApologyGiftReducer from "./acknowledge_balance_apology_gift_reducer";
import AcknowledgeOfflineSummaryReducer from "./acknowledge_offline_summary_reducer";
import AcknowledgeReleaseReducer from "./acknowledge_release_reducer";
import AttackForestRewardPrototypeReducer from "./attack_forest_reward_prototype_reducer";
import BeginAccountLinkReducer from "./begin_account_link_reducer";
import BeginAdventureReducer from "./begin_adventure_reducer";
import BeginForestRewardPrototypeReducer from "./begin_forest_reward_prototype_reducer";
import CancelGemPurchaseReducer from "./cancel_gem_purchase_reducer";
import CancelItemUpgradeReducer from "./cancel_item_upgrade_reducer";
import ChallengeGuildReducer from "./challenge_guild_reducer";
import ChangeDisplayNameReducer from "./change_display_name_reducer";
import ChangeMapReducer from "./change_map_reducer";
import ClaimDailyGemBonusReducer from "./claim_daily_gem_bonus_reducer";
import ClaimDeveloperItemGiftReducer from "./claim_developer_item_gift_reducer";
import ClaimGuestAccountReducer from "./claim_guest_account_reducer";
import ClaimMailboxGiftReducer from "./claim_mailbox_gift_reducer";
import CompleteOnboardingStepReducer from "./complete_onboarding_step_reducer";
import ConfigureGemCommerceReducer from "./configure_gem_commerce_reducer";
import ConfigurePatreonReducer from "./configure_patreon_reducer";
import ConvertItemToCosmeticReducer from "./convert_item_to_cosmetic_reducer";
import CreateGuildReducer from "./create_guild_reducer";
import DamageAegisPrimeFromPositionReducer from "./damage_aegis_prime_from_position_reducer";
import DamageDragonReducer from "./damage_dragon_reducer";
import DamageDragonBatchReducer from "./damage_dragon_batch_reducer";
import DamageDragonFromPositionReducer from "./damage_dragon_from_position_reducer";
import DamageDreadreaperFromPositionReducer from "./damage_dreadreaper_from_position_reducer";
import DamageFrostclawFromPositionReducer from "./damage_frostclaw_from_position_reducer";
import DamageGloomrootFromPositionReducer from "./damage_gloomroot_from_position_reducer";
import DamageGravebloomFromPositionReducer from "./damage_gravebloom_from_position_reducer";
import DamageIronhornFromPositionReducer from "./damage_ironhorn_from_position_reducer";
import DamageKoiShogunFromPositionReducer from "./damage_koi_shogun_from_position_reducer";
import DamageMagmaliskFromPositionReducer from "./damage_magmalisk_from_position_reducer";
import DamageMiremawFromPositionReducer from "./damage_miremaw_from_position_reducer";
import DamagePrismshellFromPositionReducer from "./damage_prismshell_from_position_reducer";
import DamageSpiderBatchReducer from "./damage_spider_batch_reducer";
import DamageSpiderFromPositionReducer from "./damage_spider_from_position_reducer";
import DamageTempestKirinFromPositionReducer from "./damage_tempest_kirin_from_position_reducer";
import DamageTidewyrmFromPositionReducer from "./damage_tidewyrm_from_position_reducer";
import DamageVoltwardenFromPositionReducer from "./damage_voltwarden_from_position_reducer";
import DestroyEquipmentReducer from "./destroy_equipment_reducer";
import DevAdjustGemsReducer from "./dev_adjust_gems_reducer";
import DevAnnounceOutageCompensationReducer from "./dev_announce_outage_compensation_reducer";
import DevBeginVirtualPlayerLoadTestReducer from "./dev_begin_virtual_player_load_test_reducer";
import DevClearVirtualPlayersReducer from "./dev_clear_virtual_players_reducer";
import DevCopyPlayerCombatStatsReducer from "./dev_copy_player_combat_stats_reducer";
import DevDeleteBugReportReducer from "./dev_delete_bug_report_reducer";
import DevDeleteLegacyPlayerReducer from "./dev_delete_legacy_player_reducer";
import DevDeliverAlphaTesterGiftsReducer from "./dev_deliver_alpha_tester_gifts_reducer";
import DevDeliverAutofarmTestGiftReducer from "./dev_deliver_autofarm_test_gift_reducer";
import DevDeliverCombatUpdateGiftReducer from "./dev_deliver_combat_update_gift_reducer";
import DevDeliverDisconnectCompensationReducer from "./dev_deliver_disconnect_compensation_reducer";
import DevDeliverEquipmentMailReducer from "./dev_deliver_equipment_mail_reducer";
import DevDeliverOutageCompensationReducer from "./dev_deliver_outage_compensation_reducer";
import DevEraseAccountReducer from "./dev_erase_account_reducer";
import DevGrantEquipmentReducer from "./dev_grant_equipment_reducer";
import DevGrantGemHeartReducer from "./dev_grant_gem_heart_reducer";
import DevGrantRetroactiveKillGemsReducer from "./dev_grant_retroactive_kill_gems_reducer";
import DevPublishMailboxLetterReducer from "./dev_publish_mailbox_letter_reducer";
import DevRepairDisplayNameReducer from "./dev_repair_display_name_reducer";
import DevRepairPlayerJoinedAtReducer from "./dev_repair_player_joined_at_reducer";
import DevResetDailyGemBonusReducer from "./dev_reset_daily_gem_bonus_reducer";
import DevRollbackPlayerProgressionReducer from "./dev_rollback_player_progression_reducer";
import DevSetAccessAuditLabelReducer from "./dev_set_access_audit_label_reducer";
import DevSetEndlessTravelAccessReducer from "./dev_set_endless_travel_access_reducer";
import DevSuspendPlayerAccountReducer from "./dev_suspend_player_account_reducer";
import DevTeleportEndlessReducer from "./dev_teleport_endless_reducer";
import DevUpdatePlayerSaveReducer from "./dev_update_player_save_reducer";
import DisconnectPatreonReducer from "./disconnect_patreon_reducer";
import EnterWorldReducer from "./enter_world_reducer";
import EnterWorldWithTutorialReducer from "./enter_world_with_tutorial_reducer";
import FriendActionReducer from "./friend_action_reducer";
import FulfillGemPurchaseReducer from "./fulfill_gem_purchase_reducer";
import GuildInviteActionReducer from "./guild_invite_action_reducer";
import HitProceduralBossReducer from "./hit_procedural_boss_reducer";
import HitProceduralBossBatchReducer from "./hit_procedural_boss_batch_reducer";
import IngestGemStoreEventReducer from "./ingest_gem_store_event_reducer";
import JoinGuildReducer from "./join_guild_reducer";
import JoinVirtualPlayerLoadTestReducer from "./join_virtual_player_load_test_reducer";
import KickGuildMemberReducer from "./kick_guild_member_reducer";
import LeaveGuildReducer from "./leave_guild_reducer";
import MarkPortalCutsceneSeenReducer from "./mark_portal_cutscene_seen_reducer";
import PrepareProceduralBossReducer from "./prepare_procedural_boss_reducer";
import PrepareWorldActionPositionReducer from "./prepare_world_action_position_reducer";
import PrestigeAccountReducer from "./prestige_account_reducer";
import PulseDuelReducer from "./pulse_duel_reducer";
import ReadMailboxLetterReducer from "./read_mailbox_letter_reducer";
import RecordAutoFarmEnemyDefeatsReducer from "./record_auto_farm_enemy_defeats_reducer";
import RecordCombatCheckpointReducer from "./record_combat_checkpoint_reducer";
import RecordConnectionDiagnosticReducer from "./record_connection_diagnostic_reducer";
import RecordDesertEnemyDefeatReducer from "./record_desert_enemy_defeat_reducer";
import RecordEnemyDefeatsReducer from "./record_enemy_defeats_reducer";
import RecordForestEnemyDefeatReducer from "./record_forest_enemy_defeat_reducer";
import RecordLavaEnemyDefeatReducer from "./record_lava_enemy_defeat_reducer";
import RecordPlayerDeathReducer from "./record_player_death_reducer";
import RecordRegularEnemyDefeatsReducer from "./record_regular_enemy_defeats_reducer";
import RecordSnowEnemyDefeatReducer from "./record_snow_enemy_defeat_reducer";
import RecordStartupTelemetryReducer from "./record_startup_telemetry_reducer";
import RefreshDuelWireAccessReducer from "./refresh_duel_wire_access_reducer";
import RegisterClientVersionReducer from "./register_client_version_reducer";
import RegisterProtocolReducer from "./register_protocol_reducer";
import ReportChatMessageReducer from "./report_chat_message_reducer";
import ReportPlayerReducer from "./report_player_reducer";
import ReportSocialMessageReducer from "./report_social_message_reducer";
import RequestAccountDeletionReducer from "./request_account_deletion_reducer";
import RequestDuelReducer from "./request_duel_reducer";
import RequestPatreonHelpReducer from "./request_patreon_help_reducer";
import ReserveGemPurchaseReducer from "./reserve_gem_purchase_reducer";
import ResetPlayerProgressReducer from "./reset_player_progress_reducer";
import RestoreMapBalanceReducer from "./restore_map_balance_reducer";
import ResumeSessionReducer from "./resume_session_reducer";
import SavePlayerProgressReducer from "./save_player_progress_reducer";
import SeedTemporaryGuildReducer from "./seed_temporary_guild_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import SendChatReplyReducer from "./send_chat_reply_reducer";
import SendSocialMessageReducer from "./send_social_message_reducer";
import SetAudioSettingsReducer from "./set_audio_settings_reducer";
import SetAvatarFrameReducer from "./set_avatar_frame_reducer";
import SetChatMessageReactionReducer from "./set_chat_message_reaction_reducer";
import SetDeveloperNameTagReducer from "./set_developer_name_tag_reducer";
import SetDeveloperPresenceReducer from "./set_developer_presence_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SetGenderReducer from "./set_gender_reducer";
import SetGuildVicePresidentReducer from "./set_guild_vice_president_reducer";
import SetMapBalanceReducer from "./set_map_balance_reducer";
import SetMultiplayerEnabledReducer from "./set_multiplayer_enabled_reducer";
import SetOfflineProgressEnabledReducer from "./set_offline_progress_enabled_reducer";
import SetPlayerBlockedReducer from "./set_player_blocked_reducer";
import SetPlayerMotionInterestReducer from "./set_player_motion_interest_reducer";
import SetPlayerSpriteReducer from "./set_player_sprite_reducer";
import SetProfileIconReducer from "./set_profile_icon_reducer";
import SetReleaseWindowReducer from "./set_release_window_reducer";
import SetSkinToneReducer from "./set_skin_tone_reducer";
import SetSpeedReducer from "./set_speed_reducer";
import ShareDuelReplayReducer from "./share_duel_replay_reducer";
import SimulateTimeAwayReducer from "./simulate_time_away_reducer";
import SpeedUpItemUpgradeWithGemsReducer from "./speed_up_item_upgrade_with_gems_reducer";
import SpeedUpResearchWithGemsReducer from "./speed_up_research_with_gems_reducer";
import SpendPrestigePerkPointReducer from "./spend_prestige_perk_point_reducer";
import StartItemUpgradeReducer from "./start_item_upgrade_reducer";
import StartResearchReducer from "./start_research_reducer";
import SyncPositionReducer from "./sync_position_reducer";
import TakeOverSessionReducer from "./take_over_session_reducer";
import TransferGuildLeadershipReducer from "./transfer_guild_leadership_reducer";
import UnlockInventorySlotReducer from "./unlock_inventory_slot_reducer";
import UnlockSecondUpgradeSlotReducer from "./unlock_second_upgrade_slot_reducer";
import UnlockThirdUpgradeSlotReducer from "./unlock_third_upgrade_slot_reducer";
import UpdateMovementStateReducer from "./update_movement_state_reducer";

// Import all procedure arg schemas
import * as BeginPatreonLinkProcedure from "./begin_patreon_link_procedure";
import * as DevTeleportToPlayerProcedure from "./dev_teleport_to_player_procedure";
import * as GetAnalyticsDashboardProcedure from "./get_analytics_dashboard_procedure";
import * as GetAvatarFramesProcedure from "./get_avatar_frames_procedure";
import * as GetBalanceEditorProcedure from "./get_balance_editor_procedure";
import * as GetChatHistoryProcedure from "./get_chat_history_procedure";
import * as GetChatHistoryWithReactionsProcedure from "./get_chat_history_with_reactions_procedure";
import * as GetChatMessageReactionsProcedure from "./get_chat_message_reactions_procedure";
import * as GetDeveloperTravelTargetProcedure from "./get_developer_travel_target_procedure";
import * as GetGuildHubProcedure from "./get_guild_hub_procedure";
import * as GetGuildPreviewProcedure from "./get_guild_preview_procedure";
import * as GetGuildReplayProcedure from "./get_guild_replay_procedure";
import * as GetLeaderboardPageProcedure from "./get_leaderboard_page_procedure";
import * as GetLeaderboardWindowProcedure from "./get_leaderboard_window_procedure";
import * as GetMapBalanceProcedure from "./get_map_balance_procedure";
import * as GetMapConfigurationProcedure from "./get_map_configuration_procedure";
import * as GetModerationHistoryProcedure from "./get_moderation_history_procedure";
import * as GetNameChangeStatusProcedure from "./get_name_change_status_procedure";
import * as GetPatreonStatusProcedure from "./get_patreon_status_procedure";
import * as GetSocialChatHistoryProcedure from "./get_social_chat_history_procedure";
import * as GetSocialChatHistoryWithReactionsProcedure from "./get_social_chat_history_with_reactions_procedure";
import * as GetSocialHubProcedure from "./get_social_hub_procedure";
import * as PreviewMapBalanceProcedure from "./preview_map_balance_procedure";
import * as RefreshPatreonMembershipProcedure from "./refresh_patreon_membership_procedure";

// Import all table schema definitions
import ActiveItemUpgradeRow from "./active_item_upgrade_table";
import ActiveItemUpgradeSlotThreeRow from "./active_item_upgrade_slot_three_table";
import ActiveItemUpgradeSlotTwoRow from "./active_item_upgrade_slot_two_table";
import ActiveResearchRow from "./active_research_table";
import AegisPrimeBossRow from "./aegis_prime_boss_table";
import AegisPrimeResultRow from "./aegis_prime_result_table";
import BossAttackFrameRow from "./boss_attack_frame_table";
import BossHitResultRow from "./boss_hit_result_table";
import DevAccessAuditRow from "./dev_access_audit_table";
import DevBugReportsRow from "./dev_bug_reports_table";
import DevForestRewardPrototypeRow from "./dev_forest_reward_prototype_table";
import DevGemPurchaseReviewRow from "./dev_gem_purchase_review_table";
import DragonBossRow from "./dragon_boss_table";
import DragonResultRow from "./dragon_result_table";
import DreadreaperBossRow from "./dreadreaper_boss_table";
import DreadreaperResultRow from "./dreadreaper_result_table";
import DuelRow from "./duel_table";
import DuelReplayRow from "./duel_replay_table";
import DuelRiposteRow from "./duel_riposte_table";
import DuelWireAccessRow from "./duel_wire_access_table";
import FrostclawBossRow from "./frostclaw_boss_table";
import FrostclawResultRow from "./frostclaw_result_table";
import GloomrootBossRow from "./gloomroot_boss_table";
import GloomrootResultRow from "./gloomroot_result_table";
import GravebloomBossRow from "./gravebloom_boss_table";
import GravebloomResultRow from "./gravebloom_result_table";
import IronhornBossRow from "./ironhorn_boss_table";
import IronhornResultRow from "./ironhorn_result_table";
import KoiShogunBossRow from "./koi_shogun_boss_table";
import KoiShogunResultRow from "./koi_shogun_result_table";
import LatestChatMessagesRow from "./latest_chat_messages_table";
import LatestChatMessagesWithReactionsRow from "./latest_chat_messages_with_reactions_table";
import LeaderboardEntryRow from "./leaderboard_entry_table";
import MagmaliskBossRow from "./magmalisk_boss_table";
import MagmaliskResultRow from "./magmalisk_result_table";
import MiremawBossRow from "./miremaw_boss_table";
import MiremawResultRow from "./miremaw_result_table";
import MyAudioSettingsRow from "./my_audio_settings_table";
import MyBalanceApologyNoticeRow from "./my_balance_apology_notice_table";
import MyBowSkillsRow from "./my_bow_skills_table";
import MyCutsceneHistoryRow from "./my_cutscene_history_table";
import MyDailyGemBonusRow from "./my_daily_gem_bonus_table";
import MyDefeatSessionRestrictionRow from "./my_defeat_session_restriction_table";
import MyEndlessTravelAccessRow from "./my_endless_travel_access_table";
import MyGemPurchasesRow from "./my_gem_purchases_table";
import MyGemWalletRow from "./my_gem_wallet_table";
import MyInventoryCapacityRow from "./my_inventory_capacity_table";
import MyItemGiftsRow from "./my_item_gifts_table";
import MyLegalConsentRow from "./my_legal_consent_table";
import MyMailboxV2Row from "./my_mailbox_v_2_table";
import MyOfflinePreferenceRow from "./my_offline_preference_table";
import MyOfflineProgressRow from "./my_offline_progress_table";
import MyOnboardingRow from "./my_onboarding_table";
import MyPlayerBlocksRow from "./my_player_blocks_table";
import MyProceduralBossRow from "./my_procedural_boss_table";
import MySocialHubRow from "./my_social_hub_table";
import MySocialMessagesRow from "./my_social_messages_table";
import MySocialMessagesWithReactionsRow from "./my_social_messages_with_reactions_table";
import MyUpgradeBenchRow from "./my_upgrade_bench_table";
import MyUpgradeBenchThirdSlotRow from "./my_upgrade_bench_third_slot_table";
import PatreonTickerSupportersRow from "./patreon_ticker_supporters_table";
import PlayerRow from "./player_table";
import PlayerAccountStatusRow from "./player_account_status_table";
import PlayerChatHeartsRow from "./player_chat_hearts_table";
import PlayerDeathFrameRow from "./player_death_frame_table";
import PlayerGemDropRow from "./player_gem_drop_table";
import PlayerItemDropRow from "./player_item_drop_table";
import PlayerItemUpgradeRow from "./player_item_upgrade_table";
import PlayerLifetimeRow from "./player_lifetime_table";
import PlayerMapFrameRow from "./player_map_frame_table";
import PlayerMapMarkerRow from "./player_map_marker_table";
import PlayerMotionDetailFrameRow from "./player_motion_detail_frame_table";
import PlayerMotionFrameRow from "./player_motion_frame_table";
import PlayerMotionIdentityRow from "./player_motion_identity_table";
import PlayerNameTagRow from "./player_name_tag_table";
import PlayerPrestigeRow from "./player_prestige_table";
import PlayerPrestigePerkRow from "./player_prestige_perk_table";
import PlayerProfileRow from "./player_profile_table";
import PlayerProgressRow from "./player_progress_table";
import PlayerResearchRow from "./player_research_table";
import PrismshellBossRow from "./prismshell_boss_table";
import PrismshellResultRow from "./prismshell_result_table";
import ProceduralBossRow from "./procedural_boss_table";
import ProceduralProgressRow from "./procedural_progress_table";
import ReleaseNoticeRow from "./release_notice_table";
import SpiderBossRow from "./spider_boss_table";
import SpiderResultRow from "./spider_result_table";
import TempestKirinBossRow from "./tempest_kirin_boss_table";
import TempestKirinResultRow from "./tempest_kirin_result_table";
import TidewyrmBossRow from "./tidewyrm_boss_table";
import TidewyrmResultRow from "./tidewyrm_result_table";
import VoltwardenBossRow from "./voltwarden_boss_table";
import VoltwardenResultRow from "./voltwarden_result_table";
import WorldStatusRow from "./world_status_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activeItemUpgrade: __table({
    name: 'active_item_upgrade',
    indexes: [
      { accessor: 'identity', name: 'active_item_upgrade_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'active_item_upgrade_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ActiveItemUpgradeRow),
  activeItemUpgradeSlotThree: __table({
    name: 'active_item_upgrade_slot_three',
    indexes: [
      { accessor: 'identity', name: 'active_item_upgrade_slot_three_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'active_item_upgrade_slot_three_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ActiveItemUpgradeSlotThreeRow),
  activeItemUpgradeSlotTwo: __table({
    name: 'active_item_upgrade_slot_two',
    indexes: [
      { accessor: 'identity', name: 'active_item_upgrade_slot_two_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'active_item_upgrade_slot_two_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ActiveItemUpgradeSlotTwoRow),
  activeResearch: __table({
    name: 'active_research',
    indexes: [
      { accessor: 'identity', name: 'active_research_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'active_research_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ActiveResearchRow),
  aegisPrimeBoss: __table({
    name: 'aegis_prime_boss',
    indexes: [
      { accessor: 'id', name: 'aegis_prime_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'aegis_prime_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AegisPrimeBossRow),
  aegisPrimeResult: __table({
    name: 'aegis_prime_result',
    indexes: [
      { accessor: 'id', name: 'aegis_prime_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'aegis_prime_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AegisPrimeResultRow),
  bossAttackFrame: __table({
    name: 'boss_attack_frame',
    indexes: [
      { accessor: 'byMapZone', name: 'boss_attack_frame_map_id_zone_x_zone_y_idx_btree', algorithm: 'btree', columns: [
        'mapId',
        'zoneX',
        'zoneY',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, BossAttackFrameRow),
  bossHitResult: __table({
    name: 'boss_hit_result',
    indexes: [
      { accessor: 'byIdentity', name: 'boss_hit_result_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, BossHitResultRow),
  dragonBoss: __table({
    name: 'dragon_boss',
    indexes: [
      { accessor: 'id', name: 'dragon_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dragon_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DragonBossRow),
  dragonResult: __table({
    name: 'dragon_result',
    indexes: [
      { accessor: 'id', name: 'dragon_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dragon_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DragonResultRow),
  dreadreaperBoss: __table({
    name: 'dreadreaper_boss',
    indexes: [
      { accessor: 'id', name: 'dreadreaper_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dreadreaper_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DreadreaperBossRow),
  dreadreaperResult: __table({
    name: 'dreadreaper_result',
    indexes: [
      { accessor: 'id', name: 'dreadreaper_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dreadreaper_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DreadreaperResultRow),
  duel: __table({
    name: 'duel',
    indexes: [
      { accessor: 'byChallenger', name: 'duel_challenger_idx_btree', algorithm: 'btree', columns: [
        'challenger',
      ] },
      { accessor: 'combatVersion', name: 'duel_combat_version_idx_btree', algorithm: 'btree', columns: [
        'combatVersion',
      ] },
      { accessor: 'id', name: 'duel_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byOpponent', name: 'duel_opponent_idx_btree', algorithm: 'btree', columns: [
        'opponent',
      ] },
    ],
    constraints: [
      { name: 'duel_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DuelRow),
  duelReplay: __table({
    name: 'duel_replay',
    indexes: [
      { accessor: 'combatVersion', name: 'duel_replay_combat_version_idx_btree', algorithm: 'btree', columns: [
        'combatVersion',
      ] },
      { accessor: 'id', name: 'duel_replay_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'duel_replay_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DuelReplayRow),
  duelRiposte: __table({
    name: 'duel_riposte',
    indexes: [
      { accessor: 'duelId', name: 'duel_riposte_duel_id_idx_btree', algorithm: 'btree', columns: [
        'duelId',
      ] },
    ],
    constraints: [
      { name: 'duel_riposte_duel_id_key', constraint: 'unique', columns: ['duelId'] },
    ],
  }, DuelRiposteRow),
  duelWireAccess: __table({
    name: 'duel_wire_access',
    indexes: [
      { accessor: 'combatVersion', name: 'duel_wire_access_combat_version_idx_btree', algorithm: 'btree', columns: [
        'combatVersion',
      ] },
      { accessor: 'byIdentity', name: 'duel_wire_access_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'key', name: 'duel_wire_access_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'duel_wire_access_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, DuelWireAccessRow),
  frostclawBoss: __table({
    name: 'frostclaw_boss',
    indexes: [
      { accessor: 'id', name: 'frostclaw_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'frostclaw_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FrostclawBossRow),
  frostclawResult: __table({
    name: 'frostclaw_result',
    indexes: [
      { accessor: 'id', name: 'frostclaw_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'frostclaw_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FrostclawResultRow),
  gloomrootBoss: __table({
    name: 'gloomroot_boss',
    indexes: [
      { accessor: 'id', name: 'gloomroot_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gloomroot_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GloomrootBossRow),
  gloomrootResult: __table({
    name: 'gloomroot_result',
    indexes: [
      { accessor: 'id', name: 'gloomroot_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gloomroot_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GloomrootResultRow),
  gravebloomBoss: __table({
    name: 'gravebloom_boss',
    indexes: [
      { accessor: 'id', name: 'gravebloom_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gravebloom_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GravebloomBossRow),
  gravebloomResult: __table({
    name: 'gravebloom_result',
    indexes: [
      { accessor: 'id', name: 'gravebloom_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gravebloom_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GravebloomResultRow),
  ironhornBoss: __table({
    name: 'ironhorn_boss',
    indexes: [
      { accessor: 'id', name: 'ironhorn_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ironhorn_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IronhornBossRow),
  ironhornResult: __table({
    name: 'ironhorn_result',
    indexes: [
      { accessor: 'id', name: 'ironhorn_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ironhorn_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IronhornResultRow),
  koiShogunBoss: __table({
    name: 'koi_shogun_boss',
    indexes: [
      { accessor: 'id', name: 'koi_shogun_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'koi_shogun_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KoiShogunBossRow),
  koiShogunResult: __table({
    name: 'koi_shogun_result',
    indexes: [
      { accessor: 'id', name: 'koi_shogun_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'koi_shogun_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KoiShogunResultRow),
  leaderboardEntry: __table({
    name: 'leaderboard_entry',
    indexes: [
      { accessor: 'identity', name: 'leaderboard_entry_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'leaderboard_entry_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, LeaderboardEntryRow),
  magmaliskBoss: __table({
    name: 'magmalisk_boss',
    indexes: [
      { accessor: 'id', name: 'magmalisk_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'magmalisk_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MagmaliskBossRow),
  magmaliskResult: __table({
    name: 'magmalisk_result',
    indexes: [
      { accessor: 'id', name: 'magmalisk_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'magmalisk_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MagmaliskResultRow),
  miremawBoss: __table({
    name: 'miremaw_boss',
    indexes: [
      { accessor: 'id', name: 'miremaw_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'miremaw_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MiremawBossRow),
  miremawResult: __table({
    name: 'miremaw_result',
    indexes: [
      { accessor: 'id', name: 'miremaw_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'miremaw_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MiremawResultRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byMapZone', name: 'player_map_id_is_visible_zone_x_zone_y_idx_btree', algorithm: 'btree', columns: [
        'mapId',
        'isVisible',
        'zoneX',
        'zoneY',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerAccountStatus: __table({
    name: 'player_account_status',
    indexes: [
      { accessor: 'identity', name: 'player_account_status_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_account_status_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerAccountStatusRow),
  playerChatHearts: __table({
    name: 'player_chat_hearts',
    indexes: [
      { accessor: 'identity', name: 'player_chat_hearts_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_chat_hearts_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerChatHeartsRow),
  playerDeathFrame: __table({
    name: 'player_death_frame',
    indexes: [
      { accessor: 'byMap', name: 'player_death_frame_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
      { accessor: 'byMapZone', name: 'player_death_frame_map_id_zone_x_zone_y_idx_btree', algorithm: 'btree', columns: [
        'mapId',
        'zoneX',
        'zoneY',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, PlayerDeathFrameRow),
  playerGemDrop: __table({
    name: 'player_gem_drop',
    indexes: [
      { accessor: 'identity', name: 'player_gem_drop_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_gem_drop_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
    event: true,
  }, PlayerGemDropRow),
  playerItemDrop: __table({
    name: 'player_item_drop',
    indexes: [
      { accessor: 'byIdentity', name: 'player_item_drop_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'key', name: 'player_item_drop_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'player_item_drop_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, PlayerItemDropRow),
  playerItemUpgrade: __table({
    name: 'player_item_upgrade',
    indexes: [
      { accessor: 'byIdentity', name: 'player_item_upgrade_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'key', name: 'player_item_upgrade_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'player_item_upgrade_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, PlayerItemUpgradeRow),
  playerLifetime: __table({
    name: 'player_lifetime',
    indexes: [
      { accessor: 'identity', name: 'player_lifetime_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_lifetime_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerLifetimeRow),
  playerMapFrame: __table({
    name: 'player_map_frame',
    indexes: [
      { accessor: 'byMap', name: 'player_map_frame_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, PlayerMapFrameRow),
  playerMapMarker: __table({
    name: 'player_map_marker',
    indexes: [
      { accessor: 'identity', name: 'player_map_marker_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byMap', name: 'player_map_marker_map_id_is_visible_idx_btree', algorithm: 'btree', columns: [
        'mapId',
        'isVisible',
      ] },
    ],
    constraints: [
      { name: 'player_map_marker_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerMapMarkerRow),
  playerMotionDetailFrame: __table({
    name: 'player_motion_detail_frame',
    indexes: [
      { accessor: 'byRecipient', name: 'player_motion_detail_frame_recipient_idx_btree', algorithm: 'btree', columns: [
        'recipient',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, PlayerMotionDetailFrameRow),
  playerMotionFrame: __table({
    name: 'player_motion_frame',
    indexes: [
      { accessor: 'byMapZone', name: 'player_motion_frame_map_id_zone_x_zone_y_idx_btree', algorithm: 'btree', columns: [
        'mapId',
        'zoneX',
        'zoneY',
      ] },
    ],
    constraints: [
    ],
    event: true,
  }, PlayerMotionFrameRow),
  playerMotionIdentity: __table({
    name: 'player_motion_identity',
    indexes: [
      { accessor: 'identity', name: 'player_motion_identity_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byMap', name: 'player_motion_identity_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
      { accessor: 'byMapZone', name: 'player_motion_identity_map_id_is_visible_zone_x_zone_y_idx_btree', algorithm: 'btree', columns: [
        'mapId',
        'isVisible',
        'zoneX',
        'zoneY',
      ] },
      { accessor: 'networkId', name: 'player_motion_identity_network_id_idx_btree', algorithm: 'btree', columns: [
        'networkId',
      ] },
    ],
    constraints: [
      { name: 'player_motion_identity_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'player_motion_identity_network_id_key', constraint: 'unique', columns: ['networkId'] },
    ],
  }, PlayerMotionIdentityRow),
  playerNameTag: __table({
    name: 'player_name_tag',
    indexes: [
      { accessor: 'identity', name: 'player_name_tag_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_name_tag_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerNameTagRow),
  playerPrestige: __table({
    name: 'player_prestige',
    indexes: [
      { accessor: 'identity', name: 'player_prestige_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_prestige_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPrestigeRow),
  playerPrestigePerk: __table({
    name: 'player_prestige_perk',
    indexes: [
      { accessor: 'identity', name: 'player_prestige_perk_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_prestige_perk_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPrestigePerkRow),
  playerProfile: __table({
    name: 'player_profile',
    indexes: [
      { accessor: 'identity', name: 'player_profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerProfileRow),
  playerProgress: __table({
    name: 'player_progress',
    indexes: [
      { accessor: 'identity', name: 'player_progress_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_progress_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerProgressRow),
  playerResearch: __table({
    name: 'player_research',
    indexes: [
      { accessor: 'identity', name: 'player_research_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_research_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerResearchRow),
  prismshellBoss: __table({
    name: 'prismshell_boss',
    indexes: [
      { accessor: 'id', name: 'prismshell_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prismshell_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PrismshellBossRow),
  prismshellResult: __table({
    name: 'prismshell_result',
    indexes: [
      { accessor: 'id', name: 'prismshell_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'prismshell_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PrismshellResultRow),
  proceduralBoss: __table({
    name: 'procedural_boss',
    indexes: [
      { accessor: 'mapId', name: 'procedural_boss_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
    ],
    constraints: [
      { name: 'procedural_boss_map_id_key', constraint: 'unique', columns: ['mapId'] },
    ],
  }, ProceduralBossRow),
  proceduralProgress: __table({
    name: 'procedural_progress',
    indexes: [
      { accessor: 'identity', name: 'procedural_progress_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'procedural_progress_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ProceduralProgressRow),
  releaseNotice: __table({
    name: 'release_notice',
    indexes: [
      { accessor: 'id', name: 'release_notice_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'release_notice_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReleaseNoticeRow),
  spiderBoss: __table({
    name: 'spider_boss',
    indexes: [
      { accessor: 'id', name: 'spider_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spider_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpiderBossRow),
  spiderResult: __table({
    name: 'spider_result',
    indexes: [
      { accessor: 'id', name: 'spider_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spider_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpiderResultRow),
  tempestKirinBoss: __table({
    name: 'tempest_kirin_boss',
    indexes: [
      { accessor: 'id', name: 'tempest_kirin_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tempest_kirin_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TempestKirinBossRow),
  tempestKirinResult: __table({
    name: 'tempest_kirin_result',
    indexes: [
      { accessor: 'id', name: 'tempest_kirin_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tempest_kirin_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TempestKirinResultRow),
  tidewyrmBoss: __table({
    name: 'tidewyrm_boss',
    indexes: [
      { accessor: 'id', name: 'tidewyrm_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tidewyrm_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TidewyrmBossRow),
  tidewyrmResult: __table({
    name: 'tidewyrm_result',
    indexes: [
      { accessor: 'id', name: 'tidewyrm_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tidewyrm_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TidewyrmResultRow),
  voltwardenBoss: __table({
    name: 'voltwarden_boss',
    indexes: [
      { accessor: 'id', name: 'voltwarden_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'voltwarden_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VoltwardenBossRow),
  voltwardenResult: __table({
    name: 'voltwarden_result',
    indexes: [
      { accessor: 'id', name: 'voltwarden_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'voltwarden_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VoltwardenResultRow),
  worldStatus: __table({
    name: 'world_status',
    indexes: [
      { accessor: 'id', name: 'world_status_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldStatusRow),
  devAccessAudit: __table({
    name: 'dev_access_audit',
    indexes: [
    ],
    constraints: [
    ],
  }, DevAccessAuditRow),
  devBugReports: __table({
    name: 'dev_bug_reports',
    indexes: [
    ],
    constraints: [
    ],
  }, DevBugReportsRow),
  devForestRewardPrototype: __table({
    name: 'dev_forest_reward_prototype',
    indexes: [
    ],
    constraints: [
    ],
  }, DevForestRewardPrototypeRow),
  devGemPurchaseReview: __table({
    name: 'dev_gem_purchase_review',
    indexes: [
    ],
    constraints: [
    ],
  }, DevGemPurchaseReviewRow),
  latestChatMessages: __table({
    name: 'latest_chat_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, LatestChatMessagesRow),
  latestChatMessagesWithReactions: __table({
    name: 'latest_chat_messages_with_reactions',
    indexes: [
    ],
    constraints: [
    ],
  }, LatestChatMessagesWithReactionsRow),
  myAudioSettings: __table({
    name: 'my_audio_settings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAudioSettingsRow),
  myBalanceApologyNotice: __table({
    name: 'my_balance_apology_notice',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBalanceApologyNoticeRow),
  myBowSkills: __table({
    name: 'my_bow_skills',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBowSkillsRow),
  myCutsceneHistory: __table({
    name: 'my_cutscene_history',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCutsceneHistoryRow),
  myDailyGemBonus: __table({
    name: 'my_daily_gem_bonus',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDailyGemBonusRow),
  myDefeatSessionRestriction: __table({
    name: 'my_defeat_session_restriction',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDefeatSessionRestrictionRow),
  myEndlessTravelAccess: __table({
    name: 'my_endless_travel_access',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEndlessTravelAccessRow),
  myGemPurchases: __table({
    name: 'my_gem_purchases',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGemPurchasesRow),
  myGemWallet: __table({
    name: 'my_gem_wallet',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGemWalletRow),
  myInventoryCapacity: __table({
    name: 'my_inventory_capacity',
    indexes: [
    ],
    constraints: [
    ],
  }, MyInventoryCapacityRow),
  myItemGifts: __table({
    name: 'my_item_gifts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyItemGiftsRow),
  myLegalConsent: __table({
    name: 'my_legal_consent',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLegalConsentRow),
  myMailboxV2: __table({
    name: 'my_mailbox_v2',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMailboxV2Row),
  myOfflinePreference: __table({
    name: 'my_offline_preference',
    indexes: [
    ],
    constraints: [
    ],
  }, MyOfflinePreferenceRow),
  myOfflineProgress: __table({
    name: 'my_offline_progress',
    indexes: [
    ],
    constraints: [
    ],
  }, MyOfflineProgressRow),
  myOnboarding: __table({
    name: 'my_onboarding',
    indexes: [
    ],
    constraints: [
    ],
  }, MyOnboardingRow),
  myPlayerBlocks: __table({
    name: 'my_player_blocks',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerBlocksRow),
  myProceduralBoss: __table({
    name: 'my_procedural_boss',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProceduralBossRow),
  mySocialHub: __table({
    name: 'my_social_hub',
    indexes: [
    ],
    constraints: [
    ],
  }, MySocialHubRow),
  mySocialMessages: __table({
    name: 'my_social_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MySocialMessagesRow),
  mySocialMessagesWithReactions: __table({
    name: 'my_social_messages_with_reactions',
    indexes: [
    ],
    constraints: [
    ],
  }, MySocialMessagesWithReactionsRow),
  myUpgradeBench: __table({
    name: 'my_upgrade_bench',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUpgradeBenchRow),
  myUpgradeBenchThirdSlot: __table({
    name: 'my_upgrade_bench_third_slot',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUpgradeBenchThirdSlotRow),
  patreonTickerSupporters: __table({
    name: 'patreon_ticker_supporters',
    indexes: [
    ],
    constraints: [
    ],
  }, PatreonTickerSupportersRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_duel", AcceptDuelReducer),
  __reducerSchema("accept_terms", AcceptTermsReducer),
  __reducerSchema("acknowledge_balance_apology_gift", AcknowledgeBalanceApologyGiftReducer),
  __reducerSchema("acknowledge_offline_summary", AcknowledgeOfflineSummaryReducer),
  __reducerSchema("acknowledge_release", AcknowledgeReleaseReducer),
  __reducerSchema("attack_forest_reward_prototype", AttackForestRewardPrototypeReducer),
  __reducerSchema("begin_account_link", BeginAccountLinkReducer),
  __reducerSchema("begin_adventure", BeginAdventureReducer),
  __reducerSchema("begin_forest_reward_prototype", BeginForestRewardPrototypeReducer),
  __reducerSchema("cancel_gem_purchase", CancelGemPurchaseReducer),
  __reducerSchema("cancel_item_upgrade", CancelItemUpgradeReducer),
  __reducerSchema("challenge_guild", ChallengeGuildReducer),
  __reducerSchema("change_display_name", ChangeDisplayNameReducer),
  __reducerSchema("change_map", ChangeMapReducer),
  __reducerSchema("claim_daily_gem_bonus", ClaimDailyGemBonusReducer),
  __reducerSchema("claim_developer_item_gift", ClaimDeveloperItemGiftReducer),
  __reducerSchema("claim_guest_account", ClaimGuestAccountReducer),
  __reducerSchema("claim_mailbox_gift", ClaimMailboxGiftReducer),
  __reducerSchema("complete_onboarding_step", CompleteOnboardingStepReducer),
  __reducerSchema("configure_gem_commerce", ConfigureGemCommerceReducer),
  __reducerSchema("configure_patreon", ConfigurePatreonReducer),
  __reducerSchema("convert_item_to_cosmetic", ConvertItemToCosmeticReducer),
  __reducerSchema("create_guild", CreateGuildReducer),
  __reducerSchema("damage_aegis_prime_from_position", DamageAegisPrimeFromPositionReducer),
  __reducerSchema("damage_dragon", DamageDragonReducer),
  __reducerSchema("damage_dragon_batch", DamageDragonBatchReducer),
  __reducerSchema("damage_dragon_from_position", DamageDragonFromPositionReducer),
  __reducerSchema("damage_dreadreaper_from_position", DamageDreadreaperFromPositionReducer),
  __reducerSchema("damage_frostclaw_from_position", DamageFrostclawFromPositionReducer),
  __reducerSchema("damage_gloomroot_from_position", DamageGloomrootFromPositionReducer),
  __reducerSchema("damage_gravebloom_from_position", DamageGravebloomFromPositionReducer),
  __reducerSchema("damage_ironhorn_from_position", DamageIronhornFromPositionReducer),
  __reducerSchema("damage_koi_shogun_from_position", DamageKoiShogunFromPositionReducer),
  __reducerSchema("damage_magmalisk_from_position", DamageMagmaliskFromPositionReducer),
  __reducerSchema("damage_miremaw_from_position", DamageMiremawFromPositionReducer),
  __reducerSchema("damage_prismshell_from_position", DamagePrismshellFromPositionReducer),
  __reducerSchema("damage_spider_batch", DamageSpiderBatchReducer),
  __reducerSchema("damage_spider_from_position", DamageSpiderFromPositionReducer),
  __reducerSchema("damage_tempest_kirin_from_position", DamageTempestKirinFromPositionReducer),
  __reducerSchema("damage_tidewyrm_from_position", DamageTidewyrmFromPositionReducer),
  __reducerSchema("damage_voltwarden_from_position", DamageVoltwardenFromPositionReducer),
  __reducerSchema("destroy_equipment", DestroyEquipmentReducer),
  __reducerSchema("dev_adjust_gems", DevAdjustGemsReducer),
  __reducerSchema("dev_announce_outage_compensation", DevAnnounceOutageCompensationReducer),
  __reducerSchema("dev_begin_virtual_player_load_test", DevBeginVirtualPlayerLoadTestReducer),
  __reducerSchema("dev_clear_virtual_players", DevClearVirtualPlayersReducer),
  __reducerSchema("dev_copy_player_combat_stats", DevCopyPlayerCombatStatsReducer),
  __reducerSchema("dev_delete_bug_report", DevDeleteBugReportReducer),
  __reducerSchema("dev_delete_legacy_player", DevDeleteLegacyPlayerReducer),
  __reducerSchema("dev_deliver_alpha_tester_gifts", DevDeliverAlphaTesterGiftsReducer),
  __reducerSchema("dev_deliver_autofarm_test_gift", DevDeliverAutofarmTestGiftReducer),
  __reducerSchema("dev_deliver_combat_update_gift", DevDeliverCombatUpdateGiftReducer),
  __reducerSchema("dev_deliver_disconnect_compensation", DevDeliverDisconnectCompensationReducer),
  __reducerSchema("dev_deliver_equipment_mail", DevDeliverEquipmentMailReducer),
  __reducerSchema("dev_deliver_outage_compensation", DevDeliverOutageCompensationReducer),
  __reducerSchema("dev_erase_account", DevEraseAccountReducer),
  __reducerSchema("dev_grant_equipment", DevGrantEquipmentReducer),
  __reducerSchema("dev_grant_gem_heart", DevGrantGemHeartReducer),
  __reducerSchema("dev_grant_retroactive_kill_gems", DevGrantRetroactiveKillGemsReducer),
  __reducerSchema("dev_publish_mailbox_letter", DevPublishMailboxLetterReducer),
  __reducerSchema("dev_repair_display_name", DevRepairDisplayNameReducer),
  __reducerSchema("dev_repair_player_joined_at", DevRepairPlayerJoinedAtReducer),
  __reducerSchema("dev_reset_daily_gem_bonus", DevResetDailyGemBonusReducer),
  __reducerSchema("dev_rollback_player_progression", DevRollbackPlayerProgressionReducer),
  __reducerSchema("dev_set_access_audit_label", DevSetAccessAuditLabelReducer),
  __reducerSchema("dev_set_endless_travel_access", DevSetEndlessTravelAccessReducer),
  __reducerSchema("dev_suspend_player_account", DevSuspendPlayerAccountReducer),
  __reducerSchema("dev_teleport_endless", DevTeleportEndlessReducer),
  __reducerSchema("dev_update_player_save", DevUpdatePlayerSaveReducer),
  __reducerSchema("disconnect_patreon", DisconnectPatreonReducer),
  __reducerSchema("enter_world", EnterWorldReducer),
  __reducerSchema("enter_world_with_tutorial", EnterWorldWithTutorialReducer),
  __reducerSchema("friend_action", FriendActionReducer),
  __reducerSchema("fulfill_gem_purchase", FulfillGemPurchaseReducer),
  __reducerSchema("guild_invite_action", GuildInviteActionReducer),
  __reducerSchema("hit_procedural_boss", HitProceduralBossReducer),
  __reducerSchema("hit_procedural_boss_batch", HitProceduralBossBatchReducer),
  __reducerSchema("ingest_gem_store_event", IngestGemStoreEventReducer),
  __reducerSchema("join_guild", JoinGuildReducer),
  __reducerSchema("join_virtual_player_load_test", JoinVirtualPlayerLoadTestReducer),
  __reducerSchema("kick_guild_member", KickGuildMemberReducer),
  __reducerSchema("leave_guild", LeaveGuildReducer),
  __reducerSchema("mark_portal_cutscene_seen", MarkPortalCutsceneSeenReducer),
  __reducerSchema("prepare_procedural_boss", PrepareProceduralBossReducer),
  __reducerSchema("prepare_world_action_position", PrepareWorldActionPositionReducer),
  __reducerSchema("prestige_account", PrestigeAccountReducer),
  __reducerSchema("pulse_duel", PulseDuelReducer),
  __reducerSchema("read_mailbox_letter", ReadMailboxLetterReducer),
  __reducerSchema("record_auto_farm_enemy_defeats", RecordAutoFarmEnemyDefeatsReducer),
  __reducerSchema("record_combat_checkpoint", RecordCombatCheckpointReducer),
  __reducerSchema("record_connection_diagnostic", RecordConnectionDiagnosticReducer),
  __reducerSchema("record_desert_enemy_defeat", RecordDesertEnemyDefeatReducer),
  __reducerSchema("record_enemy_defeats", RecordEnemyDefeatsReducer),
  __reducerSchema("record_forest_enemy_defeat", RecordForestEnemyDefeatReducer),
  __reducerSchema("record_lava_enemy_defeat", RecordLavaEnemyDefeatReducer),
  __reducerSchema("record_player_death", RecordPlayerDeathReducer),
  __reducerSchema("record_regular_enemy_defeats", RecordRegularEnemyDefeatsReducer),
  __reducerSchema("record_snow_enemy_defeat", RecordSnowEnemyDefeatReducer),
  __reducerSchema("record_startup_telemetry", RecordStartupTelemetryReducer),
  __reducerSchema("refresh_duel_wire_access", RefreshDuelWireAccessReducer),
  __reducerSchema("register_client_version", RegisterClientVersionReducer),
  __reducerSchema("register_protocol", RegisterProtocolReducer),
  __reducerSchema("report_chat_message", ReportChatMessageReducer),
  __reducerSchema("report_player", ReportPlayerReducer),
  __reducerSchema("report_social_message", ReportSocialMessageReducer),
  __reducerSchema("request_account_deletion", RequestAccountDeletionReducer),
  __reducerSchema("request_duel", RequestDuelReducer),
  __reducerSchema("request_patreon_help", RequestPatreonHelpReducer),
  __reducerSchema("reserve_gem_purchase", ReserveGemPurchaseReducer),
  __reducerSchema("reset_player_progress", ResetPlayerProgressReducer),
  __reducerSchema("restore_map_balance", RestoreMapBalanceReducer),
  __reducerSchema("resume_session", ResumeSessionReducer),
  __reducerSchema("save_player_progress", SavePlayerProgressReducer),
  __reducerSchema("seed_temporary_guild", SeedTemporaryGuildReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("send_chat_reply", SendChatReplyReducer),
  __reducerSchema("send_social_message", SendSocialMessageReducer),
  __reducerSchema("set_audio_settings", SetAudioSettingsReducer),
  __reducerSchema("set_avatar_frame", SetAvatarFrameReducer),
  __reducerSchema("set_chat_message_reaction", SetChatMessageReactionReducer),
  __reducerSchema("set_developer_name_tag", SetDeveloperNameTagReducer),
  __reducerSchema("set_developer_presence", SetDeveloperPresenceReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("set_gender", SetGenderReducer),
  __reducerSchema("set_guild_vice_president", SetGuildVicePresidentReducer),
  __reducerSchema("set_map_balance", SetMapBalanceReducer),
  __reducerSchema("set_multiplayer_enabled", SetMultiplayerEnabledReducer),
  __reducerSchema("set_offline_progress_enabled", SetOfflineProgressEnabledReducer),
  __reducerSchema("set_player_blocked", SetPlayerBlockedReducer),
  __reducerSchema("set_player_motion_interest", SetPlayerMotionInterestReducer),
  __reducerSchema("set_player_sprite", SetPlayerSpriteReducer),
  __reducerSchema("set_profile_icon", SetProfileIconReducer),
  __reducerSchema("set_release_window", SetReleaseWindowReducer),
  __reducerSchema("set_skin_tone", SetSkinToneReducer),
  __reducerSchema("set_speed", SetSpeedReducer),
  __reducerSchema("share_duel_replay", ShareDuelReplayReducer),
  __reducerSchema("simulate_time_away", SimulateTimeAwayReducer),
  __reducerSchema("speed_up_item_upgrade_with_gems", SpeedUpItemUpgradeWithGemsReducer),
  __reducerSchema("speed_up_research_with_gems", SpeedUpResearchWithGemsReducer),
  __reducerSchema("spend_prestige_perk_point", SpendPrestigePerkPointReducer),
  __reducerSchema("start_item_upgrade", StartItemUpgradeReducer),
  __reducerSchema("start_research", StartResearchReducer),
  __reducerSchema("sync_position", SyncPositionReducer),
  __reducerSchema("take_over_session", TakeOverSessionReducer),
  __reducerSchema("transfer_guild_leadership", TransferGuildLeadershipReducer),
  __reducerSchema("unlock_inventory_slot", UnlockInventorySlotReducer),
  __reducerSchema("unlock_second_upgrade_slot", UnlockSecondUpgradeSlotReducer),
  __reducerSchema("unlock_third_upgrade_slot", UnlockThirdUpgradeSlotReducer),
  __reducerSchema("update_movement_state", UpdateMovementStateReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("begin_patreon_link", BeginPatreonLinkProcedure.params, BeginPatreonLinkProcedure.returnType),
  __procedureSchema("dev_teleport_to_player", DevTeleportToPlayerProcedure.params, DevTeleportToPlayerProcedure.returnType),
  __procedureSchema("get_analytics_dashboard", GetAnalyticsDashboardProcedure.params, GetAnalyticsDashboardProcedure.returnType),
  __procedureSchema("get_avatar_frames", GetAvatarFramesProcedure.params, GetAvatarFramesProcedure.returnType),
  __procedureSchema("get_balance_editor", GetBalanceEditorProcedure.params, GetBalanceEditorProcedure.returnType),
  __procedureSchema("get_chat_history", GetChatHistoryProcedure.params, GetChatHistoryProcedure.returnType),
  __procedureSchema("get_chat_history_with_reactions", GetChatHistoryWithReactionsProcedure.params, GetChatHistoryWithReactionsProcedure.returnType),
  __procedureSchema("get_chat_message_reactions", GetChatMessageReactionsProcedure.params, GetChatMessageReactionsProcedure.returnType),
  __procedureSchema("get_developer_travel_target", GetDeveloperTravelTargetProcedure.params, GetDeveloperTravelTargetProcedure.returnType),
  __procedureSchema("get_guild_hub", GetGuildHubProcedure.params, GetGuildHubProcedure.returnType),
  __procedureSchema("get_guild_preview", GetGuildPreviewProcedure.params, GetGuildPreviewProcedure.returnType),
  __procedureSchema("get_guild_replay", GetGuildReplayProcedure.params, GetGuildReplayProcedure.returnType),
  __procedureSchema("get_leaderboard_page", GetLeaderboardPageProcedure.params, GetLeaderboardPageProcedure.returnType),
  __procedureSchema("get_leaderboard_window", GetLeaderboardWindowProcedure.params, GetLeaderboardWindowProcedure.returnType),
  __procedureSchema("get_map_balance", GetMapBalanceProcedure.params, GetMapBalanceProcedure.returnType),
  __procedureSchema("get_map_configuration", GetMapConfigurationProcedure.params, GetMapConfigurationProcedure.returnType),
  __procedureSchema("get_moderation_history", GetModerationHistoryProcedure.params, GetModerationHistoryProcedure.returnType),
  __procedureSchema("get_name_change_status", GetNameChangeStatusProcedure.params, GetNameChangeStatusProcedure.returnType),
  __procedureSchema("get_patreon_status", GetPatreonStatusProcedure.params, GetPatreonStatusProcedure.returnType),
  __procedureSchema("get_social_chat_history", GetSocialChatHistoryProcedure.params, GetSocialChatHistoryProcedure.returnType),
  __procedureSchema("get_social_chat_history_with_reactions", GetSocialChatHistoryWithReactionsProcedure.params, GetSocialChatHistoryWithReactionsProcedure.returnType),
  __procedureSchema("get_social_hub", GetSocialHubProcedure.params, GetSocialHubProcedure.returnType),
  __procedureSchema("preview_map_balance", PreviewMapBalanceProcedure.params, PreviewMapBalanceProcedure.returnType),
  __procedureSchema("refresh_patreon_membership", RefreshPatreonMembershipProcedure.params, RefreshPatreonMembershipProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

