// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.1 (commit 8ecd3c3bac427a49a9d9b13671bf83324afa59ba).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptDuelReducer from "./accept_duel_reducer";
import BeginAccountLinkReducer from "./begin_account_link_reducer";
import BeginAdventureReducer from "./begin_adventure_reducer";
import ChangeMapReducer from "./change_map_reducer";
import ClaimGuestAccountReducer from "./claim_guest_account_reducer";
import DamageDragonReducer from "./damage_dragon_reducer";
import DamageDragonBatchReducer from "./damage_dragon_batch_reducer";
import DamageSpiderBatchReducer from "./damage_spider_batch_reducer";
import DevSetAccessAuditLabelReducer from "./dev_set_access_audit_label_reducer";
import DevUpdatePlayerSaveReducer from "./dev_update_player_save_reducer";
import EnterWorldReducer from "./enter_world_reducer";
import PulseDuelReducer from "./pulse_duel_reducer";
import RegisterProtocolReducer from "./register_protocol_reducer";
import RequestDuelReducer from "./request_duel_reducer";
import ResetPlayerProgressReducer from "./reset_player_progress_reducer";
import ResumeSessionReducer from "./resume_session_reducer";
import SavePlayerProgressReducer from "./save_player_progress_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SetProfileIconReducer from "./set_profile_icon_reducer";
import SetSpeedReducer from "./set_speed_reducer";
import SyncPositionReducer from "./sync_position_reducer";
import TakeOverSessionReducer from "./take_over_session_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChatMessageRow from "./chat_message_table";
import DevAccessAuditRow from "./dev_access_audit_table";
import DragonBossRow from "./dragon_boss_table";
import DragonResultRow from "./dragon_result_table";
import DuelRow from "./duel_table";
import DuelReplayRow from "./duel_replay_table";
import LeaderboardEntryRow from "./leaderboard_entry_table";
import PlayerRow from "./player_table";
import PlayerAccountStatusRow from "./player_account_status_table";
import PlayerLifetimeRow from "./player_lifetime_table";
import PlayerProfileRow from "./player_profile_table";
import PlayerProgressRow from "./player_progress_table";
import SpiderBossRow from "./spider_boss_table";
import SpiderResultRow from "./spider_result_table";
import WorldStatusRow from "./world_status_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  dragonBoss: __table({
    name: 'dragon_boss',
    indexes: [
      { accessor: 'id', name: 'dragon_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dragon_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DragonBossRow),
  dragonResult: __table({
    name: 'dragon_result',
    indexes: [
      { accessor: 'id', name: 'dragon_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dragon_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DragonResultRow),
  duel: __table({
    name: 'duel',
    indexes: [
      { accessor: 'byChallenger', name: 'duel_challenger_idx_btree', algorithm: 'btree', columns: [
        'challenger',
      ] },
      { accessor: 'id', name: 'duel_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byOpponent', name: 'duel_opponent_idx_btree', algorithm: 'btree', columns: [
        'opponent',
      ] },
    ],
    constraints: [
      { name: 'duel_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DuelRow),
  duelReplay: __table({
    name: 'duel_replay',
    indexes: [
      { accessor: 'id', name: 'duel_replay_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'duel_replay_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DuelReplayRow),
  leaderboardEntry: __table({
    name: 'leaderboard_entry',
    indexes: [
      { accessor: 'identity', name: 'leaderboard_entry_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'leaderboard_entry_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, LeaderboardEntryRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byMap', name: 'player_map_id_idx_btree', algorithm: 'btree', columns: [
        'mapId',
      ] },
      { accessor: 'byZone', name: 'player_zone_x_zone_y_idx_btree', algorithm: 'btree', columns: [
        'zoneX',
        'zoneY',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerAccountStatus: __table({
    name: 'player_account_status',
    indexes: [
      { accessor: 'identity', name: 'player_account_status_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_account_status_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerAccountStatusRow),
  playerLifetime: __table({
    name: 'player_lifetime',
    indexes: [
      { accessor: 'identity', name: 'player_lifetime_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_lifetime_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerLifetimeRow),
  playerProfile: __table({
    name: 'player_profile',
    indexes: [
      { accessor: 'identity', name: 'player_profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerProfileRow),
  playerProgress: __table({
    name: 'player_progress',
    indexes: [
      { accessor: 'identity', name: 'player_progress_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_progress_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerProgressRow),
  spiderBoss: __table({
    name: 'spider_boss',
    indexes: [
      { accessor: 'id', name: 'spider_boss_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spider_boss_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpiderBossRow),
  spiderResult: __table({
    name: 'spider_result',
    indexes: [
      { accessor: 'id', name: 'spider_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spider_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpiderResultRow),
  worldStatus: __table({
    name: 'world_status',
    indexes: [
      { accessor: 'id', name: 'world_status_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldStatusRow),
  devAccessAudit: __table({
    name: 'dev_access_audit',
    indexes: [
    ],
    constraints: [
    ],
  }, DevAccessAuditRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_duel", AcceptDuelReducer),
  __reducerSchema("begin_account_link", BeginAccountLinkReducer),
  __reducerSchema("begin_adventure", BeginAdventureReducer),
  __reducerSchema("change_map", ChangeMapReducer),
  __reducerSchema("claim_guest_account", ClaimGuestAccountReducer),
  __reducerSchema("damage_dragon", DamageDragonReducer),
  __reducerSchema("damage_dragon_batch", DamageDragonBatchReducer),
  __reducerSchema("damage_spider_batch", DamageSpiderBatchReducer),
  __reducerSchema("dev_set_access_audit_label", DevSetAccessAuditLabelReducer),
  __reducerSchema("dev_update_player_save", DevUpdatePlayerSaveReducer),
  __reducerSchema("enter_world", EnterWorldReducer),
  __reducerSchema("pulse_duel", PulseDuelReducer),
  __reducerSchema("register_protocol", RegisterProtocolReducer),
  __reducerSchema("request_duel", RequestDuelReducer),
  __reducerSchema("reset_player_progress", ResetPlayerProgressReducer),
  __reducerSchema("resume_session", ResumeSessionReducer),
  __reducerSchema("save_player_progress", SavePlayerProgressReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("set_profile_icon", SetProfileIconReducer),
  __reducerSchema("set_speed", SetSpeedReducer),
  __reducerSchema("sync_position", SyncPositionReducer),
  __reducerSchema("take_over_session", TakeOverSessionReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.7.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

