// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  displayName: __t.string().name("display_name"),
  damage: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  isGuest: __t.bool().name("is_guest"),
  power: __t.u32(),
  armor: __t.f32(),
  regen: __t.f32(),
  playedMicros: __t.u64().name("played_micros"),
  profileIcon: __t.u32().name("profile_icon"),
  powerLevel: __t.f64().name("power_level"),
  gender: __t.u8(),
  skinTone: __t.u32().name("skin_tone"),
  headItem: __t.string().name("head_item"),
  chestItem: __t.string().name("chest_item"),
  feetItem: __t.string().name("feet_item"),
  rightHandItem: __t.string().name("right_hand_item"),
  leftHandItem: __t.string().name("left_hand_item"),
});
