// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  strikeAtMicros: __t.array(__t.u64()).name("strike_at_micros"),
  mutedUntilMicros: __t.u64().name("muted_until_micros"),
  lastMuteAtMicros: __t.u64().name("last_mute_at_micros"),
  muteCount: __t.u32().name("mute_count"),
});
