// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  claimableDayKey: __t.string().name("claimable_day_key"),
  lastClaimedDayKey: __t.string().name("last_claimed_day_key"),
  claimCycle: __t.u64().name("claim_cycle"),
  revision: __t.u64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
