// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  itemId: __t.string().name("item_id"),
  arrowStorm: __t.f32().name("arrow_storm"),
  ricochet: __t.f32(),
  piercingShot: __t.f32().name("piercing_shot"),
  acquiredAt: __t.timestamp().name("acquired_at"),
});
