// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  awaySinceMicros: __t.u64().name("away_since_micros"),
  mapId: __t.string().name("map_id"),
  seconds: __t.u32(),
  kills: __t.u32(),
  damage: __t.f64(),
  health: __t.f64(),
  armor: __t.f64(),
  regen: __t.f64(),
  attackSpeed: __t.f64().name("attack_speed"),
  blocked: __t.bool(),
  grantedAtMicros: __t.u64().name("granted_at_micros"),
  pending: __t.bool(),
});
