// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  channel: __t.string(),
  conversation: __t.string(),
  guildId: __t.u64().name("guild_id"),
  sender: __t.identity(),
  recipient: __t.identity(),
  recipientName: __t.string().name("recipient_name"),
  senderName: __t.string().name("sender_name"),
  senderGender: __t.u8().name("sender_gender"),
  powerLevel: __t.f64().name("power_level"),
  senderIsGuest: __t.bool().name("sender_is_guest"),
  message: __t.string(),
  moderated: __t.bool(),
  sentAt: __t.timestamp().name("sent_at"),
  replySender: __t.identity().name("reply_sender"),
  replyToMessageId: __t.u64().name("reply_to_message_id"),
  replyToSenderName: __t.string().name("reply_to_sender_name"),
  replyToMessage: __t.string().name("reply_to_message"),
});
