// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  identity: __t.identity(),
  researchId: __t.string().name("research_id"),
  targetRank: __t.u32().name("target_rank"),
  remainingMicros: __t.u64().name("remaining_micros"),
  pausedAt: __t.timestamp().name("paused_at"),
});
