// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  mapId: __t.string().name("map_id"),
  zoneX: __t.i32().name("zone_x"),
  zoneY: __t.i32().name("zone_y"),
  networkId: __t.u32().name("network_id"),
  playerX: __t.f64().name("player_x"),
  playerY: __t.f64().name("player_y"),
  facing: __t.f64(),
  emittedAt: __t.timestamp().name("emitted_at"),
});
