// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  maxHp: __t.f32().name("max_hp"),
  damage: __t.f32(),
  attackRate: __t.f32().name("attack_rate"),
  projectileSpeed: __t.f32().name("projectile_speed"),
  projectileCount: __t.u32().name("projectile_count"),
  attackRange: __t.f32().name("attack_range"),
  armor: __t.f32(),
  regen: __t.f32(),
  speed: __t.f32(),
  bootsCollected: __t.bool().name("boots_collected"),
  introComplete: __t.bool().name("intro_complete"),
  inventoryJson: __t.string().name("inventory_json"),
  equippedFeet: __t.string().name("equipped_feet"),
  desertUnlocked: __t.bool().name("desert_unlocked"),
  equippedHead: __t.string().name("equipped_head"),
  equippedChest: __t.string().name("equipped_chest"),
  snowlandsUnlocked: __t.bool().name("snowlands_unlocked"),
  equippedRightHand: __t.string().name("equipped_right_hand"),
  equippedLeftHand: __t.string().name("equipped_left_hand"),
  lavaUnlocked: __t.bool().name("lava_unlocked"),
  bowCount: __t.u32().name("bow_count"),
  woodenArmorCount: __t.u32().name("wooden_armor_count"),
  cosmeticHead: __t.string().name("cosmetic_head"),
  cosmeticChest: __t.string().name("cosmetic_chest"),
  cosmeticFeet: __t.string().name("cosmetic_feet"),
  cosmeticRightHand: __t.string().name("cosmetic_right_hand"),
  cosmeticLeftHand: __t.string().name("cosmetic_left_hand"),
  speedOverride: __t.f32().name("speed_override"),
});
