// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  skinTone: __t.u8().name("skin_tone"),
  headItem: __t.string().name("head_item"),
  chestItem: __t.string().name("chest_item"),
  feetItem: __t.string().name("feet_item"),
  rightHandItem: __t.string().name("right_hand_item"),
  leftHandItem: __t.string().name("left_hand_item"),
  takenAt: __t.timestamp().name("taken_at"),
});
