// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  warcraft: __t.u32(),
  foraging: __t.u32(),
  frontierMastery: __t.u32().name("frontier_mastery"),
  vitality: __t.u32(),
  precision: __t.u32(),
  criticalChance: __t.u32().name("critical_chance"),
  moveSpeed: __t.u32().name("move_speed"),
  prosperity: __t.u32(),
  criticalDamage: __t.u32().name("critical_damage"),
  regeneration: __t.u32(),
  researchSpeed: __t.u32().name("research_speed"),
  slotUpgradeSpeed: __t.u32().name("slot_upgrade_speed"),
  enemyRespawn: __t.u32().name("enemy_respawn"),
  bossRespawn: __t.u32().name("boss_respawn"),
  offlineWindow: __t.u32().name("offline_window"),
  utilityMoveSpeed: __t.u32().name("utility_move_speed"),
});
