// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  networkId: __t.u32().primaryKey().name("network_id"),
  identity: __t.identity(),
  mapId: __t.string().name("map_id"),
  isVisible: __t.bool().name("is_visible"),
  zoneX: __t.i32().name("zone_x"),
  zoneY: __t.i32().name("zone_y"),
  displayName: __t.string().name("display_name"),
  profileIcon: __t.u32().name("profile_icon"),
  playerSprite: __t.u32().name("player_sprite"),
  skinTone: __t.u32().name("skin_tone"),
  isGuest: __t.bool().name("is_guest"),
  gender: __t.u8(),
  speed: __t.f32(),
  powerLevel: __t.f64().name("power_level"),
  feetItem: __t.string().name("feet_item"),
  headItem: __t.string().name("head_item"),
  chestItem: __t.string().name("chest_item"),
  rightHandItem: __t.string().name("right_hand_item"),
  leftHandItem: __t.string().name("left_hand_item"),
});
