// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  bossSlayer: __t.u32().name("boss_slayer"),
  secondWind: __t.u32().name("second_wind"),
  longShot: __t.u32().name("long_shot"),
  fleetFoot: __t.u32().name("fleet_foot"),
  quickDraw: __t.u32().name("quick_draw"),
});
