// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
  hp: __t.f32(),
  maxHp: __t.f32().name("max_hp"),
  speed: __t.f32(),
  moving: __t.bool(),
  lastInputAt: __t.timestamp().name("last_input_at"),
  lastInputSequence: __t.u32().name("last_input_sequence"),
  power: __t.u32(),
  protocolVersion: __t.u32().name("protocol_version"),
});
