// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountLink = __t.object("AccountLink", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type AccountLink = __Infer<typeof AccountLink>;

export const ActiveItemUpgrade = __t.object("ActiveItemUpgrade", {
  identity: __t.identity(),
  itemId: __t.string(),
  currentLevel: __t.u8(),
  targetLevel: __t.u8(),
  startedAt: __t.timestamp(),
  completesAt: __t.timestamp(),
  paused: __t.bool(),
  remainingMicros: __t.u64(),
});
export type ActiveItemUpgrade = __Infer<typeof ActiveItemUpgrade>;

export const ActiveResearch = __t.object("ActiveResearch", {
  identity: __t.identity(),
  researchId: __t.string(),
  targetRank: __t.u32(),
  startedAt: __t.timestamp(),
  completesAt: __t.timestamp(),
});
export type ActiveResearch = __Infer<typeof ActiveResearch>;

export const BossAttackFrame = __t.object("BossAttackFrame", {
  mapId: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  networkId: __t.u32(),
  attackerX: __t.f64(),
  attackerY: __t.f64(),
  targetX: __t.f64(),
  targetY: __t.f64(),
  targetRadius: __t.f32(),
  hits: __t.u32(),
  emittedAt: __t.timestamp(),
});
export type BossAttackFrame = __Infer<typeof BossAttackFrame>;

export const BugReport = __t.object("BugReport", {
  id: __t.u64(),
  reporter: __t.identity(),
  reporterName: __t.string(),
  message: __t.string(),
  protocolVersion: __t.u32(),
  reportedAt: __t.timestamp(),
});
export type BugReport = __Infer<typeof BugReport>;

export const ChatCooldown = __t.object("ChatCooldown", {
  identity: __t.identity(),
  lastSentAt: __t.timestamp(),
});
export type ChatCooldown = __Infer<typeof ChatCooldown>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  message: __t.string(),
  sentAt: __t.timestamp(),
  replayId: __t.u64(),
  senderIsGuest: __t.bool(),
  powerLevel: __t.f32(),
  senderGender: __t.u8(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const DevAccessAudit = __t.object("DevAccessAudit", {});
export type DevAccessAudit = __Infer<typeof DevAccessAudit>;

export const DevBugReports = __t.object("DevBugReports", {});
export type DevBugReports = __Infer<typeof DevBugReports>;

export const DeveloperPresencePreference = __t.object("DeveloperPresencePreference", {
  identity: __t.identity(),
  visible: __t.bool(),
});
export type DeveloperPresencePreference = __Infer<typeof DeveloperPresencePreference>;

export const DragonAttackWindow = __t.object("DragonAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type DragonAttackWindow = __Infer<typeof DragonAttackWindow>;

export const DragonBoss = __t.object("DragonBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type DragonBoss = __Infer<typeof DragonBoss>;

export const DragonContribution = __t.object("DragonContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type DragonContribution = __Infer<typeof DragonContribution>;

export const DragonRespawnSchedule = __t.object("DragonRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type DragonRespawnSchedule = __Infer<typeof DragonRespawnSchedule>;

export const DragonResult = __t.object("DragonResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type DragonResult = __Infer<typeof DragonResult>;

export const Duel = __t.object("Duel", {
  id: __t.u64(),
  challenger: __t.identity(),
  opponent: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  startedAt: __t.timestamp(),
  endsAtMicros: __t.u64(),
  lastResolvedAt: __t.timestamp(),
  challengerOriginX: __t.f64(),
  challengerOriginY: __t.f64(),
  opponentOriginX: __t.f64(),
  opponentOriginY: __t.f64(),
  challengerHp: __t.f32(),
  challengerMaxHp: __t.f32(),
  challengerDamage: __t.f32(),
  challengerArmor: __t.f32(),
  challengerAttackRate: __t.f32(),
  opponentHp: __t.f32(),
  opponentMaxHp: __t.f32(),
  opponentDamage: __t.f32(),
  opponentArmor: __t.f32(),
  opponentAttackRate: __t.f32(),
  startsAtMicros: __t.u64(),
  challengerRegen: __t.f32(),
  challengerAttacks: __t.u32(),
  challengerDamageDealt: __t.f32(),
  challengerRegened: __t.f32(),
  challengerBlocked: __t.f32(),
  opponentRegen: __t.f32(),
  opponentAttacks: __t.u32(),
  opponentDamageDealt: __t.f32(),
  opponentRegened: __t.f32(),
  opponentBlocked: __t.f32(),
  challengerHeadItem: __t.string(),
  challengerChestItem: __t.string(),
  challengerFeetItem: __t.string(),
  challengerRightHandItem: __t.string(),
  challengerLeftHandItem: __t.string(),
  opponentHeadItem: __t.string(),
  opponentChestItem: __t.string(),
  opponentFeetItem: __t.string(),
  opponentRightHandItem: __t.string(),
  opponentLeftHandItem: __t.string(),
  challengerName: __t.string(),
  opponentName: __t.string(),
  challengerGender: __t.u8(),
  opponentGender: __t.u8(),
});
export type Duel = __Infer<typeof Duel>;

export const DuelReplay = __t.object("DuelReplay", {
  id: __t.u64(),
  challengerName: __t.string(),
  opponentName: __t.string(),
  winnerName: __t.string(),
  durationSeconds: __t.f32(),
  challengerMaxHp: __t.f32(),
  challengerDamage: __t.f32(),
  challengerArmor: __t.f32(),
  challengerAttackRate: __t.f32(),
  challengerRegen: __t.f32(),
  challengerFinalHp: __t.f32(),
  challengerAttacks: __t.u32(),
  challengerDamageDealt: __t.f32(),
  challengerRegened: __t.f32(),
  challengerBlocked: __t.f32(),
  opponentMaxHp: __t.f32(),
  opponentDamage: __t.f32(),
  opponentArmor: __t.f32(),
  opponentAttackRate: __t.f32(),
  opponentRegen: __t.f32(),
  opponentFinalHp: __t.f32(),
  opponentAttacks: __t.u32(),
  opponentDamageDealt: __t.f32(),
  opponentRegened: __t.f32(),
  opponentBlocked: __t.f32(),
  createdAt: __t.timestamp(),
  challengerIdentity: __t.string(),
  opponentIdentity: __t.string(),
  challengerHeadItem: __t.string(),
  challengerChestItem: __t.string(),
  challengerFeetItem: __t.string(),
  challengerRightHandItem: __t.string(),
  challengerLeftHandItem: __t.string(),
  opponentHeadItem: __t.string(),
  opponentChestItem: __t.string(),
  opponentFeetItem: __t.string(),
  opponentRightHandItem: __t.string(),
  opponentLeftHandItem: __t.string(),
  challengerGender: __t.u8(),
  opponentGender: __t.u8(),
});
export type DuelReplay = __Infer<typeof DuelReplay>;

export const DuelRequestCooldown = __t.object("DuelRequestCooldown", {
  identity: __t.identity(),
  requestedAt: __t.timestamp(),
});
export type DuelRequestCooldown = __Infer<typeof DuelRequestCooldown>;

export const DuelResolutionSchedule = __t.object("DuelResolutionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  duelId: __t.u64(),
});
export type DuelResolutionSchedule = __Infer<typeof DuelResolutionSchedule>;

export const FrostclawAttackWindow = __t.object("FrostclawAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type FrostclawAttackWindow = __Infer<typeof FrostclawAttackWindow>;

export const FrostclawBoss = __t.object("FrostclawBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type FrostclawBoss = __Infer<typeof FrostclawBoss>;

export const FrostclawContribution = __t.object("FrostclawContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type FrostclawContribution = __Infer<typeof FrostclawContribution>;

export const FrostclawRespawnSchedule = __t.object("FrostclawRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type FrostclawRespawnSchedule = __Infer<typeof FrostclawRespawnSchedule>;

export const FrostclawResult = __t.object("FrostclawResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type FrostclawResult = __Infer<typeof FrostclawResult>;

export const GemTransaction = __t.object("GemTransaction", {
  id: __t.u64(),
  identity: __t.identity(),
  delta: __t.i64(),
  balanceAfter: __t.u64(),
  kind: __t.string(),
  note: __t.string(),
  externalReference: __t.string(),
  createdAt: __t.timestamp(),
});
export type GemTransaction = __Infer<typeof GemTransaction>;

export const ItemUpgradeCompletionSchedule = __t.object("ItemUpgradeCompletionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
  itemId: __t.string(),
  targetLevel: __t.u8(),
  completesAtMicros: __t.u64(),
});
export type ItemUpgradeCompletionSchedule = __Infer<typeof ItemUpgradeCompletionSchedule>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  identity: __t.identity(),
  displayName: __t.string(),
  damage: __t.f32(),
  maxHp: __t.f32(),
  isGuest: __t.bool(),
  power: __t.u32(),
  armor: __t.f32(),
  regen: __t.f32(),
  playedMicros: __t.u64(),
  profileIcon: __t.u32(),
  powerLevel: __t.f64(),
  gender: __t.u8(),
  skinTone: __t.u32(),
  headItem: __t.string(),
  chestItem: __t.string(),
  feetItem: __t.string(),
  rightHandItem: __t.string(),
  leftHandItem: __t.string(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const LeaderboardRefreshState = __t.object("LeaderboardRefreshState", {
  id: __t.u32(),
  refreshedAtMicros: __t.u64(),
  version: __t.u32(),
});
export type LeaderboardRefreshState = __Infer<typeof LeaderboardRefreshState>;

export const LocalMovementDemand = __t.object("LocalMovementDemand", {});
export type LocalMovementDemand = __Infer<typeof LocalMovementDemand>;

export const MaintenanceSchedule = __t.object("MaintenanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSchedule = __Infer<typeof MaintenanceSchedule>;

export const MapFrameSchedule = __t.object("MapFrameSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MapFrameSchedule = __Infer<typeof MapFrameSchedule>;

export const ModuleMigrationState = __t.object("ModuleMigrationState", {
  id: __t.u32(),
  version: __t.u32(),
});
export type ModuleMigrationState = __Infer<typeof ModuleMigrationState>;

export const MotionFrameSchedule = __t.object("MotionFrameSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  previousTickMicros: __t.u64(),
});
export type MotionFrameSchedule = __Infer<typeof MotionFrameSchedule>;

export const MyGemWallet = __t.object("MyGemWallet", {});
export type MyGemWallet = __Infer<typeof MyGemWallet>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  speed: __t.f32(),
  moving: __t.bool(),
  lastInputAt: __t.timestamp(),
  lastInputSequence: __t.u32(),
  power: __t.u32(),
  protocolVersion: __t.u32(),
  feetItem: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  mapId: __t.string(),
  controllerTabId: __t.string(),
  headItem: __t.string(),
  chestItem: __t.string(),
  isVisible: __t.bool(),
  dx: __t.f32(),
  dy: __t.f32(),
  powerLevel: __t.f64(),
  rightHandItem: __t.string(),
  leftHandItem: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const PlayerAccessAudit = __t.object("PlayerAccessAudit", {
  identity: __t.identity(),
  viewer: __t.identity(),
  displayName: __t.string(),
  firstSeenAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  accountType: __t.string(),
  lastProtocolVersion: __t.u32(),
  label: __t.string(),
});
export type PlayerAccessAudit = __Infer<typeof PlayerAccessAudit>;

export const PlayerAccountStatus = __t.object("PlayerAccountStatus", {
  identity: __t.identity(),
  isGuest: __t.bool(),
});
export type PlayerAccountStatus = __Infer<typeof PlayerAccountStatus>;

export const PlayerBalanceVersion = __t.object("PlayerBalanceVersion", {
  identity: __t.identity(),
  version: __t.u32(),
});
export type PlayerBalanceVersion = __Infer<typeof PlayerBalanceVersion>;

export const PlayerController = __t.object("PlayerController", {
  identity: __t.identity(),
  connectionId: __t.connectionId(),
});
export type PlayerController = __Infer<typeof PlayerController>;

export const PlayerGemWallet = __t.object("PlayerGemWallet", {
  identity: __t.identity(),
  balance: __t.u64(),
  revision: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PlayerGemWallet = __Infer<typeof PlayerGemWallet>;

export const PlayerItemDrop = __t.object("PlayerItemDrop", {
  key: __t.string(),
  identity: __t.identity(),
  itemId: __t.string(),
  alreadyOwned: __t.bool(),
  sequence: __t.u64(),
  droppedAt: __t.timestamp(),
});
export type PlayerItemDrop = __Infer<typeof PlayerItemDrop>;

export const PlayerItemUpgrade = __t.object("PlayerItemUpgrade", {
  key: __t.string(),
  identity: __t.identity(),
  itemId: __t.string(),
  level: __t.u8(),
});
export type PlayerItemUpgrade = __Infer<typeof PlayerItemUpgrade>;

export const PlayerLastLocation = __t.object("PlayerLastLocation", {
  identity: __t.identity(),
  mapId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
});
export type PlayerLastLocation = __Infer<typeof PlayerLastLocation>;

export const PlayerLifetime = __t.object("PlayerLifetime", {
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  playedMicros: __t.u64(),
  sessionStartedAt: __t.timestamp(),
  enemyKills: __t.u64(),
  deathCount: __t.u64(),
});
export type PlayerLifetime = __Infer<typeof PlayerLifetime>;

export const PlayerMapFrame = __t.object("PlayerMapFrame", {
  mapId: __t.string(),
  emittedAt: __t.timestamp(),
  playerCount: __t.u32(),
  payload: __t.byteArray(),
});
export type PlayerMapFrame = __Infer<typeof PlayerMapFrame>;

export const PlayerMapMarker = __t.object("PlayerMapMarker", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  mapId: __t.string(),
  isVisible: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerMapMarker = __Infer<typeof PlayerMapMarker>;

export const PlayerMotion = __t.object("PlayerMotion", {
  networkId: __t.u32(),
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
  moving: __t.bool(),
  lastInputAt: __t.timestamp(),
  lastInputSequence: __t.u32(),
  inputIntervalMicros: __t.u64(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  mapId: __t.string(),
  dx: __t.f32(),
  dy: __t.f32(),
  isVisible: __t.bool(),
});
export type PlayerMotion = __Infer<typeof PlayerMotion>;

export const PlayerMotionFrame = __t.object("PlayerMotionFrame", {
  mapId: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  emittedAt: __t.timestamp(),
  playerCount: __t.u32(),
  payload: __t.byteArray(),
});
export type PlayerMotionFrame = __Infer<typeof PlayerMotionFrame>;

export const PlayerMotionIdentity = __t.object("PlayerMotionIdentity", {
  networkId: __t.u32(),
  identity: __t.identity(),
  mapId: __t.string(),
  isVisible: __t.bool(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  displayName: __t.string(),
  profileIcon: __t.u32(),
  playerSprite: __t.u32(),
  skinTone: __t.u32(),
  isGuest: __t.bool(),
  gender: __t.u8(),
});
export type PlayerMotionIdentity = __Infer<typeof PlayerMotionIdentity>;

export const PlayerMotionMapState = __t.object("PlayerMotionMapState", {
  mapId: __t.string(),
  playerCount: __t.u32(),
  visibleCount: __t.u32(),
});
export type PlayerMotionMapState = __Infer<typeof PlayerMotionMapState>;

export const PlayerMovementDemand = __t.object("PlayerMovementDemand", {
  identity: __t.identity(),
});
export type PlayerMovementDemand = __Infer<typeof PlayerMovementDemand>;

export const PlayerNameCooldown = __t.object("PlayerNameCooldown", {
  identity: __t.identity(),
  changedAt: __t.timestamp(),
});
export type PlayerNameCooldown = __Infer<typeof PlayerNameCooldown>;

export const PlayerProfile = __t.object("PlayerProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  profileIcon: __t.u32(),
  playerSprite: __t.u32(),
  skinTone: __t.u32(),
  gender: __t.u8(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const PlayerProgress = __t.object("PlayerProgress", {
  identity: __t.identity(),
  maxHp: __t.f32(),
  damage: __t.f32(),
  attackRate: __t.f32(),
  projectileSpeed: __t.f32(),
  projectileCount: __t.u32(),
  attackRange: __t.f32(),
  armor: __t.f32(),
  regen: __t.f32(),
  speed: __t.f32(),
  bootsCollected: __t.bool(),
  introComplete: __t.bool(),
  inventoryJson: __t.string(),
  equippedFeet: __t.string(),
  desertUnlocked: __t.bool(),
  equippedHead: __t.string(),
  equippedChest: __t.string(),
  snowlandsUnlocked: __t.bool(),
  equippedRightHand: __t.string(),
  equippedLeftHand: __t.string(),
  lavaUnlocked: __t.bool(),
  bowCount: __t.u32(),
  woodenArmorCount: __t.u32(),
  cosmeticHead: __t.string(),
  cosmeticChest: __t.string(),
  cosmeticFeet: __t.string(),
  cosmeticRightHand: __t.string(),
  cosmeticLeftHand: __t.string(),
  speedOverride: __t.f32(),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const PlayerResearch = __t.object("PlayerResearch", {
  identity: __t.identity(),
  warcraft: __t.u32(),
  foraging: __t.u32(),
  frontierMastery: __t.u32(),
  vitality: __t.u32(),
  precision: __t.u32(),
  criticalChance: __t.u32(),
  moveSpeed: __t.u32(),
  prosperity: __t.u32(),
  criticalDamage: __t.u32(),
  regeneration: __t.u32(),
});
export type PlayerResearch = __Infer<typeof PlayerResearch>;

export const PlayerSession = __t.object("PlayerSession", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
  protocolVersion: __t.u32(),
  lastInputSequence: __t.u32(),
  enteredWorld: __t.bool(),
  tabId: __t.string(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const ResearchCompletionSchedule = __t.object("ResearchCompletionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
  researchId: __t.string(),
  targetRank: __t.u32(),
  completesAtMicros: __t.u64(),
});
export type ResearchCompletionSchedule = __Infer<typeof ResearchCompletionSchedule>;

export const SpiderAttackWindow = __t.object("SpiderAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type SpiderAttackWindow = __Infer<typeof SpiderAttackWindow>;

export const SpiderBoss = __t.object("SpiderBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type SpiderBoss = __Infer<typeof SpiderBoss>;

export const SpiderContribution = __t.object("SpiderContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type SpiderContribution = __Infer<typeof SpiderContribution>;

export const SpiderRespawnSchedule = __t.object("SpiderRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type SpiderRespawnSchedule = __Infer<typeof SpiderRespawnSchedule>;

export const SpiderResult = __t.object("SpiderResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SpiderResult = __Infer<typeof SpiderResult>;

export const VirtualPlayer = __t.object("VirtualPlayer", {
  identity: __t.identity(),
  owner: __t.identity(),
  mapId: __t.string(),
  spawnX: __t.f64(),
  spawnY: __t.f64(),
  createdAt: __t.timestamp(),
});
export type VirtualPlayer = __Infer<typeof VirtualPlayer>;

export const VirtualPlayerLoad = __t.object("VirtualPlayerLoad", {
  owner: __t.identity(),
  activeCount: __t.u32(),
});
export type VirtualPlayerLoad = __Infer<typeof VirtualPlayerLoad>;

export const VirtualPlayerRun = __t.object("VirtualPlayerRun", {
  owner: __t.identity(),
  ticket: __t.string(),
  maxCount: __t.u32(),
  expiresAtMicros: __t.u64(),
});
export type VirtualPlayerRun = __Infer<typeof VirtualPlayerRun>;

export const WorldStatus = __t.object("WorldStatus", {
  id: __t.u32(),
  onlinePlayers: __t.u32(),
});
export type WorldStatus = __Infer<typeof WorldStatus>;

