// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountLink = __t.object("AccountLink", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type AccountLink = __Infer<typeof AccountLink>;

export const ActiveItemUpgrade = __t.object("ActiveItemUpgrade", {
  identity: __t.identity(),
  itemId: __t.string(),
  currentLevel: __t.u8(),
  targetLevel: __t.u8(),
  startedAt: __t.timestamp(),
  completesAt: __t.timestamp(),
  paused: __t.bool(),
  remainingMicros: __t.u64(),
});
export type ActiveItemUpgrade = __Infer<typeof ActiveItemUpgrade>;

export const ActiveItemUpgradeSlotTwo = __t.object("ActiveItemUpgradeSlotTwo", {
  identity: __t.identity(),
  itemId: __t.string(),
  currentLevel: __t.u8(),
  targetLevel: __t.u8(),
  startedAt: __t.timestamp(),
  completesAt: __t.timestamp(),
  paused: __t.bool(),
  remainingMicros: __t.u64(),
});
export type ActiveItemUpgradeSlotTwo = __Infer<typeof ActiveItemUpgradeSlotTwo>;

export const ActiveResearch = __t.object("ActiveResearch", {
  identity: __t.identity(),
  researchId: __t.string(),
  targetRank: __t.u32(),
  startedAt: __t.timestamp(),
  completesAt: __t.timestamp(),
});
export type ActiveResearch = __Infer<typeof ActiveResearch>;

export const BalanceApologyNotice = __t.object("BalanceApologyNotice", {
  identity: __t.identity(),
  amount: __t.u64(),
  createdAt: __t.timestamp(),
});
export type BalanceApologyNotice = __Infer<typeof BalanceApologyNotice>;

export const BossAttackFrame = __t.object("BossAttackFrame", {
  mapId: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  networkId: __t.u32(),
  attackerX: __t.f64(),
  attackerY: __t.f64(),
  targetX: __t.f64(),
  targetY: __t.f64(),
  targetRadius: __t.f32(),
  hits: __t.u32(),
  emittedAt: __t.timestamp(),
});
export type BossAttackFrame = __Infer<typeof BossAttackFrame>;

export const BugReport = __t.object("BugReport", {
  id: __t.u64(),
  reporter: __t.identity(),
  reporterName: __t.string(),
  message: __t.string(),
  protocolVersion: __t.u32(),
  reportedAt: __t.timestamp(),
});
export type BugReport = __Infer<typeof BugReport>;

export const ChatCooldown = __t.object("ChatCooldown", {
  identity: __t.identity(),
  lastSentAt: __t.timestamp(),
});
export type ChatCooldown = __Infer<typeof ChatCooldown>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  message: __t.string(),
  sentAt: __t.timestamp(),
  replayId: __t.u64(),
  senderIsGuest: __t.bool(),
  powerLevel: __t.f32(),
  senderGender: __t.u8(),
  moderated: __t.bool(),
  replyToMessageId: __t.u64(),
  replyToSenderName: __t.string(),
  replyToMessage: __t.string(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatMessageReport = __t.object("ChatMessageReport", {
  id: __t.u64(),
  reporter: __t.identity(),
  reporterName: __t.string(),
  accused: __t.identity(),
  senderName: __t.string(),
  messageId: __t.u64(),
  message: __t.string(),
  messageModerated: __t.bool(),
  sentAt: __t.timestamp(),
  reason: __t.string(),
  status: __t.string(),
  reportedAt: __t.timestamp(),
  replyToSenderName: __t.string(),
  replyToMessage: __t.string(),
});
export type ChatMessageReport = __Infer<typeof ChatMessageReport>;

export const ChatMessageReportRateLimit = __t.object("ChatMessageReportRateLimit", {
  reporter: __t.identity(),
  windowStartedAt: __t.timestamp(),
  reportCount: __t.u8(),
});
export type ChatMessageReportRateLimit = __Infer<typeof ChatMessageReportRateLimit>;

export const DailyGemBonus = __t.object("DailyGemBonus", {
  identity: __t.identity(),
  claimableDayKey: __t.string(),
  lastClaimedDayKey: __t.string(),
  claimCycle: __t.u64(),
  revision: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type DailyGemBonus = __Infer<typeof DailyGemBonus>;

export const DevAccessAudit = __t.object("DevAccessAudit", {});
export type DevAccessAudit = __Infer<typeof DevAccessAudit>;

export const DevBugReports = __t.object("DevBugReports", {});
export type DevBugReports = __Infer<typeof DevBugReports>;

export const DevForestRewardPrototype = __t.object("DevForestRewardPrototype", {});
export type DevForestRewardPrototype = __Infer<typeof DevForestRewardPrototype>;

export const DeveloperPresencePreference = __t.object("DeveloperPresencePreference", {
  identity: __t.identity(),
  visible: __t.bool(),
});
export type DeveloperPresencePreference = __Infer<typeof DeveloperPresencePreference>;

export const DragonAttackWindow = __t.object("DragonAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type DragonAttackWindow = __Infer<typeof DragonAttackWindow>;

export const DragonBoss = __t.object("DragonBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type DragonBoss = __Infer<typeof DragonBoss>;

export const DragonContribution = __t.object("DragonContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type DragonContribution = __Infer<typeof DragonContribution>;

export const DragonRespawnSchedule = __t.object("DragonRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type DragonRespawnSchedule = __Infer<typeof DragonRespawnSchedule>;

export const DragonResult = __t.object("DragonResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type DragonResult = __Infer<typeof DragonResult>;

export const Duel = __t.object("Duel", {
  id: __t.u64(),
  challenger: __t.identity(),
  opponent: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  startedAt: __t.timestamp(),
  endsAtMicros: __t.u64(),
  lastResolvedAt: __t.timestamp(),
  challengerOriginX: __t.f64(),
  challengerOriginY: __t.f64(),
  opponentOriginX: __t.f64(),
  opponentOriginY: __t.f64(),
  challengerHp: __t.f32(),
  challengerMaxHp: __t.f32(),
  challengerDamage: __t.f32(),
  challengerArmor: __t.f32(),
  challengerAttackRate: __t.f32(),
  opponentHp: __t.f32(),
  opponentMaxHp: __t.f32(),
  opponentDamage: __t.f32(),
  opponentArmor: __t.f32(),
  opponentAttackRate: __t.f32(),
  startsAtMicros: __t.u64(),
  challengerRegen: __t.f32(),
  challengerAttacks: __t.u32(),
  challengerDamageDealt: __t.f32(),
  challengerRegened: __t.f32(),
  challengerBlocked: __t.f32(),
  opponentRegen: __t.f32(),
  opponentAttacks: __t.u32(),
  opponentDamageDealt: __t.f32(),
  opponentRegened: __t.f32(),
  opponentBlocked: __t.f32(),
  challengerHeadItem: __t.string(),
  challengerChestItem: __t.string(),
  challengerFeetItem: __t.string(),
  challengerRightHandItem: __t.string(),
  challengerLeftHandItem: __t.string(),
  opponentHeadItem: __t.string(),
  opponentChestItem: __t.string(),
  opponentFeetItem: __t.string(),
  opponentRightHandItem: __t.string(),
  opponentLeftHandItem: __t.string(),
  challengerName: __t.string(),
  opponentName: __t.string(),
  challengerGender: __t.u8(),
  opponentGender: __t.u8(),
  combatVersion: __t.u8(),
});
export type Duel = __Infer<typeof Duel>;

export const DuelReplay = __t.object("DuelReplay", {
  id: __t.u64(),
  challengerName: __t.string(),
  opponentName: __t.string(),
  winnerName: __t.string(),
  durationSeconds: __t.f32(),
  challengerMaxHp: __t.f32(),
  challengerDamage: __t.f32(),
  challengerArmor: __t.f32(),
  challengerAttackRate: __t.f32(),
  challengerRegen: __t.f32(),
  challengerFinalHp: __t.f32(),
  challengerAttacks: __t.u32(),
  challengerDamageDealt: __t.f32(),
  challengerRegened: __t.f32(),
  challengerBlocked: __t.f32(),
  opponentMaxHp: __t.f32(),
  opponentDamage: __t.f32(),
  opponentArmor: __t.f32(),
  opponentAttackRate: __t.f32(),
  opponentRegen: __t.f32(),
  opponentFinalHp: __t.f32(),
  opponentAttacks: __t.u32(),
  opponentDamageDealt: __t.f32(),
  opponentRegened: __t.f32(),
  opponentBlocked: __t.f32(),
  createdAt: __t.timestamp(),
  challengerIdentity: __t.string(),
  opponentIdentity: __t.string(),
  challengerHeadItem: __t.string(),
  challengerChestItem: __t.string(),
  challengerFeetItem: __t.string(),
  challengerRightHandItem: __t.string(),
  challengerLeftHandItem: __t.string(),
  opponentHeadItem: __t.string(),
  opponentChestItem: __t.string(),
  opponentFeetItem: __t.string(),
  opponentRightHandItem: __t.string(),
  opponentLeftHandItem: __t.string(),
  challengerGender: __t.u8(),
  opponentGender: __t.u8(),
  combatVersion: __t.u8(),
});
export type DuelReplay = __Infer<typeof DuelReplay>;

export const DuelRequestCooldown = __t.object("DuelRequestCooldown", {
  identity: __t.identity(),
  requestedAt: __t.timestamp(),
});
export type DuelRequestCooldown = __Infer<typeof DuelRequestCooldown>;

export const DuelResolutionSchedule = __t.object("DuelResolutionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  duelId: __t.u64(),
});
export type DuelResolutionSchedule = __Infer<typeof DuelResolutionSchedule>;

export const ForestRewardPrototype = __t.object("ForestRewardPrototype", {
  identity: __t.identity(),
  encounter: __t.u64(),
  enemyHp: __t.u32(),
  damage: __t.u32(),
  kills: __t.u64(),
  lastAttack: __t.u64(),
  nextAttackAt: __t.u64(),
  respawnAt: __t.u64(),
});
export type ForestRewardPrototype = __Infer<typeof ForestRewardPrototype>;

export const FrostclawAttackWindow = __t.object("FrostclawAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type FrostclawAttackWindow = __Infer<typeof FrostclawAttackWindow>;

export const FrostclawBoss = __t.object("FrostclawBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type FrostclawBoss = __Infer<typeof FrostclawBoss>;

export const FrostclawContribution = __t.object("FrostclawContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type FrostclawContribution = __Infer<typeof FrostclawContribution>;

export const FrostclawRespawnSchedule = __t.object("FrostclawRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type FrostclawRespawnSchedule = __Infer<typeof FrostclawRespawnSchedule>;

export const FrostclawResult = __t.object("FrostclawResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type FrostclawResult = __Infer<typeof FrostclawResult>;

export const GemTransaction = __t.object("GemTransaction", {
  id: __t.u64(),
  identity: __t.identity(),
  delta: __t.i64(),
  balanceAfter: __t.u64(),
  kind: __t.string(),
  note: __t.string(),
  externalReference: __t.string(),
  createdAt: __t.timestamp(),
});
export type GemTransaction = __Infer<typeof GemTransaction>;

export const GloomrootAttackWindow = __t.object("GloomrootAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type GloomrootAttackWindow = __Infer<typeof GloomrootAttackWindow>;

export const GloomrootBoss = __t.object("GloomrootBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type GloomrootBoss = __Infer<typeof GloomrootBoss>;

export const GloomrootContribution = __t.object("GloomrootContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type GloomrootContribution = __Infer<typeof GloomrootContribution>;

export const GloomrootRespawnSchedule = __t.object("GloomrootRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type GloomrootRespawnSchedule = __Infer<typeof GloomrootRespawnSchedule>;

export const GloomrootResult = __t.object("GloomrootResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type GloomrootResult = __Infer<typeof GloomrootResult>;

export const ItemUpgradeCompletionSchedule = __t.object("ItemUpgradeCompletionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
  itemId: __t.string(),
  targetLevel: __t.u8(),
  completesAtMicros: __t.u64(),
  slot: __t.u8(),
});
export type ItemUpgradeCompletionSchedule = __Infer<typeof ItemUpgradeCompletionSchedule>;

export const KoiShogunAttackWindow = __t.object("KoiShogunAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type KoiShogunAttackWindow = __Infer<typeof KoiShogunAttackWindow>;

export const KoiShogunBoss = __t.object("KoiShogunBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type KoiShogunBoss = __Infer<typeof KoiShogunBoss>;

export const KoiShogunContribution = __t.object("KoiShogunContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type KoiShogunContribution = __Infer<typeof KoiShogunContribution>;

export const KoiShogunRespawnSchedule = __t.object("KoiShogunRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type KoiShogunRespawnSchedule = __Infer<typeof KoiShogunRespawnSchedule>;

export const KoiShogunResult = __t.object("KoiShogunResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type KoiShogunResult = __Infer<typeof KoiShogunResult>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  identity: __t.identity(),
  displayName: __t.string(),
  damage: __t.f32(),
  maxHp: __t.f32(),
  isGuest: __t.bool(),
  power: __t.u32(),
  armor: __t.f32(),
  regen: __t.f32(),
  playedMicros: __t.u64(),
  profileIcon: __t.u32(),
  powerLevel: __t.f64(),
  gender: __t.u8(),
  skinTone: __t.u32(),
  headItem: __t.string(),
  chestItem: __t.string(),
  feetItem: __t.string(),
  rightHandItem: __t.string(),
  leftHandItem: __t.string(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const LeaderboardRefreshState = __t.object("LeaderboardRefreshState", {
  id: __t.u32(),
  refreshedAtMicros: __t.u64(),
  version: __t.u32(),
});
export type LeaderboardRefreshState = __Infer<typeof LeaderboardRefreshState>;

export const LocalMovementDemand = __t.object("LocalMovementDemand", {});
export type LocalMovementDemand = __Infer<typeof LocalMovementDemand>;

export const MagmaliskAttackWindow = __t.object("MagmaliskAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type MagmaliskAttackWindow = __Infer<typeof MagmaliskAttackWindow>;

export const MagmaliskBoss = __t.object("MagmaliskBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type MagmaliskBoss = __Infer<typeof MagmaliskBoss>;

export const MagmaliskContribution = __t.object("MagmaliskContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type MagmaliskContribution = __Infer<typeof MagmaliskContribution>;

export const MagmaliskRespawnSchedule = __t.object("MagmaliskRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type MagmaliskRespawnSchedule = __Infer<typeof MagmaliskRespawnSchedule>;

export const MagmaliskResult = __t.object("MagmaliskResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type MagmaliskResult = __Infer<typeof MagmaliskResult>;

export const MaintenanceSchedule = __t.object("MaintenanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSchedule = __Infer<typeof MaintenanceSchedule>;

export const MaintenanceSweepSchedule = __t.object("MaintenanceSweepSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSweepSchedule = __Infer<typeof MaintenanceSweepSchedule>;

export const MapFrameSchedule = __t.object("MapFrameSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MapFrameSchedule = __Infer<typeof MapFrameSchedule>;

export const MiremawAttackWindow = __t.object("MiremawAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type MiremawAttackWindow = __Infer<typeof MiremawAttackWindow>;

export const MiremawBoss = __t.object("MiremawBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type MiremawBoss = __Infer<typeof MiremawBoss>;

export const MiremawContribution = __t.object("MiremawContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type MiremawContribution = __Infer<typeof MiremawContribution>;

export const MiremawRespawnSchedule = __t.object("MiremawRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type MiremawRespawnSchedule = __Infer<typeof MiremawRespawnSchedule>;

export const MiremawResult = __t.object("MiremawResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type MiremawResult = __Infer<typeof MiremawResult>;

export const ModuleMigrationState = __t.object("ModuleMigrationState", {
  id: __t.u32(),
  version: __t.u32(),
});
export type ModuleMigrationState = __Infer<typeof ModuleMigrationState>;

export const MotionDetailFrameSchedule = __t.object("MotionDetailFrameSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MotionDetailFrameSchedule = __Infer<typeof MotionDetailFrameSchedule>;

export const MotionFrameSchedule = __t.object("MotionFrameSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  previousTickMicros: __t.u64(),
});
export type MotionFrameSchedule = __Infer<typeof MotionFrameSchedule>;

export const MyBalanceApologyNotice = __t.object("MyBalanceApologyNotice", {});
export type MyBalanceApologyNotice = __Infer<typeof MyBalanceApologyNotice>;

export const MyCutsceneHistory = __t.object("MyCutsceneHistory", {});
export type MyCutsceneHistory = __Infer<typeof MyCutsceneHistory>;

export const MyDailyGemBonus = __t.object("MyDailyGemBonus", {});
export type MyDailyGemBonus = __Infer<typeof MyDailyGemBonus>;

export const MyGemWallet = __t.object("MyGemWallet", {});
export type MyGemWallet = __Infer<typeof MyGemWallet>;

export const MyInventoryCapacity = __t.object("MyInventoryCapacity", {});
export type MyInventoryCapacity = __Infer<typeof MyInventoryCapacity>;

export const MyPlayerBlocks = __t.object("MyPlayerBlocks", {});
export type MyPlayerBlocks = __Infer<typeof MyPlayerBlocks>;

export const MyUpgradeBench = __t.object("MyUpgradeBench", {});
export type MyUpgradeBench = __Infer<typeof MyUpgradeBench>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  speed: __t.f32(),
  moving: __t.bool(),
  lastInputAt: __t.timestamp(),
  lastInputSequence: __t.u32(),
  power: __t.u32(),
  protocolVersion: __t.u32(),
  feetItem: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  mapId: __t.string(),
  controllerTabId: __t.string(),
  headItem: __t.string(),
  chestItem: __t.string(),
  isVisible: __t.bool(),
  dx: __t.f32(),
  dy: __t.f32(),
  powerLevel: __t.f64(),
  rightHandItem: __t.string(),
  leftHandItem: __t.string(),
  vx: __t.f32(),
  vy: __t.f32(),
  simulationTick: __t.u32(),
  motionEpoch: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerAccessAudit = __t.object("PlayerAccessAudit", {
  identity: __t.identity(),
  viewer: __t.identity(),
  displayName: __t.string(),
  firstSeenAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  accountType: __t.string(),
  lastProtocolVersion: __t.u32(),
  label: __t.string(),
});
export type PlayerAccessAudit = __Infer<typeof PlayerAccessAudit>;

export const PlayerAccountStatus = __t.object("PlayerAccountStatus", {
  identity: __t.identity(),
  isGuest: __t.bool(),
});
export type PlayerAccountStatus = __Infer<typeof PlayerAccountStatus>;

export const PlayerBalanceVersion = __t.object("PlayerBalanceVersion", {
  identity: __t.identity(),
  version: __t.u32(),
});
export type PlayerBalanceVersion = __Infer<typeof PlayerBalanceVersion>;

export const PlayerBlock = __t.object("PlayerBlock", {
  key: __t.string(),
  owner: __t.identity(),
  target: __t.identity(),
  targetName: __t.string(),
});
export type PlayerBlock = __Infer<typeof PlayerBlock>;

export const PlayerController = __t.object("PlayerController", {
  identity: __t.identity(),
  connectionId: __t.connectionId(),
});
export type PlayerController = __Infer<typeof PlayerController>;

export const PlayerCutsceneHistory = __t.object("PlayerCutsceneHistory", {
  identity: __t.identity(),
  seenMask: __t.u32(),
  generation: __t.u32(),
});
export type PlayerCutsceneHistory = __Infer<typeof PlayerCutsceneHistory>;

export const PlayerDeathFrame = __t.object("PlayerDeathFrame", {
  mapId: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  networkId: __t.u32(),
  playerX: __t.f64(),
  playerY: __t.f64(),
  facing: __t.f64(),
  emittedAt: __t.timestamp(),
});
export type PlayerDeathFrame = __Infer<typeof PlayerDeathFrame>;

export const PlayerGemWallet = __t.object("PlayerGemWallet", {
  identity: __t.identity(),
  balance: __t.u64(),
  revision: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PlayerGemWallet = __Infer<typeof PlayerGemWallet>;

export const PlayerInventoryCapacity = __t.object("PlayerInventoryCapacity", {
  identity: __t.identity(),
  slotsUnlocked: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type PlayerInventoryCapacity = __Infer<typeof PlayerInventoryCapacity>;

export const PlayerItemDrop = __t.object("PlayerItemDrop", {
  key: __t.string(),
  identity: __t.identity(),
  itemId: __t.string(),
  alreadyOwned: __t.bool(),
  sequence: __t.u64(),
  droppedAt: __t.timestamp(),
});
export type PlayerItemDrop = __Infer<typeof PlayerItemDrop>;

export const PlayerItemUpgrade = __t.object("PlayerItemUpgrade", {
  key: __t.string(),
  identity: __t.identity(),
  itemId: __t.string(),
  level: __t.u8(),
});
export type PlayerItemUpgrade = __Infer<typeof PlayerItemUpgrade>;

export const PlayerLastLocation = __t.object("PlayerLastLocation", {
  identity: __t.identity(),
  mapId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
});
export type PlayerLastLocation = __Infer<typeof PlayerLastLocation>;

export const PlayerLegalConsent = __t.object("PlayerLegalConsent", {
  identity: __t.identity(),
  termsVersion: __t.string(),
  ageBand: __t.u8(),
  acceptedAt: __t.timestamp(),
});
export type PlayerLegalConsent = __Infer<typeof PlayerLegalConsent>;

export const PlayerLifetime = __t.object("PlayerLifetime", {
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  playedMicros: __t.u64(),
  sessionStartedAt: __t.timestamp(),
  enemyKills: __t.u64(),
  deathCount: __t.u64(),
});
export type PlayerLifetime = __Infer<typeof PlayerLifetime>;

export const PlayerMapFrame = __t.object("PlayerMapFrame", {
  mapId: __t.string(),
  emittedAt: __t.timestamp(),
  playerCount: __t.u32(),
  payload: __t.byteArray(),
});
export type PlayerMapFrame = __Infer<typeof PlayerMapFrame>;

export const PlayerMapMarker = __t.object("PlayerMapMarker", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  mapId: __t.string(),
  isVisible: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerMapMarker = __Infer<typeof PlayerMapMarker>;

export const PlayerMotion = __t.object("PlayerMotion", {
  networkId: __t.u32(),
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
  moving: __t.bool(),
  lastInputAt: __t.timestamp(),
  lastInputSequence: __t.u32(),
  inputIntervalMicros: __t.u64(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  mapId: __t.string(),
  dx: __t.f32(),
  dy: __t.f32(),
  isVisible: __t.bool(),
  vx: __t.f32(),
  vy: __t.f32(),
  simulationTick: __t.u32(),
  motionEpoch: __t.u32(),
});
export type PlayerMotion = __Infer<typeof PlayerMotion>;

export const PlayerMotionDetailFrame = __t.object("PlayerMotionDetailFrame", {
  recipient: __t.identity(),
  emittedAt: __t.timestamp(),
  playerCount: __t.u32(),
  payload: __t.byteArray(),
});
export type PlayerMotionDetailFrame = __Infer<typeof PlayerMotionDetailFrame>;

export const PlayerMotionFrame = __t.object("PlayerMotionFrame", {
  mapId: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  emittedAt: __t.timestamp(),
  playerCount: __t.u32(),
  payload: __t.byteArray(),
});
export type PlayerMotionFrame = __Infer<typeof PlayerMotionFrame>;

export const PlayerMotionIdentity = __t.object("PlayerMotionIdentity", {
  networkId: __t.u32(),
  identity: __t.identity(),
  mapId: __t.string(),
  isVisible: __t.bool(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  displayName: __t.string(),
  profileIcon: __t.u32(),
  playerSprite: __t.u32(),
  skinTone: __t.u32(),
  isGuest: __t.bool(),
  gender: __t.u8(),
  speed: __t.f32(),
  powerLevel: __t.f64(),
  feetItem: __t.string(),
  headItem: __t.string(),
  chestItem: __t.string(),
  rightHandItem: __t.string(),
  leftHandItem: __t.string(),
});
export type PlayerMotionIdentity = __Infer<typeof PlayerMotionIdentity>;

export const PlayerMotionInterest = __t.object("PlayerMotionInterest", {
  identity: __t.identity(),
  networkIds: __t.array(__t.u32()),
});
export type PlayerMotionInterest = __Infer<typeof PlayerMotionInterest>;

export const PlayerMotionMapState = __t.object("PlayerMotionMapState", {
  mapId: __t.string(),
  playerCount: __t.u32(),
  visibleCount: __t.u32(),
});
export type PlayerMotionMapState = __Infer<typeof PlayerMotionMapState>;

export const PlayerMovementDemand = __t.object("PlayerMovementDemand", {
  identity: __t.identity(),
});
export type PlayerMovementDemand = __Infer<typeof PlayerMovementDemand>;

export const PlayerNameCooldown = __t.object("PlayerNameCooldown", {
  identity: __t.identity(),
  changedAt: __t.timestamp(),
});
export type PlayerNameCooldown = __Infer<typeof PlayerNameCooldown>;

export const PlayerProfile = __t.object("PlayerProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  profileIcon: __t.u32(),
  playerSprite: __t.u32(),
  skinTone: __t.u32(),
  gender: __t.u8(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const PlayerProgress = __t.object("PlayerProgress", {
  identity: __t.identity(),
  maxHp: __t.f32(),
  damage: __t.f32(),
  attackRate: __t.f32(),
  projectileSpeed: __t.f32(),
  projectileCount: __t.u32(),
  attackRange: __t.f32(),
  armor: __t.f32(),
  regen: __t.f32(),
  speed: __t.f32(),
  bootsCollected: __t.bool(),
  introComplete: __t.bool(),
  inventoryJson: __t.string(),
  equippedFeet: __t.string(),
  desertUnlocked: __t.bool(),
  equippedHead: __t.string(),
  equippedChest: __t.string(),
  snowlandsUnlocked: __t.bool(),
  equippedRightHand: __t.string(),
  equippedLeftHand: __t.string(),
  lavaUnlocked: __t.bool(),
  bowCount: __t.u32(),
  woodenArmorCount: __t.u32(),
  cosmeticHead: __t.string(),
  cosmeticChest: __t.string(),
  cosmeticFeet: __t.string(),
  cosmeticRightHand: __t.string(),
  cosmeticLeftHand: __t.string(),
  speedOverride: __t.f32(),
  infernalUnlocked: __t.bool(),
  waterUnlocked: __t.bool(),
  samuraiUnlocked: __t.bool(),
  cloudspireUnlocked: __t.bool(),
  moonfenUnlocked: __t.bool(),
  crystalHollowsUnlocked: __t.bool(),
  bossRewardClaims: __t.u32(),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const PlayerReport = __t.object("PlayerReport", {
  id: __t.u64(),
  reporter: __t.identity(),
  reporterName: __t.string(),
  target: __t.identity(),
  targetName: __t.string(),
  reason: __t.string(),
  note: __t.string(),
  status: __t.string(),
  reportedAt: __t.timestamp(),
});
export type PlayerReport = __Infer<typeof PlayerReport>;

export const PlayerResearch = __t.object("PlayerResearch", {
  identity: __t.identity(),
  warcraft: __t.u32(),
  foraging: __t.u32(),
  frontierMastery: __t.u32(),
  vitality: __t.u32(),
  precision: __t.u32(),
  criticalChance: __t.u32(),
  moveSpeed: __t.u32(),
  prosperity: __t.u32(),
  criticalDamage: __t.u32(),
  regeneration: __t.u32(),
});
export type PlayerResearch = __Infer<typeof PlayerResearch>;

export const PlayerSession = __t.object("PlayerSession", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
  protocolVersion: __t.u32(),
  lastInputSequence: __t.u32(),
  enteredWorld: __t.bool(),
  tabId: __t.string(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const PlayerUpgradeBench = __t.object("PlayerUpgradeBench", {
  identity: __t.identity(),
  secondSlotUnlocked: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerUpgradeBench = __Infer<typeof PlayerUpgradeBench>;

export const PresenceChatCooldown = __t.object("PresenceChatCooldown", {
  identity: __t.identity(),
  lastLoginAtMicros: __t.u64(),
  lastLeaveAtMicros: __t.u64(),
});
export type PresenceChatCooldown = __Infer<typeof PresenceChatCooldown>;

export const PrismshellAttackWindow = __t.object("PrismshellAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type PrismshellAttackWindow = __Infer<typeof PrismshellAttackWindow>;

export const PrismshellBoss = __t.object("PrismshellBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type PrismshellBoss = __Infer<typeof PrismshellBoss>;

export const PrismshellContribution = __t.object("PrismshellContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type PrismshellContribution = __Infer<typeof PrismshellContribution>;

export const PrismshellRespawnSchedule = __t.object("PrismshellRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type PrismshellRespawnSchedule = __Infer<typeof PrismshellRespawnSchedule>;

export const PrismshellResult = __t.object("PrismshellResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type PrismshellResult = __Infer<typeof PrismshellResult>;

export const ResearchCompletionSchedule = __t.object("ResearchCompletionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
  researchId: __t.string(),
  targetRank: __t.u32(),
  completesAtMicros: __t.u64(),
});
export type ResearchCompletionSchedule = __Infer<typeof ResearchCompletionSchedule>;

export const SpiderAttackWindow = __t.object("SpiderAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type SpiderAttackWindow = __Infer<typeof SpiderAttackWindow>;

export const SpiderBoss = __t.object("SpiderBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type SpiderBoss = __Infer<typeof SpiderBoss>;

export const SpiderContribution = __t.object("SpiderContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type SpiderContribution = __Infer<typeof SpiderContribution>;

export const SpiderRespawnSchedule = __t.object("SpiderRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type SpiderRespawnSchedule = __Infer<typeof SpiderRespawnSchedule>;

export const SpiderResult = __t.object("SpiderResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SpiderResult = __Infer<typeof SpiderResult>;

export const StartupTelemetryEvent = __t.object("StartupTelemetryEvent", {
  id: __t.u64(),
  stage: __t.string(),
  outcome: __t.string(),
  issueCode: __t.string(),
  durationMs: __t.u32(),
  attempt: __t.u16(),
  clientVersion: __t.string(),
  protocolVersion: __t.u32(),
  connectivity: __t.string(),
  recordedAt: __t.timestamp(),
});
export type StartupTelemetryEvent = __Infer<typeof StartupTelemetryEvent>;

export const StartupTelemetryRateLimit = __t.object("StartupTelemetryRateLimit", {
  sender: __t.identity(),
  windowStartedAt: __t.timestamp(),
  sampleCount: __t.u8(),
});
export type StartupTelemetryRateLimit = __Infer<typeof StartupTelemetryRateLimit>;

export const StartupTelemetrySample = __t.object("StartupTelemetrySample", {
  stage: __t.string(),
  outcome: __t.string(),
  issueCode: __t.string(),
  durationMs: __t.u32(),
  attempt: __t.u16(),
  clientVersion: __t.string(),
  connectivity: __t.string(),
});
export type StartupTelemetrySample = __Infer<typeof StartupTelemetrySample>;

export const TempestKirinAttackWindow = __t.object("TempestKirinAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type TempestKirinAttackWindow = __Infer<typeof TempestKirinAttackWindow>;

export const TempestKirinBoss = __t.object("TempestKirinBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type TempestKirinBoss = __Infer<typeof TempestKirinBoss>;

export const TempestKirinContribution = __t.object("TempestKirinContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type TempestKirinContribution = __Infer<typeof TempestKirinContribution>;

export const TempestKirinRespawnSchedule = __t.object("TempestKirinRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type TempestKirinRespawnSchedule = __Infer<typeof TempestKirinRespawnSchedule>;

export const TempestKirinResult = __t.object("TempestKirinResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type TempestKirinResult = __Infer<typeof TempestKirinResult>;

export const TidewyrmAttackWindow = __t.object("TidewyrmAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type TidewyrmAttackWindow = __Infer<typeof TidewyrmAttackWindow>;

export const TidewyrmBoss = __t.object("TidewyrmBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type TidewyrmBoss = __Infer<typeof TidewyrmBoss>;

export const TidewyrmContribution = __t.object("TidewyrmContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type TidewyrmContribution = __Infer<typeof TidewyrmContribution>;

export const TidewyrmRespawnSchedule = __t.object("TidewyrmRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type TidewyrmRespawnSchedule = __Infer<typeof TidewyrmRespawnSchedule>;

export const TidewyrmResult = __t.object("TidewyrmResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type TidewyrmResult = __Infer<typeof TidewyrmResult>;

export const VirtualPlayer = __t.object("VirtualPlayer", {
  identity: __t.identity(),
  owner: __t.identity(),
  mapId: __t.string(),
  spawnX: __t.f64(),
  spawnY: __t.f64(),
  createdAt: __t.timestamp(),
});
export type VirtualPlayer = __Infer<typeof VirtualPlayer>;

export const VirtualPlayerLoad = __t.object("VirtualPlayerLoad", {
  owner: __t.identity(),
  activeCount: __t.u32(),
});
export type VirtualPlayerLoad = __Infer<typeof VirtualPlayerLoad>;

export const VirtualPlayerRun = __t.object("VirtualPlayerRun", {
  owner: __t.identity(),
  ticket: __t.string(),
  maxCount: __t.u32(),
  expiresAtMicros: __t.u64(),
});
export type VirtualPlayerRun = __Infer<typeof VirtualPlayerRun>;

export const WorldStatus = __t.object("WorldStatus", {
  id: __t.u32(),
  onlinePlayers: __t.u32(),
});
export type WorldStatus = __Infer<typeof WorldStatus>;

