// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountLink = __t.object("AccountLink", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type AccountLink = __Infer<typeof AccountLink>;

export const BugReport = __t.object("BugReport", {
  id: __t.u64(),
  reporter: __t.identity(),
  reporterName: __t.string(),
  message: __t.string(),
  protocolVersion: __t.u32(),
  reportedAt: __t.timestamp(),
});
export type BugReport = __Infer<typeof BugReport>;

export const ChatCooldown = __t.object("ChatCooldown", {
  identity: __t.identity(),
  lastSentAt: __t.timestamp(),
});
export type ChatCooldown = __Infer<typeof ChatCooldown>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  message: __t.string(),
  sentAt: __t.timestamp(),
  replayId: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const DevAccessAudit = __t.object("DevAccessAudit", {});
export type DevAccessAudit = __Infer<typeof DevAccessAudit>;

export const DevBugReports = __t.object("DevBugReports", {});
export type DevBugReports = __Infer<typeof DevBugReports>;

export const DragonAttackWindow = __t.object("DragonAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type DragonAttackWindow = __Infer<typeof DragonAttackWindow>;

export const DragonBoss = __t.object("DragonBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type DragonBoss = __Infer<typeof DragonBoss>;

export const DragonContribution = __t.object("DragonContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type DragonContribution = __Infer<typeof DragonContribution>;

export const DragonRespawnSchedule = __t.object("DragonRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type DragonRespawnSchedule = __Infer<typeof DragonRespawnSchedule>;

export const DragonResult = __t.object("DragonResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type DragonResult = __Infer<typeof DragonResult>;

export const Duel = __t.object("Duel", {
  id: __t.u64(),
  challenger: __t.identity(),
  opponent: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  startedAt: __t.timestamp(),
  endsAtMicros: __t.u64(),
  lastResolvedAt: __t.timestamp(),
  challengerOriginX: __t.f64(),
  challengerOriginY: __t.f64(),
  opponentOriginX: __t.f64(),
  opponentOriginY: __t.f64(),
  challengerHp: __t.f32(),
  challengerMaxHp: __t.f32(),
  challengerDamage: __t.f32(),
  challengerArmor: __t.f32(),
  challengerAttackRate: __t.f32(),
  opponentHp: __t.f32(),
  opponentMaxHp: __t.f32(),
  opponentDamage: __t.f32(),
  opponentArmor: __t.f32(),
  opponentAttackRate: __t.f32(),
  startsAtMicros: __t.u64(),
  challengerRegen: __t.f32(),
  challengerAttacks: __t.u32(),
  challengerDamageDealt: __t.f32(),
  challengerRegened: __t.f32(),
  challengerBlocked: __t.f32(),
  opponentRegen: __t.f32(),
  opponentAttacks: __t.u32(),
  opponentDamageDealt: __t.f32(),
  opponentRegened: __t.f32(),
  opponentBlocked: __t.f32(),
});
export type Duel = __Infer<typeof Duel>;

export const DuelReplay = __t.object("DuelReplay", {
  id: __t.u64(),
  challengerName: __t.string(),
  opponentName: __t.string(),
  winnerName: __t.string(),
  durationSeconds: __t.f32(),
  challengerMaxHp: __t.f32(),
  challengerDamage: __t.f32(),
  challengerArmor: __t.f32(),
  challengerAttackRate: __t.f32(),
  challengerRegen: __t.f32(),
  challengerFinalHp: __t.f32(),
  challengerAttacks: __t.u32(),
  challengerDamageDealt: __t.f32(),
  challengerRegened: __t.f32(),
  challengerBlocked: __t.f32(),
  opponentMaxHp: __t.f32(),
  opponentDamage: __t.f32(),
  opponentArmor: __t.f32(),
  opponentAttackRate: __t.f32(),
  opponentRegen: __t.f32(),
  opponentFinalHp: __t.f32(),
  opponentAttacks: __t.u32(),
  opponentDamageDealt: __t.f32(),
  opponentRegened: __t.f32(),
  opponentBlocked: __t.f32(),
  createdAt: __t.timestamp(),
  challengerIdentity: __t.string(),
  opponentIdentity: __t.string(),
});
export type DuelReplay = __Infer<typeof DuelReplay>;

export const DuelRequestCooldown = __t.object("DuelRequestCooldown", {
  identity: __t.identity(),
  requestedAt: __t.timestamp(),
});
export type DuelRequestCooldown = __Infer<typeof DuelRequestCooldown>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  identity: __t.identity(),
  displayName: __t.string(),
  damage: __t.f32(),
  maxHp: __t.f32(),
  isGuest: __t.bool(),
  power: __t.u32(),
  armor: __t.f32(),
  regen: __t.f32(),
  playedMicros: __t.u64(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const LeaderboardRefreshState = __t.object("LeaderboardRefreshState", {
  id: __t.u32(),
  refreshedAtMicros: __t.u64(),
  version: __t.u32(),
});
export type LeaderboardRefreshState = __Infer<typeof LeaderboardRefreshState>;

export const MaintenanceSchedule = __t.object("MaintenanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSchedule = __Infer<typeof MaintenanceSchedule>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f64(),
  y: __t.f64(),
  facing: __t.f64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  speed: __t.f32(),
  moving: __t.bool(),
  lastInputAt: __t.timestamp(),
  lastInputSequence: __t.u32(),
  power: __t.u32(),
  protocolVersion: __t.u32(),
  feetItem: __t.string(),
  zoneX: __t.i32(),
  zoneY: __t.i32(),
  mapId: __t.string(),
  controllerTabId: __t.string(),
  headItem: __t.string(),
  chestItem: __t.string(),
  isVisible: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const PlayerAccessAudit = __t.object("PlayerAccessAudit", {
  identity: __t.identity(),
  viewer: __t.identity(),
  displayName: __t.string(),
  firstSeenAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  accountType: __t.string(),
  lastProtocolVersion: __t.u32(),
  label: __t.string(),
});
export type PlayerAccessAudit = __Infer<typeof PlayerAccessAudit>;

export const PlayerAccountStatus = __t.object("PlayerAccountStatus", {
  identity: __t.identity(),
  isGuest: __t.bool(),
});
export type PlayerAccountStatus = __Infer<typeof PlayerAccountStatus>;

export const PlayerBalanceVersion = __t.object("PlayerBalanceVersion", {
  identity: __t.identity(),
  version: __t.u32(),
});
export type PlayerBalanceVersion = __Infer<typeof PlayerBalanceVersion>;

export const PlayerController = __t.object("PlayerController", {
  identity: __t.identity(),
  connectionId: __t.connectionId(),
});
export type PlayerController = __Infer<typeof PlayerController>;

export const PlayerLifetime = __t.object("PlayerLifetime", {
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  playedMicros: __t.u64(),
  sessionStartedAt: __t.timestamp(),
  enemyKills: __t.u64(),
});
export type PlayerLifetime = __Infer<typeof PlayerLifetime>;

export const PlayerNameCooldown = __t.object("PlayerNameCooldown", {
  identity: __t.identity(),
  changedAt: __t.timestamp(),
});
export type PlayerNameCooldown = __Infer<typeof PlayerNameCooldown>;

export const PlayerProfile = __t.object("PlayerProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  profileIcon: __t.u32(),
  playerSprite: __t.u32(),
  skinTone: __t.u32(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const PlayerProgress = __t.object("PlayerProgress", {
  identity: __t.identity(),
  maxHp: __t.f32(),
  damage: __t.f32(),
  attackRate: __t.f32(),
  projectileSpeed: __t.f32(),
  projectileCount: __t.u32(),
  attackRange: __t.f32(),
  armor: __t.f32(),
  regen: __t.f32(),
  speed: __t.f32(),
  bootsCollected: __t.bool(),
  introComplete: __t.bool(),
  inventoryJson: __t.string(),
  equippedFeet: __t.string(),
  desertUnlocked: __t.bool(),
  equippedHead: __t.string(),
  equippedChest: __t.string(),
  snowlandsUnlocked: __t.bool(),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const PlayerSession = __t.object("PlayerSession", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
  protocolVersion: __t.u32(),
  lastInputSequence: __t.u32(),
  enteredWorld: __t.bool(),
  tabId: __t.string(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const SpiderAttackWindow = __t.object("SpiderAttackWindow", {
  identity: __t.identity(),
  encounter: __t.u64(),
  startedAtMicros: __t.u64(),
  hits: __t.u32(),
});
export type SpiderAttackWindow = __Infer<typeof SpiderAttackWindow>;

export const SpiderBoss = __t.object("SpiderBoss", {
  id: __t.u32(),
  encounter: __t.u64(),
  hp: __t.f32(),
  maxHp: __t.f32(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
  lastDamageAtMicros: __t.u64(),
});
export type SpiderBoss = __Infer<typeof SpiderBoss>;

export const SpiderContribution = __t.object("SpiderContribution", {
  identity: __t.identity(),
  encounter: __t.u64(),
  displayName: __t.string(),
  damage: __t.f32(),
});
export type SpiderContribution = __Infer<typeof SpiderContribution>;

export const SpiderRespawnSchedule = __t.object("SpiderRespawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  encounter: __t.u64(),
});
export type SpiderRespawnSchedule = __Infer<typeof SpiderRespawnSchedule>;

export const SpiderResult = __t.object("SpiderResult", {
  id: __t.u32(),
  encounter: __t.u64(),
  totalDamage: __t.f32(),
  contributorsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SpiderResult = __Infer<typeof SpiderResult>;

export const WorldStatus = __t.object("WorldStatus", {
  id: __t.u32(),
  onlinePlayers: __t.u32(),
});
export type WorldStatus = __Infer<typeof WorldStatus>;

