import type { wildstatCoop } from "../wildstat-coop";

// This is the legacy browser API surface. Typechecking fails if a refactor
// removes, renames, or accidentally exposes a method without an intentional
// contract update.
type ExpectedApiKey =
  | "social"
  | "guild"
  | "acceptLegalTerms"
  | "acceptDuel"
  | "accessAuditEntries"
  | "accountState"
  | "acknowledgeBalanceApologyGift"
  | "activeItemUpgrade"
  | "activeItemUpgrades"
  | "activePlayerMap"
  | "activeResearch"
  | "balanceApologyGiftAmount"
  | "beginStartupTelemetryStage"
  | "beginAdventure"
  | "bossTargets"
  | "bugReportEntries"
  | "cancelItemUpgrade"
  | "changeMap"
  | "chatMessages"
  | "chatRevision"
  | "claimDailyGemBonus"
  | "connect"
  | "connectionDiagnostics"
  | "continueAsGuest"
  | "correctMovementPosition"
  | "dailyGemBonusClaimable"
  | "damageDragon"
  | "damageFrostclaw"
  | "damageGloomroot"
  | "damageMagmalisk"
  | "damageSpider"
  | "damageTidewyrm"
  | "damageKoiShogun"
  | "damageTempestKirin"
  | "damageMiremaw" | "damagePrismshell" | "damageIronhorn" | "damageDreadreaper" | "damageVoltwarden" | "damageGravebloom"
  | "databaseName"
  | "deleteBugReport"
  | "devAdjustGems"
  | "devForestRewardPrototype"
  | "forestRewardPrototypeState"
  | "developerPresenceVisible"
  | "drainBossHitResults"
  | "dragonBoss"
  | "dragonResult"
  | "duelCooldownRemainingMs"
  | "duelReplay"
  | "frostclawBoss"
  | "frostclawResult"
  | "gloomrootBoss"
  | "gloomrootResult"
  | "gemBalance"
  | "hasRemotePlayerInArea"
  | "host"
  | "inventorySlotsUnlocked"
  | "hasSeenPortalCutscene"
  | "markPortalCutsceneSeen"
  | "isConnected"
  | "isDeveloper"
  | "isDisplayNameTaken"
  | "isGuest"
  | "isReconnectingAfterWake"
  | "itemUpgradeLevel"
  | "itemUpgradeLevels"
  | "knownCharacter"
  | "knownCharacterGender"
  | "koiShogunBoss"
  | "koiShogunResult"
  | "tempestKirinBoss"
  | "tempestKirinResult"
  | "miremawBoss" | "prismshellBoss" | "ironhornBoss" | "dreadreaperBoss" | "voltwardenBoss" | "gravebloomBoss"
  | "miremawResult" | "prismshellResult" | "ironhornResult" | "dreadreaperResult" | "voltwardenResult" | "gravebloomResult"
  | "latencyMs"
  | "legalConsentAccepted"
  | "leaderboardEntries"
  | "loadDuelReplay"
  | "loadLeaderboardSnapshot"
  | "loadPlayerProfile"
  | "localDisplayName"
  | "localDuel"
  | "localIdentity"
  | "localProfileReady"
  | "localState"
  | "magmaliskBoss"
  | "magmaliskResult"
  | "mapPlayerMarkers"
  | "onlinePlayerCount"
  | "playerDisplayName"
  | "playerGender"
  | "playerProfile"
  | "playerSprite"
  | "prepareUpdateReload"
  | "profileIcon"
  | "pulseDuel"
  | "recordDesertEnemyDefeat"
  | "recordForestEnemyDefeat"
  | "recordLavaEnemyDefeat"
  | "recordSnowEnemyDefeat"
  | "recordPlayerDeath"
  | "regularEnemyLocalPosition"
  | "releasePlayerProfile"
  | "remotePlayerCount"
  | "remotePlayerDeath"
  | "remoteCombatStats"
  | "remotePlayers"
  | "reportChatMessage"
  | "reportPlayer"
  | "isPlayerBlocked"
  | "setPlayerBlocked"
  | "blockedPlayers"
  | "requestDuel"
  | "research"
  | "resetProgress"
  | "retryConnection"
  | "saveProgress"
  | "savedProgress"
  | "serverNowMs"
  | "secondUpgradeSlotUnlocked"
  | "sendChatMessage"
  | "sessionGeneration"
  | "setAccessAuditLabel"
  | "setDeveloperPresence"
  | "developerNameTagVisible"
  | "setDeveloperNameTag"
  | "playerNamePrefix"
  | "playerNameTagsRevision"
  | "setDisplayName"
  | "setGender"
  | "setOnChange"
  | "setOnItemDrop"
  | "setOnItemUpgrade"
  | "setPlayerSprite"
  | "setProfileIcon"
  | "setSkinTone"
  | "signIn"
  | "signOut"
  | "skinTone"
  | "speedUpItemUpgradeWithGems"
  | "speedUpResearchWithGems"
  | "spiderBoss"
  | "spiderResult"
  | "startItemUpgrade"
  | "startResearch"
  | "startVirtualPlayers"
  | "stopVirtualPlayers"
  | "subscriptionCount"
  | "syncMovementState"
  | "syncSpeed"
  | "takeOverSession"
  | "tidewyrmBoss"
  | "tidewyrmResult"
  | "unlockInventorySlot"
  | "unlockSecondUpgradeSlot"
  | "updatePlayerSave"
  | "virtualPlayerLoadTestState";

type ActualApiKey = keyof typeof wildstatCoop;
type SameKeys<Left, Right> = [Left] extends [Right]
  ? [Right] extends [Left] ? true : false
  : false;
type Assert<Condition extends true> = Condition;

export type WildstatCoopApiContract = Assert<SameKeys<ActualApiKey, ExpectedApiKey>>;
