import { requiredElement } from "../game/runtime/dom";

type SkinToneOptions = { names: readonly string[]; colors: readonly string[] };

/** All game DOM lookups. Keep DOM ids and initial profile skin controls outside composition root. */
export function createGameElements(skinTones: SkinToneOptions) {
  const profileSkinToneControl = requiredElement<HTMLDivElement>("profileSkinToneControl");
  skinTones.names.forEach((name, index) => {
    const choice = document.createElement("button");
    choice.type = "button";
    choice.className = "profile-skin-tone-choice";
    choice.dataset.skinTone = String(index);
    choice.setAttribute("aria-label", name);
    choice.title = name;
    choice.style.background = skinTones.colors[index] || "";
    profileSkinToneControl.append(choice);
  });

  return {
    canvas: requiredElement<HTMLCanvasElement>("game"), gameOverEl: requiredElement("gameOver"), deathCountdownEl: requiredElement("deathCountdown"),
    hpFill: requiredElement("hpFill"), hpText: requiredElement("hpText"), playerNameEl: requiredElement("playerName"), playerPowerEl: requiredElement("playerPower"), playerHudProfileIcon: requiredElement<HTMLButtonElement>("playerHudProfileIcon"), hudGemWallet: requiredElement("hudGemWallet"), hudGemBalance: requiredElement("hudGemBalance"), dailyGemBonusEl: requiredElement("dailyGemBonus"), dailyGemClaimBtn: requiredElement<HTMLButtonElement>("dailyGemClaimBtn"), balanceApologyGiftEl: requiredElement("balanceApologyGift"), balanceApologyGiftTitle: requiredElement("balanceApologyGiftTitle"), balanceApologyContinueBtn: requiredElement<HTMLButtonElement>("balanceApologyContinueBtn"), chatPanel: requiredElement("chatPanel"), coopStatusEl: requiredElement("coopStatus"), messageEl: requiredElement("message"), pickupLog: requiredElement("pickupLog"), itemDropReveal: requiredElement("itemDropReveal"),
    minimapButton: requiredElement<HTMLButtonElement>("minimapButton"), minimapPlayersEl: requiredElement("minimapPlayers"), minimapVersionEl: requiredElement("minimapVersion"), enemyRespawnAdBtn: requiredElement<HTMLButtonElement>("enemyRespawnAdBtn"), enemyRespawnAdStatus: requiredElement("enemyRespawnAdStatus"), enemyRespawnBoostStatus: requiredElement("enemyRespawnBoostStatus"), enemyRespawnBoostTimer: requiredElement("enemyRespawnBoostTimer"), enemyRespawnAdPrompt: requiredElement("enemyRespawnAdPrompt"), enemyRespawnAdConfirm: requiredElement<HTMLButtonElement>("enemyRespawnAdConfirm"), enemyRespawnAdCancel: requiredElement<HTMLButtonElement>("enemyRespawnAdCancel"), browserRewardedAd: requiredElement("browserRewardedAd"), browserRewardedAdTimer: requiredElement("browserRewardedAdTimer"),
    toolbar: requiredElement("toolbar"), settingsBtn: requiredElement("settingsBtn"), inventoryBtn: requiredElement("inventoryBtn"), shopBtn: requiredElement<HTMLButtonElement>("shopBtn"), settingsPanel: requiredElement("settingsPanel"), closeSettingsBtn: requiredElement("closeSettingsBtn"), inventoryPanel: requiredElement("inventoryPanel"), closeInventoryBtn: requiredElement("closeInventoryBtn"), inventoryCharacterCanvas: requiredElement<HTMLCanvasElement>("inventoryCharacterCanvas"), itemInspectionPanel: requiredElement("itemInspectionPanel"), itemInspectionTitle: requiredElement("itemInspectionTitle"), itemInspectionContent: requiredElement("itemInspectionContent"), itemInspectionBack: requiredElement<HTMLButtonElement>("itemInspectionBack"), resetProgressBtn: requiredElement("resetProgressBtn"), bootUpgradeEl: requiredElement("bootUpgrade"), bootUpgradeClose: requiredElement("bootUpgradeClose"), joystickEl: requiredElement("joystick"), stickEl: requiredElement("stick"),
    upgradeBenchPanel: requiredElement("upgradeBenchPanel"), upgradeBenchPrompt: requiredElement("upgradeBenchPrompt"), upgradeBenchSlot: requiredElement<HTMLButtonElement>("upgradeBenchSlot"), upgradeBenchSlotTwo: requiredElement<HTMLButtonElement>("upgradeBenchSlotTwo"), upgradeBenchStatGain: requiredElement("upgradeBenchStatGain"), upgradeBenchTimer: requiredElement("upgradeBenchTimer"), upgradeBenchAction: requiredElement<HTMLButtonElement>("upgradeBenchAction"), upgradeBenchSpeedUp: requiredElement<HTMLButtonElement>("upgradeBenchSpeedUp"), upgradeBenchBack: requiredElement<HTMLButtonElement>("upgradeBenchBack"), upgradeBenchPicker: requiredElement("upgradeBenchPicker"), upgradeBenchPickerItems: requiredElement("upgradeBenchPickerItems"), closeUpgradeBenchPickerBtn: requiredElement<HTMLButtonElement>("closeUpgradeBenchPickerBtn"),
    techTreeBtn: requiredElement("techTreeBtn"), techTreeNotice: requiredElement("techTreeNotice"), techTreeOverlay: requiredElement("techTreeOverlay"), closeTechTreeBtn: requiredElement("closeTechTreeBtn"), techTreeActive: requiredElement("techTreeActive"), techTreeCanvas: requiredElement<HTMLCanvasElement>("techTreeCanvas"), techTreeMap: requiredElement("techTreeMap"), techTreeDetail: requiredElement("techTreeDetail"), techTreeDetailContent: requiredElement("techTreeDetailContent"), closeTechTreeDetailBtn: requiredElement("closeTechTreeDetailBtn"),
    duelControls: requiredElement("duelControls"), duelStatusEl: requiredElement("duelStatus"), duelRequestBtn: requiredElement("duelRequestBtn"), duelAcceptBtn: requiredElement("duelAcceptBtn"), duelCountdownEl: requiredElement("duelCountdown"), duelResultEl: requiredElement("duelResult"), duelResultTitle: requiredElement("duelResultTitle"), duelResultStats: requiredElement("duelResultStats"), watchDuelReplayBtn: requiredElement("watchDuelReplayBtn"), closeDuelResultBtn: requiredElement("closeDuelResultBtn"), duelReplayEl: requiredElement("duelReplay"), duelReplayTitle: requiredElement("duelReplayTitle"), closeDuelReplayBtn: requiredElement("closeDuelReplayBtn"), sceneFadeEl: requiredElement("sceneFade"), cutsceneOverlayEl: requiredElement("cutsceneOverlay"),
    dragonWorldNoticeEl: requiredElement("dragonWorldNotice"), dragonWorldNoticeDetailEl: requiredElement("dragonWorldNoticeDetail"),
    playerProfileEl: requiredElement("playerProfile"), playerProfileNameEl: requiredElement("playerProfileName"), playerProfileGuestLabel: requiredElement("playerProfileGuestLabel"), playerProfilePresenceEl: requiredElement("playerProfilePresence"), playerProfilePowerEl: requiredElement("playerProfilePower"), playerProfileIcon: requiredElement<HTMLButtonElement>("playerProfileIcon"), editPlayerNameBtn: requiredElement<HTMLButtonElement>("editPlayerNameBtn"), profileCharacterPreviewEl: requiredElement("profileCharacterPreview"), profileCharacterCanvas: requiredElement<HTMLCanvasElement>("profileCharacterCanvas"), profileEquippedHeadSlot: requiredElement<HTMLButtonElement>("profileEquippedHeadSlot"), profileEquippedChestSlot: requiredElement<HTMLButtonElement>("profileEquippedChestSlot"), profileEquippedFeetSlot: requiredElement<HTMLButtonElement>("profileEquippedFeetSlot"), profileEquippedRightHandSlot: requiredElement<HTMLButtonElement>("profileEquippedRightHandSlot"), profileEquippedLeftHandSlot: requiredElement<HTMLButtonElement>("profileEquippedLeftHandSlot"), previousPlayerSpriteBtn: requiredElement<HTMLButtonElement>("previousPlayerSpriteBtn"), nextPlayerSpriteBtn: requiredElement<HTMLButtonElement>("nextPlayerSpriteBtn"), profileSkinToneEdit: requiredElement<HTMLButtonElement>("profileSkinToneEdit"), profileSkinToneControl, profileGenderSetting: requiredElement("profileGenderSetting"), profileGenderValue: requiredElement("profileGenderValue"), profileGenderEdit: requiredElement<HTMLButtonElement>("profileGenderEdit"), profileGenderChoices: requiredElement("profileGenderChoices"),
    playerProfileLoadingEl: requiredElement("playerProfileLoading"), profileOverviewTab: requiredElement("profileOverviewTab"), profileStatsTab: requiredElement("profileStatsTab"), profileOverviewPanel: requiredElement("profileOverviewPanel"), profileStatsPanel: requiredElement("profileStatsPanel"), profileJoinedEl: requiredElement("profileJoined"), profileTimePlayedEl: requiredElement("profileTimePlayed"), profileKillsEl: requiredElement("profileKills"), profileOnlineEl: requiredElement("profileOnline"), profileStatGrid: requiredElement("profileStatGrid"), closePlayerProfileBtn: requiredElement("closePlayerProfileBtn"), profileDuelBtn: requiredElement<HTMLButtonElement>("profileDuelBtn"), profileNameEditorEl: requiredElement("profileNameEditor"), profileNameEditorForm: requiredElement<HTMLFormElement>("profileNameEditorForm"), profileNameInput: requiredElement<HTMLInputElement>("profileNameInput"), savePlayerNameBtn: requiredElement<HTMLButtonElement>("savePlayerNameBtn"),
    leaderboardBtn: requiredElement("leaderboardBtn"), leaderboardEl: requiredElement("leaderboard"), leaderboardPowerTab: requiredElement("leaderboardPowerTab"), leaderboardDamageTab: requiredElement("leaderboardDamageTab"), leaderboardHealthTab: requiredElement("leaderboardHealthTab"), leaderboardArmorTab: requiredElement("leaderboardArmorTab"), leaderboardRegenTab: requiredElement("leaderboardRegenTab"), leaderboardTimeTab: requiredElement("leaderboardTimeTab"), leaderboardValueHeading: requiredElement("leaderboardValueHeading"), leaderboardPodiumEl: requiredElement("leaderboardPodium"), leaderboardRowsEl: requiredElement("leaderboardRows"), leaderboardLoadingEl: requiredElement("leaderboardLoading"), leaderboardEmptyEl: requiredElement("leaderboardEmpty"), closeLeaderboardBtn: requiredElement("closeLeaderboardBtn"),
    mapGuideEl: requiredElement("mapGuide"), mapGuideTitle: requiredElement("mapGuideTitle"), mapGuideCanvas: requiredElement<HTMLCanvasElement>("mapGuideCanvas"), mapGuideZoneLabels: requiredElement("mapGuideZoneLabels"), mapGuideDropItems: requiredElement("mapGuideDropItems"), mapGuideBack: requiredElement<HTMLButtonElement>("mapGuideBack"),
    triggerDragonCutsceneBtn: requiredElement("triggerDragonCutsceneBtn"), triggerSnowlandsCutsceneBtn: requiredElement("triggerSnowlandsCutsceneBtn"), triggerLavaCutsceneBtn: requiredElement("triggerLavaCutsceneBtn"), updateNoticeEl: requiredElement("updateNotice"), updateNoticeItemsEl: requiredElement("updateNoticeItems"), signinVersionButton: requiredElement<HTMLButtonElement>("signinVersion"), profileIconPickerEl: requiredElement("profileIconPicker"), profileIconChoices: requiredElement("profileIconChoices"), closeProfileIconPickerBtn: requiredElement("closeProfileIconPickerBtn"), gameUpdateGateEl: requiredElement("gameUpdateGate"), reconnectOverlayEl: requiredElement("reconnectOverlay"), reconnectDetailEl: requiredElement("reconnectDetail"), reconnectRetryBtn: requiredElement<HTMLButtonElement>("reconnectRetryBtn"),
  };
}
