import type { BalanceSettings } from '../../shared/map-balance-types';

export type LiveBalanceSnapshot = { revision: number; capturedAt: string; database: string; settings: BalanceSettings };
export const LIVE_BALANCE_FILE = 'src/balance/live-balance.ts';

/**
 * The text of src/balance/live-balance.ts for one captured revision. The values
 * come from the live database (npm run balance:sync), so no test can regenerate
 * them offline; scripts/generated-balance-files.test.ts only checks the file is
 * exactly what this function writes for its own snapshot (no hand edits).
 */
export function liveBalanceSource(snapshot: LiveBalanceSnapshot) {
  // Typed, so live's version markers (baselineVersion: 2 and the rest) read as BalanceSettings, not plain numbers.
  return `// Generated by npm run balance:sync (scripts/sync-balance-lab.ts) from ${snapshot.database} revision ${snapshot.revision}, captured ${snapshot.capturedAt}.\n// Read-only snapshot for the Balance Lab and audit scripts; the game itself reads the live revision.\nimport type { BalanceSettings } from "../../shared/map-balance-types";\n\nexport const LIVE_BALANCE: { revision: number; capturedAt: string; database: string; settings: BalanceSettings } = ${JSON.stringify(snapshot, null, 2)};\n`;
}
