// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as BeginPatreonLinkProcedure from "../begin_patreon_link_procedure";
import * as DevTeleportToPlayerProcedure from "../dev_teleport_to_player_procedure";
import * as GetAnalyticsDashboardProcedure from "../get_analytics_dashboard_procedure";
import * as GetAvatarFramesProcedure from "../get_avatar_frames_procedure";
import * as GetBalanceEditorProcedure from "../get_balance_editor_procedure";
import * as GetChatHistoryProcedure from "../get_chat_history_procedure";
import * as GetChatHistoryWithReactionsProcedure from "../get_chat_history_with_reactions_procedure";
import * as GetChatMessageReactionsProcedure from "../get_chat_message_reactions_procedure";
import * as GetDeveloperTravelTargetProcedure from "../get_developer_travel_target_procedure";
import * as GetGuildHubProcedure from "../get_guild_hub_procedure";
import * as GetGuildPreviewProcedure from "../get_guild_preview_procedure";
import * as GetGuildReplayProcedure from "../get_guild_replay_procedure";
import * as GetLeaderboardPageProcedure from "../get_leaderboard_page_procedure";
import * as GetLeaderboardWindowProcedure from "../get_leaderboard_window_procedure";
import * as GetMapBalanceProcedure from "../get_map_balance_procedure";
import * as GetMapConfigurationProcedure from "../get_map_configuration_procedure";
import * as GetModerationHistoryProcedure from "../get_moderation_history_procedure";
import * as GetNameChangeStatusProcedure from "../get_name_change_status_procedure";
import * as GetPatreonStatusProcedure from "../get_patreon_status_procedure";
import * as GetPrestigeLeaderboardPageProcedure from "../get_prestige_leaderboard_page_procedure";
import * as GetSocialChatHistoryProcedure from "../get_social_chat_history_procedure";
import * as GetSocialChatHistoryWithReactionsProcedure from "../get_social_chat_history_with_reactions_procedure";
import * as GetSocialHubProcedure from "../get_social_hub_procedure";
import * as PreviewMapBalanceProcedure from "../preview_map_balance_procedure";
import * as RefreshPatreonMembershipProcedure from "../refresh_patreon_membership_procedure";

export type BeginPatreonLinkArgs = __Infer<typeof BeginPatreonLinkProcedure.params>;
export type BeginPatreonLinkResult = __Infer<typeof BeginPatreonLinkProcedure.returnType>;
export type DevTeleportToPlayerArgs = __Infer<typeof DevTeleportToPlayerProcedure.params>;
export type DevTeleportToPlayerResult = __Infer<typeof DevTeleportToPlayerProcedure.returnType>;
export type GetAnalyticsDashboardArgs = __Infer<typeof GetAnalyticsDashboardProcedure.params>;
export type GetAnalyticsDashboardResult = __Infer<typeof GetAnalyticsDashboardProcedure.returnType>;
export type GetAvatarFramesArgs = __Infer<typeof GetAvatarFramesProcedure.params>;
export type GetAvatarFramesResult = __Infer<typeof GetAvatarFramesProcedure.returnType>;
export type GetBalanceEditorArgs = __Infer<typeof GetBalanceEditorProcedure.params>;
export type GetBalanceEditorResult = __Infer<typeof GetBalanceEditorProcedure.returnType>;
export type GetChatHistoryArgs = __Infer<typeof GetChatHistoryProcedure.params>;
export type GetChatHistoryResult = __Infer<typeof GetChatHistoryProcedure.returnType>;
export type GetChatHistoryWithReactionsArgs = __Infer<typeof GetChatHistoryWithReactionsProcedure.params>;
export type GetChatHistoryWithReactionsResult = __Infer<typeof GetChatHistoryWithReactionsProcedure.returnType>;
export type GetChatMessageReactionsArgs = __Infer<typeof GetChatMessageReactionsProcedure.params>;
export type GetChatMessageReactionsResult = __Infer<typeof GetChatMessageReactionsProcedure.returnType>;
export type GetDeveloperTravelTargetArgs = __Infer<typeof GetDeveloperTravelTargetProcedure.params>;
export type GetDeveloperTravelTargetResult = __Infer<typeof GetDeveloperTravelTargetProcedure.returnType>;
export type GetGuildHubArgs = __Infer<typeof GetGuildHubProcedure.params>;
export type GetGuildHubResult = __Infer<typeof GetGuildHubProcedure.returnType>;
export type GetGuildPreviewArgs = __Infer<typeof GetGuildPreviewProcedure.params>;
export type GetGuildPreviewResult = __Infer<typeof GetGuildPreviewProcedure.returnType>;
export type GetGuildReplayArgs = __Infer<typeof GetGuildReplayProcedure.params>;
export type GetGuildReplayResult = __Infer<typeof GetGuildReplayProcedure.returnType>;
export type GetLeaderboardPageArgs = __Infer<typeof GetLeaderboardPageProcedure.params>;
export type GetLeaderboardPageResult = __Infer<typeof GetLeaderboardPageProcedure.returnType>;
export type GetLeaderboardWindowArgs = __Infer<typeof GetLeaderboardWindowProcedure.params>;
export type GetLeaderboardWindowResult = __Infer<typeof GetLeaderboardWindowProcedure.returnType>;
export type GetMapBalanceArgs = __Infer<typeof GetMapBalanceProcedure.params>;
export type GetMapBalanceResult = __Infer<typeof GetMapBalanceProcedure.returnType>;
export type GetMapConfigurationArgs = __Infer<typeof GetMapConfigurationProcedure.params>;
export type GetMapConfigurationResult = __Infer<typeof GetMapConfigurationProcedure.returnType>;
export type GetModerationHistoryArgs = __Infer<typeof GetModerationHistoryProcedure.params>;
export type GetModerationHistoryResult = __Infer<typeof GetModerationHistoryProcedure.returnType>;
export type GetNameChangeStatusArgs = __Infer<typeof GetNameChangeStatusProcedure.params>;
export type GetNameChangeStatusResult = __Infer<typeof GetNameChangeStatusProcedure.returnType>;
export type GetPatreonStatusArgs = __Infer<typeof GetPatreonStatusProcedure.params>;
export type GetPatreonStatusResult = __Infer<typeof GetPatreonStatusProcedure.returnType>;
export type GetPrestigeLeaderboardPageArgs = __Infer<typeof GetPrestigeLeaderboardPageProcedure.params>;
export type GetPrestigeLeaderboardPageResult = __Infer<typeof GetPrestigeLeaderboardPageProcedure.returnType>;
export type GetSocialChatHistoryArgs = __Infer<typeof GetSocialChatHistoryProcedure.params>;
export type GetSocialChatHistoryResult = __Infer<typeof GetSocialChatHistoryProcedure.returnType>;
export type GetSocialChatHistoryWithReactionsArgs = __Infer<typeof GetSocialChatHistoryWithReactionsProcedure.params>;
export type GetSocialChatHistoryWithReactionsResult = __Infer<typeof GetSocialChatHistoryWithReactionsProcedure.returnType>;
export type GetSocialHubArgs = __Infer<typeof GetSocialHubProcedure.params>;
export type GetSocialHubResult = __Infer<typeof GetSocialHubProcedure.returnType>;
export type PreviewMapBalanceArgs = __Infer<typeof PreviewMapBalanceProcedure.params>;
export type PreviewMapBalanceResult = __Infer<typeof PreviewMapBalanceProcedure.returnType>;
export type RefreshPatreonMembershipArgs = __Infer<typeof RefreshPatreonMembershipProcedure.params>;
export type RefreshPatreonMembershipResult = __Infer<typeof RefreshPatreonMembershipProcedure.returnType>;

