// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptDuelReducer from "../accept_duel_reducer";
import BeginAccountLinkReducer from "../begin_account_link_reducer";
import BeginAdventureReducer from "../begin_adventure_reducer";
import ClaimGuestAccountReducer from "../claim_guest_account_reducer";
import DamageDragonReducer from "../damage_dragon_reducer";
import PulseDuelReducer from "../pulse_duel_reducer";
import RegisterProtocolReducer from "../register_protocol_reducer";
import RequestDuelReducer from "../request_duel_reducer";
import ResetPlayerProgressReducer from "../reset_player_progress_reducer";
import SavePlayerProgressReducer from "../save_player_progress_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SetSpeedReducer from "../set_speed_reducer";
import SyncPositionReducer from "../sync_position_reducer";

export type AcceptDuelParams = __Infer<typeof AcceptDuelReducer>;
export type BeginAccountLinkParams = __Infer<typeof BeginAccountLinkReducer>;
export type BeginAdventureParams = __Infer<typeof BeginAdventureReducer>;
export type ClaimGuestAccountParams = __Infer<typeof ClaimGuestAccountReducer>;
export type DamageDragonParams = __Infer<typeof DamageDragonReducer>;
export type PulseDuelParams = __Infer<typeof PulseDuelReducer>;
export type RegisterProtocolParams = __Infer<typeof RegisterProtocolReducer>;
export type RequestDuelParams = __Infer<typeof RequestDuelReducer>;
export type ResetPlayerProgressParams = __Infer<typeof ResetPlayerProgressReducer>;
export type SavePlayerProgressParams = __Infer<typeof SavePlayerProgressReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SetSpeedParams = __Infer<typeof SetSpeedReducer>;
export type SyncPositionParams = __Infer<typeof SyncPositionReducer>;

