// Deliberate capability boundary: map databases cannot accept account saves,
// inventory changes, research, admin grants, or global duel mutations.
export { default,
  configureSharding,
  coordinateMapShard,
  synchronizeMapShard,
  acknowledgeShardRewards,
  renewShardLease,
  recordPlayerDeath,
  installShardPlayer,
  revokeShardPlayer,
  acknowledgeShardReward,
  onConnect,
  onDisconnect,
  registerProtocol,
  enterRegionalWorld as enterWorld,
  updateMovementState,
  setPlayerMotionInterest,
  damageDragonFromPosition,
  damageSpiderFromPosition,
  damageFrostclawFromPosition,
  damageMagmaliskFromPosition,
  damageGloomrootFromPosition,
  damageTidewyrmFromPosition,
  damageKoiShogunFromPosition,
  damageTempestKirinFromPosition,
  damageMiremawFromPosition,
  damagePrismshellFromPosition,
  runMaintenance,
  runMaintenanceSweep,
  publishMotionFrames,
  publishMotionDetailFrames,
  publishMapFrames,
  completeResearch,
  completeItemUpgrade,
  resolveScheduledDuel,
  respawnDragon,
  respawnSpider,
  respawnFrostclaw,
  respawnMagmalisk,
  respawnGloomroot,
  respawnTidewyrm,
  respawnKoiShogun,
  respawnTempestKirin,
  respawnMiremaw,
  respawnPrismshell
} from "../../spacetimedb/src/index";
