// Generated by scripts/smooth-campaign-health.ts from revision 73.
// Fixed Forest/map 15 endpoints; each enemy role gets a log-quadratic fit
// with tapering growth. Missing/new roles keep authored HP.
export const CAMPAIGN_HEALTH_FACTORS: Readonly<Record<string, Readonly<Record<string, number>>>> = {
  "tutorial_forest": {
    "regular:damage": 1,
    "regular:health": 1,
    "regular:armor": 1,
    "elite:damage": 1,
    "elite:health": 1,
    "elite:regen": 1
  },
  "beginner_desert": {
    "regular:damage": 0.7108985274081837,
    "regular:health": 0.106597804127897,
    "regular:armor": 0.24664739117934373,
    "elite:damage": 0.4404288310065975,
    "elite:health": 0.5213117831928433,
    "elite:regen": 0.31157628595016634
  },
  "intermediate_snowlands": {
    "regular:damage": 0.521605146848932,
    "regular:health": 0.1321338273821232,
    "regular:armor": 0.2424705358353997,
    "elite:damage": 0.3688694165209081,
    "elite:health": 0.5217348277282996,
    "elite:regen": 0.28714439063176217
  },
  "advanced_lava_wastes": {
    "regular:damage": 0.2403211346297431,
    "regular:health": 0.09656177239137614,
    "regular:armor": 0.1445028963498823,
    "elite:damage": 0.19092996160559278,
    "elite:health": 0.3025210080159885,
    "elite:regen": 0.16167568221265258
  },
  "infernal_depths": {
    "regular:damage": 0.39558322230984977,
    "regular:health": 0.23670196088088863,
    "regular:armor": 0.29703609147676485,
    "elite:damage": 0.3475041585869181,
    "elite:health": 0.5782220226695531,
    "elite:regen": 0.3164298523028406
  },
  "water_reach": {
    "regular:damage": 0.6048572771471334,
    "regular:health": 0.5060311411405487,
    "regular:armor": 0.5475582529229434,
    "elite:damage": 0.5782341798349151,
    "elite:health": 0.9471972874729016,
    "elite:regen": 0.5597214154660677
  },
  "samurai_garden": {
    "regular:damage": 1.7181738318568986,
    "regular:health": 1.8869543321442277,
    "regular:armor": 1.8103805294268256,
    "elite:damage": 1.7592815211270594,
    "elite:health": 2.6596407951524395,
    "elite:regen": 1.7896088694342152
  },
  "cloudspire": {
    "regular:damage": 1.133418892861737,
    "regular:health": 1.5341375676143785,
    "regular:armor": 1.3419547061009356,
    "elite:damage": 1.2233895419702159,
    "elite:health": 1.600118925725142,
    "elite:regen": 1.2928438111041136
  },
  "moonfen": {
    "regular:damage": 1.389034199837295,
    "regular:health": 2.175584607102009,
    "regular:armor": 1.784120891709927,
    "elite:damage": 1.5555429767965365,
    "elite:health": 1.6501303841715824,
    "elite:regen": 1.688207100764665
  },
  "crystal_hollows": {
    "regular:damage": 1.581264708548595,
    "regular:health": 2.6907070159857276,
    "regular:armor": 2.1271550036750164,
    "elite:damage": 1.808244269836189,
    "elite:health": 1.4584481289171374,
    "elite:regen": 1.992356785862472
  },
  "clockwork_ruins": {
    "regular:damage": 1.6721120091840544,
    "regular:health": 2.9022552551470486,
    "regular:armor": 2.274376893137663,
    "elite:damage": 1.9217195713140818,
    "elite:health": 1.1047663598964614,
    "elite:regen": 2.1250552843565833
  },
  "duskfall_orchard": {
    "regular:damage": 1.6424618924382306,
    "regular:health": 2.730131480092184,
    "regular:armor": 2.180791616917774,
    "elite:damage": 1.8671566733669092,
    "elite:health": 0.7172269876844165,
    "elite:regen": 2.0484958165741562
  },
  "neon_bastion": {
    "regular:damage": 2.1408998237289003,
    "regular:health": 3.199721949091648,
    "regular:armor": 2.678898761733672,
    "elite:damage": 2.369361360249279,
    "elite:health": 0.5701005911353467,
    "elite:regen": 2.5495505003331593
  },
  "verdant_catacombs": {
    "regular:damage": 1.2701722464219625,
    "regular:health": 1.6025653912758144,
    "regular:armor": 1.4460488080893628,
    "elite:damage": 1.3469012458182565,
    "elite:health": 0.8155909197475424,
    "elite:regen": 1.4052382575130014
  },
  "ion_citadel": {
    "regular:damage": 1,
    "regular:health": 1,
    "regular:armor": 1,
    "elite:damage": 1,
    "elite:health": 1,
    "elite:regen": 1
  }
};
