/**
 * Endless-only enemies (0.867): the Layer Lab EnemyMonster 3 captures that no
 * campaign map uses. No camp spawns them; an Endless map may draw one as its art.
 * Endless resolves their combat values from its own lanes, so these are only the
 * shape the enemy list needs: melee, regular size, the late maps' attack speed.
 */
import type { EnemyDefinition } from "./enemy-definitions";

/** Each enemy's runtime sprite id under public/assets/wildstat/enemies/. */
export const ENDLESS_ENEMY_ART = {
  "Castle Carapace": "carapace-castle",
  "Green Carapace": "carapace-green",
  "Iron Carapace": "carapace-iron",
  "Angry Evilmass": "evilmass-angry",
  "Boxer Evilmass": "evilmass-boxer",
  "Knight Evilmass": "evilmass-knight",
  "Berry Bloom": "flower-berry",
  "Candy Bloom": "flower-candy",
  "Daisy Bloom": "flower-daisy",
  "Dandelion Bloom": "flower-dandelion",
  "Horned Fungus": "fungus-horn",
  "Demon Hornrabbit": "hornrabbit-demon",
  "Jelly Hornrabbit": "hornrabbit-jelly",
  "Bronco": "horse-bronco",
  "Nightmare": "horse-nightmare",
  "Unicorn": "horse-unicorn",
  "Green Larva": "larva-green",
  "Knight Larva": "larva-knight",
  "Leech Larva": "larva-leech",
  "Orc Berserker": "orcsmasher-berserker",
  "Red Orc Smasher": "orcsmasher-red",
  "Orc Warlord": "orcsmasher-warlord",
  "Orc Butcher": "orcsword-butcher",
  "Orc Rookie": "orcsword-rookie",
  "Orc Veteran": "orcsword-veteran",
  "Steel Pumpkin": "pumpkin-steel",
  "Swamp Raptor": "raptor-swamp",
  "Blood Reaper": "reaper-blood",
  "Huge Rhino": "rhino-huge",
  "Giant Toad": "toad-giant",
  "Horned Toad": "toad-horn",
  "Toad King": "toad-king",
  "Apple Wingdemon": "wingdemon-apple",
  "Bomb Wingdemon": "wingdemon-bomb",
  "Eye Wingdemon": "wingdemon-eye",
  "Vampire Wingdemon": "wingdemon-vampire",
  "Ice Winterling": "winter-ice",
  "Iron Winterling": "winter-iron",
  "Snow Winterling": "winter-snow",
  "Lightning Worm": "worm-lightning",
  "Poison Worm": "worm-poison",
} as const;

const endless = { attackSpeed: 0.65, speed: 305, r: 30, color: "#9aa7b5", outline: "#2a3038", hp: 1, damage: 1, reward: { type: "damage", amount: 1 } } as const satisfies EnemyDefinition;
export const ENDLESS_ENEMY_BASE_VALUES = {
  "Castle Carapace": endless,
  "Green Carapace": endless,
  "Iron Carapace": endless,
  "Angry Evilmass": endless,
  "Boxer Evilmass": endless,
  "Knight Evilmass": endless,
  "Berry Bloom": endless,
  "Candy Bloom": endless,
  "Daisy Bloom": endless,
  "Dandelion Bloom": endless,
  "Horned Fungus": endless,
  "Demon Hornrabbit": endless,
  "Jelly Hornrabbit": endless,
  "Bronco": endless,
  "Nightmare": endless,
  "Unicorn": endless,
  "Green Larva": endless,
  "Knight Larva": endless,
  "Leech Larva": endless,
  "Orc Berserker": endless,
  "Red Orc Smasher": endless,
  "Orc Warlord": endless,
  "Orc Butcher": endless,
  "Orc Rookie": endless,
  "Orc Veteran": endless,
  "Steel Pumpkin": endless,
  "Swamp Raptor": endless,
  "Blood Reaper": endless,
  "Huge Rhino": endless,
  "Giant Toad": endless,
  "Horned Toad": endless,
  "Toad King": endless,
  "Apple Wingdemon": endless,
  "Bomb Wingdemon": endless,
  "Eye Wingdemon": endless,
  "Vampire Wingdemon": endless,
  "Ice Winterling": endless,
  "Iron Winterling": endless,
  "Snow Winterling": endless,
  "Lightning Worm": endless,
  "Poison Worm": endless,
} satisfies Record<keyof typeof ENDLESS_ENEMY_ART, EnemyDefinition>;
