/**
 * Generated by the local WildStat Map Editor.
 * Do not hand-edit this file; the editor validates and replaces it atomically.
 */
export type MapEditorGameplayOverride = {
  name: string;
  arrival: { x: number; y: number };
  boss: { x: number; y: number };
  bootsPickup?: { x: number; y: number };
  upgradeBench?: { x: number; y: number };
  portals: {
    x: number;
    y: number;
    width: number;
    height: number;
    depth: number;
    destination: string;
  }[];
};

export const MAP_EDITOR_GAMEPLAY_OVERRIDES: Readonly<Record<string, MapEditorGameplayOverride>> = {
  "tutorial_forest": {
    "name": "Tutorial Forest",
    "arrival": {
      "x": 875,
      "y": 900
    },
    "boss": {
      "x": 4040,
      "y": 4240
    },
    "bootsPickup": {
      "x": 1165,
      "y": 810
    },
    "portals": [
      {
        "x": 875,
        "y": 850,
        "width": 198,
        "height": 198,
        "depth": 850,
        "destination": "beginner_desert"
      }
    ]
  },
  "beginner_desert": {
    "name": "Beginner Desert",
    "arrival": {
      "x": 625,
      "y": 800
    },
    "boss": {
      "x": 4050,
      "y": 4050
    },
    "portals": [
      {
        "x": 500,
        "y": 725,
        "width": 198,
        "height": 198,
        "depth": 725,
        "destination": "tutorial_forest"
      },
      {
        "x": 750,
        "y": 725,
        "width": 198,
        "height": 198,
        "depth": 725,
        "destination": "intermediate_snowlands"
      }
    ]
  }
};
