/**
 * Generated by the local WildStat Map Editor.
 * Do not hand-edit this file; the editor validates and replaces it atomically.
 */
export type MapEditorGameplayOverride = {
  name: string;
  arrival: { x: number; y: number };
  boss: { x: number; y: number };
  bootsPickup?: { x: number; y: number };
  upgradeBench?: { x: number; y: number };
  portals: {
    x: number;
    y: number;
    width: number;
    height: number;
    depth: number;
    destination: string;
  }[];
};

export const MAP_EDITOR_GAMEPLAY_OVERRIDES: Readonly<Record<string, MapEditorGameplayOverride>> = {
  "tutorial_forest": {
    "name": "Tutorial Forest",
    "arrival": {
      "x": 825,
      "y": 875
    },
    "boss": {
      "x": 4040,
      "y": 4240
    },
    "bootsPickup": {
      "x": 1165,
      "y": 810
    },
    "portals": [
      {
        "x": 825,
        "y": 800,
        "width": 198,
        "height": 198,
        "depth": 800,
        "destination": "beginner_desert"
      }
    ]
  }
};
