/**
 * Generated by the local WildStat Map Editor (scripts/map-editor-server.mjs,
 * npm run map:editor) from shared/map-designs.json.
 * Do not hand-edit this file; the editor validates and replaces it atomically.
 */
export type MapEditorGameplayOverride = {
  name: string;
  arrival: { x: number; y: number };
  boss: { x: number; y: number };
  bootsPickup?: { x: number; y: number };
  upgradeBench?: { x: number; y: number };
  portals: {
    x: number;
    y: number;
    width: number;
    height: number;
    depth: number;
    destination: string;
  }[];
};

export const MAP_EDITOR_GAMEPLAY_OVERRIDES: Readonly<Record<string, MapEditorGameplayOverride>> = {
  "tutorial_forest": {
    "name": "Tutorial Forest",
    "arrival": {
      "x": 2240,
      "y": 2900
    },
    "boss": {
      "x": 4040,
      "y": 4240
    },
    "bootsPickup": {
      "x": 1165,
      "y": 810
    },
    "portals": [
      {
        "x": 2240,
        "y": 2810,
        "width": 198,
        "height": 198,
        "depth": 2810,
        "destination": "beginner_desert"
      }
    ]
  },
  "beginner_desert": {
    "name": "Beginner Desert",
    "arrival": {
      "x": 2400,
      "y": 2490
    },
    "boss": {
      "x": 4050,
      "y": 4050
    },
    "portals": [
      {
        "x": 2290,
        "y": 2400,
        "width": 198,
        "height": 198,
        "depth": 2400,
        "destination": "tutorial_forest"
      },
      {
        "x": 2510,
        "y": 2400,
        "width": 198,
        "height": 198,
        "depth": 2400,
        "destination": "intermediate_snowlands"
      }
    ]
  }
};
