import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { buildCampaignHealthCurve, CAMPAIGN_HEALTH_FILE, CAMPAIGN_HEALTH_SOURCE } from "./balance/campaign-health-curve";
import { buildCampaignProgression, CAMPAIGN_PROGRESSION_FILE, CAMPAIGN_PROGRESSION_SOURCE } from "./balance/campaign-progression";
import { liveBalanceSource, LIVE_BALANCE_FILE } from "./balance/live-balance-source";
import { generatedGameplaySource } from "./map-editor-gameplay-source.mjs";
import { LIVE_BALANCE } from "../src/balance/live-balance";

// Every generated balance file is regenerated here from its committed inputs
// and compared byte for byte, so a hand edit or a stale generation fails.
// To change one, change its input (or generator) and rerun the generator named
// in the file's first line. See docs/balance-bake.md for the ownership table.
const read = (path: string) => readFileSync(path, "utf8");

describe("generated balance files match their generators", () => {
  it(`${CAMPAIGN_HEALTH_FILE} is regenerated from revision ${CAMPAIGN_HEALTH_SOURCE.revision}`, () => {
    expect(read(CAMPAIGN_HEALTH_FILE)).toBe(buildCampaignHealthCurve().source);
  });

  it(`${CAMPAIGN_PROGRESSION_FILE} is regenerated from revision ${CAMPAIGN_PROGRESSION_SOURCE.revision}`, () => {
    expect(read(CAMPAIGN_PROGRESSION_FILE)).toBe(buildCampaignProgression());
  });

  it("shared/map-editor-overrides.ts is regenerated from shared/map-designs.json", () => {
    expect(read("shared/map-editor-overrides.ts")).toBe(generatedGameplaySource(JSON.parse(read("shared/map-designs.json"))));
  });

  // Values come from the live database and cannot be refetched offline; this
  // only proves the file is untouched since balance:sync wrote it.
  it(`${LIVE_BALANCE_FILE} is exactly what balance:sync wrote for its snapshot`, () => {
    expect(read(LIVE_BALANCE_FILE)).toBe(liveBalanceSource(LIVE_BALANCE));
  });

  it("each generated file names its generator and source in its first lines", () => {
    expect(read(CAMPAIGN_HEALTH_FILE).split("\n")[0]).toMatch(/^\/\/ Generated by scripts\/smooth-campaign-health\.ts from revision \d+ \(tests\/fixtures\//);
    expect(read(CAMPAIGN_PROGRESSION_FILE).split("\n")[0]).toMatch(/^\/\/ Generated by scripts\/build-campaign-progression\.ts from revision \d+ \(tests\/fixtures\//);
    expect(read("shared/map-editor-overrides.ts").split("\n").slice(0, 4).join(" ")).toContain("from shared/map-designs.json");
    expect(read(LIVE_BALANCE_FILE).split("\n")[0]).toMatch(/^\/\/ Generated by npm run balance:sync .* revision \d+, captured /);
  });
});
