import { writeFileSync, mkdirSync } from 'node:fs';
import { CAMPAIGN_MAPS } from '../shared/campaign-registry';
import { resolveMapBalance, validateBalanceSettings } from '../shared/map-balance';
import { LIVE_BALANCE } from '../src/balance/live-balance';
// Fit log HP with fixed endpoints and a decreasing growth rate, rather than
// applying one repeated map multiplier. Separate role tracks also fix the late
// health-elite plateau without spreading its correction to other enemies.
const baseline = validateBalanceSettings(LIVE_BALANCE.settings);
const maps = CAMPAIGN_MAPS.map(m => resolveMapBalance(m.id, baseline, 0));
const roles = ['regular:damage', 'regular:health', 'regular:armor', 'elite:damage', 'elite:health', 'elite:regen'];
const tracks = maps.map((m, index) => Object.fromEntries(roles.map(role => {
  const [rank, type] = role.split(':');
  const enemies = Object.values(m.enemies);
  let matches = enemies.filter(e => Boolean(e.elite) === (rank === 'elite') && e.reward.type === type);
  // Forest's regen enemy is not elite; it is the starting regen-track anchor.
  if (!matches.length && index === 0 && role === 'elite:regen') matches = enemies.filter(e => e.reward.type === 'regen');
  if (!matches.length) throw new Error(`Missing ${role} anchor on ${m.mapId}`);
  return [role, Math.max(...matches.map(e => e.hp))];
})));
function fit(values: number[]) {
  const start = Math.log(values[0]), end = Math.log(values.at(-1)!);
  let numerator = 0, denominator = 0;
  values.forEach((hp, i) => {
    const t = i / (values.length - 1), bow = t * (1 - t);
    numerator += bow * (Math.log(hp) - start - (end - start) * t);
    denominator += bow * bow;
  });
  const curvature = Math.max(0, Math.min(end - start, numerator / denominator));
  return values.map((hp, i) => {
    if (i === 0 || i === values.length - 1) return hp;
    const t = i / (values.length - 1);
    return Math.exp(start + (end - start) * t + curvature * t * (1 - t));
  });
}
const fitted = Object.fromEntries(roles.map(role => [role, fit(tracks.map(t => t[role]))]));
const factors = Object.fromEntries(CAMPAIGN_MAPS.map((m, i) => [m.id,
  Object.fromEntries(roles.map(role => [role, fitted[role][i] / tracks[i][role]]))]));
writeFileSync('shared/campaign-health-curve.ts', `// Generated by scripts/smooth-campaign-health.ts from revision ${LIVE_BALANCE.revision}.\n// Fixed Forest/map 15 endpoints; each enemy role gets a log-quadratic fit\n// with tapering growth. Missing/new roles keep authored HP.\nexport const CAMPAIGN_HEALTH_FACTORS: Readonly<Record<string, Readonly<Record<string, number>>>> = ${JSON.stringify(factors, null, 2)};\n`);
mkdirSync('local-data/campaign-health', { recursive: true });
writeFileSync('local-data/campaign-health/curve.json', JSON.stringify(CAMPAIGN_MAPS.map((m, i) => ({map: m.id, before: tracks[i], after: Object.fromEntries(roles.map(role => [role, fitted[role][i]]))})), null, 2));
