import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { validateBalanceSettings } from "../shared/map-balance";

// One read-only join captures a consistent head + settings pair. No player data.
const query = "SELECT v.revision, v.settings_json FROM map_balance_version v JOIN map_balance_head h ON v.revision = h.revision";
const output = execFileSync(process.env.SPACETIME_BIN || "spacetime", [
  "sql", "wildwood-coop", "--server", "maincloud", "--format", "json", query,
], { encoding: "utf8", timeout: 30_000 });
const rows = JSON.parse(output)[0]?.rows;
if (rows?.length !== 1) throw new Error("Expected one live balance revision; previous snapshot retained.");
const [revision, json] = rows[0];
if (!Number.isSafeInteger(revision) || revision < 0) throw new Error("Invalid balance revision.");
const snapshot = { revision, capturedAt: new Date().toISOString(), database: "wildwood-coop",
  settings: validateBalanceSettings(JSON.parse(json)) };
writeFileSync(new URL("../src/balance/live-balance.ts", import.meta.url),
  // Typed, so live's version markers (baselineVersion: 2 and the rest) read as BalanceSettings, not plain numbers.
  `// Generated by npm run balance:sync. Read-only snapshot; refresh before a live audit.\nimport type { BalanceSettings } from "../../shared/map-balance-types";\n\nexport const LIVE_BALANCE: { revision: number; capturedAt: string; database: string; settings: BalanceSettings } = ${JSON.stringify(snapshot, null, 2)};\n`);
console.log(`Balance Lab captured maincloud revision ${revision}. No server changes.`);
